### ISSUE TITLE
Timeout incorrectly reported instead of actual failing assertion when using isEqualTo with SEPARATE_THREAD

### ISSUE THREAD

**Issue by mabre** [junit-team/junit5#3000] opened 2022-08-08 09:29 UTC
In some cases, JUnit reports an exceeded timeout although it is not exceeded. This seems to happen when using `SEPARATE_THREAD` and `isEqualTo`.

## Steps to reproduce

code to reproduce: https://github.com/hhu-progra/junit-timeout/

run `./gradlew test`

### Actual result:

The project contains two unit tests. Both (deliberatly) have failing assertions, but no timeout should occur.

For the first test (which uses `isEqualTo`), JUnit reports:

```
ExampleTest > test_reports_timeout_incorrectly() FAILED
    java.util.concurrent.TimeoutException: test_reports_timeout_incorrectly() timed out after 10 seconds
        at org.junit.jupiter.engine.extension.TimeoutExceptionFactory.create(TimeoutExceptionFactory.java:29)
        at org.junit.jupiter.engine.extension.SeparateThreadTimeoutInvocation.proceed(SeparateThreadTimeoutInvocation.java:43)
        at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
…
```

The tests run within 2 seconds, so reporting an exceeded timeout seems like a bug.

### Expected:

```
ExampleTest > test_reports_timeout_incorrectly() FAILED
    org.opentest4j.AssertionFailedError: 
    expected: 21
     but was: 42
        at java.base@17.0.3/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base@17.0.3/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base@17.0.3/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base@17.0.3/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at app//ExampleTest.test_reports_timeout_incorrectly(ExampleTest.java:8)
```

You get this expected output when removing `systemProperty "junit.jupiter.execution.timeout.default", "10"` or `systemProperty "junit.jupiter.execution.timeout.thread.mode.default", "SEPARATE_THREAD"` from `build.gradle`.

Note that the test using `contains` (and no `isEqualTo`) runs just fine in any case.

I just skimmed through the code and would guess that `SeparateThreadTimeoutInvocation` should check whether `failure.cause` is an `ExecutionTimeoutException` [here](https://github.com/junit-team/junit5/blob/e7130723ba11f8a6e14db141f5239d132f8284d4/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/SeparateThreadTimeoutInvocation.java#L42).

## Context

 - Used versions (Jupiter/Vintage/Platform): JUnit 5.9.0, Platform 1.9.0, AssertJ 3.23.1
 - Build Tool/IDE: Gradle 7.4

**Comment by gilbertojrequena** [comment] 2022-08-08 19:41
It seems like [this](https://github.com/junit-team/junit5/blob/e7130723ba11f8a6e14db141f5239d132f8284d4/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/SeparateThreadTimeoutInvocation.java#L42) handling is not needed since it is catching the wrong type of exception and also because the `assertTimeoutPreemptively` handles internally the timeout. Also, I realized that there are some inconsistencies in the exceptions generated by the `SameThreadTimeoutInvocation#proceed` and the `assertTimeoutPreemptively`. The former [throws](https://github.com/gilbertojrequena/junit5/blob/e7130723ba11f8a6e14db141f5239d132f8284d4/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/SameThreadTimeoutInvocation.java#L58) a `TimeoutException` when a timeout happens, and the latter [throws](https://github.com/gilbertojrequena/junit5/blob/e91e5dc26b86d0fc0a92f747f0b5dcdc9e5fbec2/junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertTimeout.java#L161) an `AssertionFailedError`. Should we make the exceptions thrown by both of them consistent? Is it ok if I create a fix for this bug, or the team wants to handle it internally?

**Comment by marcphilipp** [comment] 2022-08-10 05:42
> It seems like [this](https://github.com/junit-team/junit5/blob/e7130723ba11f8a6e14db141f5239d132f8284d4/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/SeparateThreadTimeoutInvocation.java#L42) handling is not needed since it is catching the wrong type of exception and also because the `assertTimeoutPreemptively` handles internally the timeout.

> Also, I realized that there are some inconsistencies in the exceptions generated by the `SameThreadTimeoutInvocation#proceed` and the `assertTimeoutPreemptively`. The former [throws](https://github.com/gilbertojrequena/junit5/blob/e7130723ba11f8a6e14db141f5239d132f8284d4/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/extension/SameThreadTimeoutInvocation.java#L58) a `TimeoutException` when a timeout happens, and the latter [throws](https://github.com/gilbertojrequena/junit5/blob/e91e5dc26b86d0fc0a92f747f0b5dcdc9e5fbec2/junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertTimeout.java#L161) an `AssertionFailedError`. Should we make the exceptions thrown by both of them consistent?

I think usage of `assertTimeoutPreemptively` in user code should continue to throw an `AssertionFailedError`. The `catch` block in `SeparateThreadTimeoutInvocation` currently makes it so they are consistent, doesn't it? But it's not specific enough since the invocation may throw an `AssertionFailedError` for different reasons (hence this issue).

I think we should create an internal overload of `assertTimeoutPreemptively` (or move it to a separate class) that can be configured with a factory/strategy for creating an exception which is then either `AssertionFailedError` or `TimeoutException`.

> Is it ok if I create a fix for this bug, or the team wants to handle it internally?

Please go ahead. I think we should release 5.9.1 as soon as this issue is fixed.

**Comment by gilbertojrequena** [comment] 2022-08-11 13:14
Just want to make sure I got it right, so the proposal is to extend the API and give the possibility to the user of `Assertions` to specify which exception should be thrown by the `assertTimeoutPreemptively`?

So it would be something like:

```
class Assertions {
  
    ...

    public static <T> T assertTimeoutPreemptively(Duration timeout, ThrowingSupplier<T> supplier,
			Supplier<String> messageSupplier, Throwing throwing) {
	return AssertTimeout.assertTimeoutPreemptively(timeout, supplier, messageSupplier, throwing);
    }

    public enum Throwing {
        ASSERTION_EXCEPTION,
        TIMEOUT_EXCEPTION
    }
    
     ...

}
```

**Comment by marcphilipp** [comment] 2022-08-11 15:38
No, this would only be available internally via a package-private method, if possible.

**Comment by gilbertojrequena** [comment] 2022-08-11 16:02
The problem is that it will not be visible for the `engine`, or am I missing something? 😅

**Comment by marcphilipp** [comment] 2022-08-12 12:50
No, you're right. In that case, we'll have to resort to making it public and use `@API(status = INTERNAL)`.

**Comment by mabre** [comment] 2022-09-05 06:38
I can confirm that #3005 fixes the issue in our original project.

**Closed** 2022-09-11 15:26 UTC
Labels: type: bug, theme: execution, status: in progress, component: Jupiter
