### ISSUE TITLE
@Timeout does not work when the test prints infinite output to stdout

### ISSUE THREAD

**Issue by SolalPirelli** [junit-team/junit5#2127] opened 2019-12-13 16:32 UTC
I'm using JUnit to grade coding exams. Students get points for each passing test, so it's important to me that failures from a single test are isolated - I don't want students' mistakes in one part of the code to affect other tests and cause them to lose more points than they should. Such mistakes sometimes include infinite loops in their code, meaning I need timeouts. And sometimes mistakes include printing text to stdout within an infinite loop...

## Steps to reproduce

Run the following test:

```java
import org.junit.jupiter.api.*;
import java.util.concurrent.*;

class Example {
    @Test
    @Timeout(value = 2, unit = TimeUnit.SECONDS)
    void test() throws InterruptedException {
        while(true) System.out.println("Hello");
    }
}
```

The test hangs, despite the timeout.

## Context

 - Used versions (Jupiter/Vintage/Platform): Jupiter
 - Build Tool/IDE: Gradle

On Ubuntu 18.04.3, using Gradle 6.0.1 (latest as of this report) and the following build.gradle:

```
plugins {
    id 'java'
}

repositories {
    jcenter()
}

dependencies {
    // JUnit 5 "Jupiter"
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.5.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.5.2'
}

test {
    useJUnitPlatform()
}
```

I run tests with `./gradlew build`.

Note that replacing the `while(true)` loop above with `Thread.sleep(60 * 1000)` causes the test to fail with a `TimeoutException`, as expected.

## Deliverables

- [ ] Make `@Timeout` work even when the test prints infinite output to stdout

**Comment by marcphilipp** [comment] 2019-12-14 13:10
Duplicate of #2087

**Closed by marcphilipp** 2019-12-14 13:10 UTC
