### ISSUE TITLE
The method annotated with @DisabledIf("customCondition") will execute the annotated method regardless of whether the value of customCondition is true or false! ! !

### ISSUE THREAD

**Issue by darrenluo1993** [junit-team/junit5#3015] opened 2022-08-26 08:00 UTC
```java
@Test
@DisabledIf("customCondition")
public void disabledIfTest() {
    System.out.println("Come in disabledIf");
}
private boolean customCondition() {
    return true;
}
```

Or

```java
@Test
@DisabledIf("customCondition")
public void disabledIfTest() {
    System.out.println("Come in disabledIf");
}
private boolean customCondition() {
    return false;
}
```

After execution, it will output: Come in disabledIf

**Comment by sormuras** [comment] 2022-08-26 08:07
Please translate your messages into English, thanks.

**Comment by darrenluo1993** [comment] 2022-08-26 08:42
@sormuras Hello, it has been translated into English.

**Comment by sbrannen** [comment] 2022-08-26 13:32
I cannot reproduce that behavior.

The following prints only "customCondition".

```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.DisabledIf;

public class DisableIfDemoTests {

	@Test
	@DisabledIf("customCondition")
	public void disabledIfTest() {
		System.err.println("disabledIfTest");
	}

	private boolean customCondition() {
		System.err.println("customCondition");
		return true;
	}

}
```

Are you sure you imported `org.junit.jupiter.api.Test` and not some other `@Test` annotation?

**Comment by sbrannen** [comment] 2022-08-29 12:40
Due to the above comment and lack of a response, I'm closing this as "invalid".

**Closed by sbrannen** 2022-08-29 12:40 UTC
Labels: type: question, component: Jupiter, status: waiting-for-feedback, status: new

**Comment by darrenluo1993** [comment] 2022-08-31 01:46
@sbrannen Sorry for replying only now, I just tried the case you wrote. If the DisableIfDemoTests class is executed, the expected effect can be achieved, but if the disabledIfTest method is executed, it will output: disabledIfTest.
```java
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.DisabledIf;

public class DisableIfDemoTests {

	@Test
	@DisabledIf("customCondition")
	public void disabledIfTest() {
		System.err.println("disabledIfTest");
	}

	private boolean customCondition() {
		System.err.println("customCondition");
		return true;
	}

}
```

**Comment by sbrannen** [comment] 2022-08-31 09:52
> Sorry for replying only now, I just tried the case you wrote. 

No worries. Thanks for trying it out and providing the feedback.

> If the DisableIfDemoTests class is executed, the expected effect can be achieved, but if the disabledIfTest method is executed, it will output: disabledIfTest.

That's a feature of IntelliJ IDEA: IDEA disables conditions for a given test method if you ask IDEA to run a single test method.

**Comment by darrenluo1993** [comment] 2022-08-31 10:57
@sbrannen Okay, I understand now, thanks!
