### ISSUE TITLE
PreDestroy callback is not invoked for enclosing instances of nested classes

### ISSUE THREAD

**Issue by paschi** [junit-team/junit5#2430] opened 2020-09-30 13:43 UTC
## Actual behavior

I have a JUnit extension which implements the `TestInstancePostProcessor` and `TestInstancePreDestroyCallback`. When using this extension for a test class with inner nested test classes, if the lifecycle of the enclosing class is `PER_METHOD`, then an instance of the enclosing class is created for the tests in the nested class, as well as a nested instance for each or all of the tests (depending on the lifecycle of the nested class). The post-process hook is then called for the enclosing instance and the nested instances, but the pre-destroy hook is only called for the nested instances and not for the enclosing instance.

## Expected behavior

The post-process and pre-destroy hooks are called both for the nested instances as well as for the enclosing instance.

## Steps to reproduce

Example test which shows the behavior:
```java
@ExtendWith(OuterTests.LifecycleExtension.class)
class OuterTests {
    @Test
    void testOuter1() {
        System.out.println("testOuter1");
    }

    @Test
    void testOuter2() {
        System.out.println("testOuter2");
    }

    @Nested
    class InnerTests {
        @Test
        void testInner1() {
            System.out.println("testInner1");
        }

        @Test
        void testInner2() {
            System.out.println("testInner2");
        }
    }

    static class LifecycleExtension implements TestInstancePostProcessor, TestInstancePreDestroyCallback {
        @Override
        public void postProcessTestInstance(Object testInstance, ExtensionContext context) {
            System.out.println("postProcess: " + testInstance);
        }

        @Override
        public void preDestroyTestInstance(ExtensionContext context) {
            System.out.println("preDestroy: " + context.getRequiredTestInstance());
        }
    }
}
```

Output for lifecycle = PER_METHOD for outer and inner class (indentations for better readability):
```
postProcess: mypackage.OuterTests@7bedc48a
-- testOuter1
preDestroy: mypackage.OuterTests@7bedc48a

postProcess: mypackage.OuterTests@38e79ae3
-- testOuter2
preDestroy: mypackage.OuterTests@38e79ae3

postProcess: mypackage.OuterTests@63070bab
-- postProcess: mypackage.OuterTests$InnerTests@291b4bf5
---- testInner1
-- preDestroy: mypackage.OuterTests$InnerTests@291b4bf5

postProcess: mypackage.OuterTests@2d2ffcb7
-- postProcess: mypackage.OuterTests$InnerTests@762ef0ea
---- testInner2
-- preDestroy: mypackage.OuterTests$InnerTests@762ef0ea
```

Output for lifecycle = PER_CLASS for outer and inner class (indentations for better readability):
```
postProcess: mypackage.OuterTests@fa4c865
-- testOuter1
-- testOuter2

-- postProcess: mypackage.OuterTests$InnerTests@2d2ffcb7
---- testInner1
---- testInner2
-- preDestroy: mypackage.OuterTests$InnerTests@2d2ffcb7
preDestroy: mypackage.OuterTests@fa4c865
```

## Context

 - Used versions (Jupiter/Vintage/Platform): JUnit Jupiter 5.7.0
 - Build Tool/IDE: Maven 3.6.3, IntelliJ IDEA 2020.2, OpenJDK 11

**Comment by sbrannen** [comment] 2020-09-30 14:16
Thanks for raising the issue and providing the example! 👍 

I have confirmed the behavior against `main` and am therefore labeling this as a bug.

**Comment by rishiCS** [comment] 2020-10-22 11:21
@sbrannen @paschi Assign this issue to me please.

**Comment by sbrannen** [comment] 2020-10-22 12:24
@rishiCS, the fix for this might be rather involved.

Thus, before starting on a PR, why don't you research the issue and outline a proposal for fixing it here?

That way the team could provide feedback before you get knee-deep in a PR.

Or if you feel confident in your proposal, feel free to go ahead and submit a PR.

**Comment by marcphilipp** [comment] 2020-10-25 12:57
I'll take a look.

**Comment by marcphilipp** [comment] 2020-10-25 14:31
@paschi Here's a workaround that does what you need:

```java
static class LifecycleExtension implements TestInstancePostProcessor, TestInstancePreDestroyCallback {
    @Override
    public void postProcessTestInstance(Object testInstance, ExtensionContext context) {
        System.out.println("postProcess: " + testInstance);
    }

    @Override
    public void preDestroyTestInstance(ExtensionContext context) {
        List<Object> destroyedInstances = new ArrayList<>(context.getRequiredTestInstances().getAllInstances());
        for (Optional<ExtensionContext> current = context.getParent(); current.isPresent(); current = current.get().getParent()) {
            current.get().getTestInstances().map(TestInstances::getAllInstances).ifPresent(destroyedInstances::removeAll);
        }
        Collections.reverse(destroyedInstances);
        destroyedInstances.forEach(testInstance -> System.out.println("preDestroy: " + testInstance));
    }
}
```

**Comment by marcphilipp** [comment] 2020-10-25 14:39
Since `TestInstancePreDestroyCallback` is often paired with `TestInstancePostProcessor` we should try to make them more symmetric. While the former is currently called once per test instance, the latter is only called once per extension context. Moreover, while the former is passed the `ExtensionContext` corresponding to the test class, the latter is passed that of the test method. Thus, I think we should introduce a new `preDestroyTestInstance(Object testInstance, ExtensionContext context)` extension method that is called the same number of times and with the same parameters as `postProcessTestInstance`, only in reverse order of test instances. However, we've cannot add another method to `TestInstancePreDestroyCallback` while making the existing one `default` since it's annotated with `@FunctionalInterface`. Thus, our only option is to introduce a new interface, e.g. `TestInstancePreDestroyProcessor`, and deprecate the old one.

**Comment by marcphilipp** [comment] 2020-10-25 14:39
Tentatively slated for 5.8 M1 solely for the purpose of _team discussion_.

**Comment by marcphilipp** [comment] 2020-11-13 11:36
**Team decision:** Investigate fixing this without introducing a new interface.

**Closed** 2020-12-13 13:30 UTC
Labels: component: Jupiter, status: team discussion, theme: extensions, type: bug
