### ISSUE TITLE
Add support for dynamic display names

### ISSUE THREAD

**Issue by mfulton26** [junit-team/junit5#826] opened 2017-05-01 18:37 UTC
## Overview

Dynamic tests allow specifying display names dynamically but static tests do not. The `DisplayName` annotation takes a constant `String` as its value.

A user can create a `TestFactory` method to create a single dynamic test in order to dynamically define a single test's display name but this results in undesirable nesting. e.g.:

```java
class DemoTests {
    @TestFactory
    Stream<DynamicTest> createCurrentYearTest() {
        Year currentYear = Year.now();
        String displayName = String.format("Year should be current year (%s)", currentYear);
        return Stream.of(dynamicTest(displayName, () -> {
            // ...
        }));
    }
}
```

## Deliverables

- [ ] A simple way to dynamically specify a display name for a single, non-nested test.

**Comment by mfulton26** [comment] 2017-05-01 18:38
One way to do this might be to support returning `DynamicTest` directly from a `TestFactory` method thereby eliminating the nesting and simply specifying a single dynamic test.

**Comment by sbrannen** [comment] 2017-05-01 22:43
Closing this issue as a duplicate of #162.

**Closed by sbrannen** 2017-05-01 22:43 UTC

**Comment by mfulton26** [comment] 2017-05-02 00:49
I didn't see that one. Thank you.
