### ISSUE TITLE
Allow for BeforeAllCallback and AfterAllCallback extensions methods to be executed only on root class

### ISSUE THREAD

**Issue by apontini** [junit-team/junit5#2831] opened 2022-02-16 09:13 UTC
I have the following extension:
```java

import org.junit.jupiter.api.extension.AfterAllCallback;
import org.junit.jupiter.api.extension.AfterEachCallback;
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.BeforeEachCallback;
import org.junit.jupiter.api.extension.ExtensionContext;

public class TestExt implements BeforeAllCallback, AfterAllCallback, BeforeEachCallback, AfterEachCallback {

  @Override
  public void afterAll(ExtensionContext context) throws Exception {
    System.out.println("================== EXT AFTER ALL");
  }

  @Override
  public void afterEach(ExtensionContext context) throws Exception {
    System.out.println("================== EXT AFTER");
  }

  @Override
  public void beforeAll(ExtensionContext context) throws Exception {
    System.out.println("================== EXT BEFORE ALL");
  }

  @Override
  public void beforeEach(ExtensionContext context) throws Exception {
    System.out.println("================== EXT BEFORE");
  }
}

```
Which is used in the following test.
```java

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(TestExt.class)
@TestInstance(Lifecycle.PER_CLASS)
public class ProvaIT {

  @BeforeAll
  public static void beforeAll() {
    System.out.println("================== BEFORE ALL");
  }

  @BeforeEach
  public void before() {
    System.out.println("================== BEFORE");
  }

  @AfterAll
  public static void afterAll() {
    System.out.println("================== AFTER ALL");
  }

  @AfterEach
  public void after() {
    System.out.println("================== AFTER");
  }

  @Nested
  @DisplayName("Nested test 1")
  public class Nested1Test {

    @Test
    @DisplayName("Test 1")
    public void test1() {
      System.out.println("================== TEST 1");
    }

    @Test
    @DisplayName("Test 2")
    public void test2() {
      System.out.println("================== TEST 2");
    }

  }

  @Nested
  @DisplayName("Nested test 2")
  public class Nested2Test {

    @Test
    @DisplayName("Test 3")
    public void test3() {
      System.out.println("================== TEST 3");
    }

    @Test
    @DisplayName("Test 4")
    public void test4() {
      System.out.println("================== TEST 4");
    }

  }

}
```
The standard output result is:
```
================== EXT BEFORE ALL
================== BEFORE ALL
================== EXT BEFORE ALL
================== EXT BEFORE
================== BEFORE
================== TEST 3
================== AFTER
================== EXT AFTER
================== EXT BEFORE
================== BEFORE
================== TEST 4
================== AFTER
================== EXT AFTER
================== EXT AFTER ALL
================== EXT BEFORE ALL
================== EXT BEFORE
================== BEFORE
================== TEST 1
================== AFTER
================== EXT AFTER
================== EXT BEFORE
================== BEFORE
================== TEST 2
================== AFTER
================== EXT AFTER
================== EXT AFTER ALL
================== AFTER ALL
================== EXT AFTER ALL
```

As far as I could understand from googling, reading docs and from stackoverflow, there's no actual way to tell jUnit to execute the extension's `beforeAll` and `afterAll` methods only on the root class instead of executing them for each nested class. This could be a nice-to-have feature which imho would improve extensions flexibility.
My problem arose when I tried using nested classes with an extension which initialized a `MockServer` instance on its `beforeAll` method: tests were failing due to the fact that the `beforeAll` method was called once for the root class and once for every nested class, which lead to a `RuntimeException` because the port was already binded by the previous MockServer instance.

Some solutions that I came up with include:

- checking that the enclosing test class is null and, if it is, only then initialize the `MockServer` instance
- checking that the `MockServer` wasn't already initialized and, if it is, don't initialize it again

but these feel like hacks to me.

**Comment by sbrannen** [comment] 2022-02-16 09:52
Use cases like this are already supported via the `ExtensionContext.Store`.

In your `beforeAll()` method in your extension, you should use `org.junit.jupiter.api.extension.ExtensionContext.Store.getOrComputeIfAbsent(K, Function<K, V>)` for the creation/retrieval of the `MockServer` instance.

Please give that a try and let us know if you run into any issues.

**Comment by apontini** [comment] 2022-02-16 10:04
I'll try as soon as possible! Thanks for the quick response.

**Comment by apontini** [comment] 2022-02-25 11:52
Sorry for the delay but I haven't had the change to try this sooner.
By using `getOrComputeIfAbsent` I solved this problem on tests initialization but it's still much the same on test teardown:
if I want to close the `MockServer`, I can't do it once every test is completed because if I put close it in the `AfterAllCallback`, `MockServer` will be closed after each test class (and, closed twice at the very end since there are two callbacks to the `AfterAllCallback`), which is not what I want.

**Comment by miralexan** [comment] 2022-02-28 02:31
@apontini have you looked at [`ExtensionContext.Store.CloseableResource`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/extension/ExtensionContext.Store.CloseableResource.html)? It may solve your problem by letting Junit close the mock server once the extension context associated with your test is closed.

<https://junit.org/junit5/docs/current/user-guide/#extensions-keeping-state>

**Comment by sbrannen** [comment] 2022-02-28 16:50
Hi @apontini,

> By using `getOrComputeIfAbsent` I solved this problem on tests initialization 

Glad that works for you.

> but it's still much the same on test teardown:

@miralexan is correct: the solution for single tear-down is `CloseableResource`. We are aware of the fact that this is not well documented. 

- See #1555 for details.

In light of that, I am closing this issue as effectively a duplicate of #1555; however, if you run into issues implementing the solution feel free to post back here with additional information.

**Closed by sbrannen** 2022-02-28 16:50 UTC
Labels: type: question, theme: extensions, component: Jupiter, status: waiting-for-feedback, status: new

**Comment by apontini** [comment] 2022-03-01 10:03
Alright, I'll give it a try, thank you for your support!
