### ISSUE TITLE
Associate a test with a method

### ISSUE THREAD

**Issue by abarhub** [junit-team/junit5#857] opened 2017-05-18 20:21 UTC
Hello,

Why i can't set the method tested in the Test annotation ?

I think it is a good practice to test a single method.
And with that, you can run all test associate with a method.
It can be a string in the annotation.

For exemple : 
`
@Test(method="Class1.method")
public void test1() {
...
}
`

Thank you

**Comment by jbduncan** [comment] 2017-05-18 20:40
Hi @abarhub, can you explain what purpose this would serve? Your current explanation is very sparse.

**Comment by Andrei94** [comment] 2017-06-16 17:19
@jbduncan I think he means to be able to run all the tests for a method by specifying the name in the `@Test` annotation. 
For example, if you have a method which finds the prime factors of a number, you should be able to discover, based on the parameters of the annotation, which test methods correspond to this method(prime factors of 2, prime factors of 4 and so on...).

**Comment by jbduncan** [comment] 2017-06-18 13:09
Okay, that would make some sort of sense. Thanks @Andrei94.

@abarhub Does @Andrei94's hypothesis-explanation accurately convey what you'd like to come out of this issue?

**Comment by abarhub** [comment] 2017-06-18 17:53
Yes, @Andrei94 said exactly what I meant.

I do not master English enough to explain it better.

Sorry for my bad English.

**Comment by sbrannen** [comment] 2017-06-19 14:50
I am closing this issue since it is a duplicate of #510.

**Closed by sbrannen** 2017-06-19 14:50 UTC
