### ISSUE TITLE
Include @author tags in Java source code

### ISSUE THREAD

**Issue by sbrannen** [junit-team/junit5#914] opened 2017-07-04 14:51 UTC
## Background

Historically, Java source code within the JUnit code base has not included `@author` tags.

As an exception to the rule, there are (as of the time of this writing) 15 occurrences of `@author` tags within the JUnit 4 code base.

The JUnit Lambda prototype included `@author` tags in the Javadoc for all top-level types, but those tags were removed before JUnit 5.0 Alpha was released.

While it's true that anyone can load the [contributors page](https://github.com/junit-team/junit5/graphs/contributors) to see who has contributed, that is something that very few people actually do, and it doesn't carry the same weight as an `@author` tag which finds its way into the IDEs of thousands of developers worldwide. 

## Impetus for Change

Over the course of the past year and a half, I (Sam Brannen) have had discussions with numerous would-be contributors who all said that they would find it not only appropriate to include `@author` tags but also (more importantly) an incentive to be a committer to an open source project like JUnit. The rationale varied from "the coolness factor" to "something to be visibly proud of" to "something to impress my current employer and future potential employers".

### Benefits Above and Beyond Git History

The presence of `@author` tags has benefits above and beyond those provided by tools such as git history and git blame.

- `@author` tags still tell you something about the history of a file even when tools such as git history and git blame cannot tell the whole story (e.g., because the information has been lost due to refactorings, renaming/moving projects, etc.)
- See the following comments for further benefits of `@author` tags
   - https://github.com/junit-team/junit5/issues/914#issuecomment-312963347
   - https://github.com/junit-team/junit5/issues/914#issuecomment-312965419

### Potential Legal Ramifications

Furthermore, there are potential legal ramifications associated with *not* including `@author` tags as pointed out [here](https://twitter.com/aalmiray/status/882255680530415618). Also, the Eclipse Public License version 1.0 contains the following requirement.

> Each Contributor must identify itself as the originator of its Contribution, if any, in a manner that reasonably allows subsequent Recipients to identify the originator of the Contribution.

## Proposal

Avoid potential legal issues and honor all open source contributors by including `@author` tags in Java source code and including author information as part of the published Javadoc.

**Comment by sbrannen** [comment] 2017-07-04 15:14
Update: added note on potential legal ramifications.

**Comment by Andrei94** [comment] 2017-07-04 15:17
We could use more `@author` tags inside the header of the source file. That way, there wouldn't be a lot of `@author` tags inside actual code that may remain there even though someone else changed some parts of it.

**Comment by Andrei94** [comment] 2017-07-04 15:37
Or how about a custom tag `@contributor`? [They seem to be doable](https://stackoverflow.com/questions/2677564/how-to-create-custom-javadoc-tags) We would just have to modify gradle build 😉

**Comment by jbduncan** [comment] 2017-07-04 16:02
@sbrannen Would the addition of `@author` tags be applicable for contributors such as myself who made contributions in the past but, in light of this issue, would quite like their past contributions to be properly attributed as well?

**Comment by slu-it** [comment] 2017-07-04 17:23
Found this issue over Twitter. The problem with `@author` tags is, that over time they generally turn into lies. If I look at some 5 year old code, with a hand full of `@author` tags, I can't tell who did what, and who's code is even still part of the class. I always interpreted their original intend to be a reference for people to ask questions in case something doesn't work anymore. But that's hardly ever truly useful even in a corporate environment - at least after a few years of change. As part of the source code's documentation `@author` tags are completely useless (in my opinion).

If you want't to show your oss-cred as a developer, you can always point to commits, pull requests, issues or the official mentions of your contribution on a contributor page. Pull requests and issues are especially useful for demonstrating what improvements you brought to an open source project.

@Andrei94 I'm not sure about `@contributor`, but it would at least change the meaning of the tag to something true. "These people have contributed to this class."

**Comment by Andrei94** [comment] 2017-07-04 18:29
@slu-it I agree with the fact that they eventually turn into lies. Isn't it because nobody ensures that they stay up to date? I see these `@author` tags in most of the files from the work and they don't add very much value to the code. 

@sbrannen Perhaps we can have some gradle task to run and dynamically generate the `@author`/`@contributor` tags by looking at who commited changes to a file and at which lines (in case more precision is needed 😄). When the person does not have any more changes there, that person should be removed. (not really sure about removal, whether is okay, but it might work)

**Comment by jbduncan** [comment] 2017-07-04 18:31
Now that @slu-it mentions it, I think I actually agree with his viewpoint on this.

IIRC, Google is currently in the process of removing `@author` tags from their Java open source projects, because they don't accurately reflect who initially wrote certain source files and who made additions/changes/deletions to particular areas in those source files over time. So I'd be tempted to follow their example.

**Comment by jbduncan** [comment] 2017-07-04 18:40
But having said that, @Andrei94's idea of generating `@contributor` tags automatically sounds neat to me in theory, so I'd be interested to see it developed further. It may turn out to be practical, it may turn out not to be. But if it does, then it may make contributor's efforts a bit more visible (leaving people who are interested to know more about who did what to use appropriate tools to dig into the git history).

**Comment by jbduncan** [comment] 2017-07-04 18:46
Regarding the potential legal ramifications of _not_ including `@author` tags, well that's a tricky area where I have little to no experience, as (admittedly) my understanding of EPL 1.0 is far from comprehensive... :thinking:

**Comment by jbduncan** [comment] 2017-07-04 18:47
How do companies like IBM (who use EPL 1.0 IIRC) deal with this situation?

**Comment by slu-it** [comment] 2017-07-04 18:50
@Andrei94 as far as I've observed over the years, people there a couple of reasons:

1. people tend to not want to remove credit from other people (seen as rude)
2. it's to much effort to track back whether or not an `@authot` tag is still reasonable
3. people don't care

In every project I head some form of control over things like this, I killed `@author` tags and nobody ever missed them. But those where mostly corporate projects.. 

@jbduncan i don't think `@author` has any real legal impact.

> "... in a manner that reasonably allows subsequent Recipients to identify the originator..."

I think for anyone on contributing to a GitHub project, it is reasonable to assume they can `git blame`.

**Comment by jbduncan** [comment] 2017-07-04 19:10
It seems that Eclipse (and by extension IBM) deal with this sort of legal situation by specifying who did what at the bottom of the license header of each source file in their EPL-v1.0-licensed projects.

To give an example: https://github.com/eclipse/eclipse.jdt.core/blob/master/org.eclipse.jdt.core/compiler/org/eclipse/jdt/core/compiler/CharOperation.java

Might this be a good pattern for JUnit 5 to follow?

**Comment by Andrei94** [comment] 2017-07-04 19:32
@jbduncan the message alongside the person name could be taken from the commit message. Nevertheless, as @slu-it pointed out, official mentions of your contribution such as pull requests, commits and issues are your best solution.

**Comment by rstoyanchev** [comment] 2017-07-04 22:42
I think it's more than just credit and legal. Open source projects are all about people. Seeing author tags tells fly by tells me who left a mark in a particular area. After a while If a specific name flies by a lot in some subsystem I begin to associate that person with that functionality and that helps me to learn about a project, about the people's style, and could also be beneficial when discussing issues and requests. So I definitely like to see them and it's not something easy to derive otherwise.

I realize the experience can vary widely especially on projects where people come and go. If a project wants to systematically remove all author tags that's a strong indication of a situation like that. I'm not saying it's bad necessarily and I personally don't see this as a reason to remove author tags. 

On the other hand lots of @author tags could also mean made people made small tweaks. To me this is noise that I don't like to see. I favor using some (subjective) judgement and include @author tags for most but the most trivial and straight forward fixes. In other words author tags are useful as a loose indicator of code ownership and commit history contains the next level of detail down to the line number and commit.

**Comment by garyrussell** [comment] 2017-07-04 23:12
I don't understand all the angst about staleness; the word "lies" seems a bit extreme too.

`git blame` (and commit history) will show you who actually changed what.

`@author` also provides credibility when somebody talks about a project at a conference.

As a (relatively new, but now 7yr) Spring ecosystem committer, recognition is generally not an issue for me but, in my first few years, I can't count how many times people came up to me at conferences and said things like "I like project X and came to your talk because I see your name all over the code base".

An author tag for fixing a typo in a log message would not be valid IMHO, but anyone who provides a significant feature/bug fix/improvement should get credit.

People who contribute a lot should get commensurate recognition by casual observers, without the observer having to dig into the contributor's page. People who contribute only a little will get little recognition; seems like `@author` automatically provides that filter.

**Comment by slu-it** [comment] 2017-07-05 06:47
I think @sbrannen 's poll on twitter is a good way of getting some data from the community. Currently it seems to be: a lot of people don't care either way and of those who do, the pro-author tags are in the lead. The topic itself is very subjective (possible legal specialities from the Eclipse license aside) - kinda like spaces and tabs and where to put the curly braces...

Even though I dislike `@author` tags in general, I can also see @garyrussell 's point. Most users of JUnit will never checkout this repository but they will see the source code at one point or another.

As to @rstoyanchev 's points: I'm not sure about _subjectively_ adding `@author` tags, who decides when an `@author` was earned? Should people always add them and during review of the PR, they might get told to remove it? The other way around?

@Andrei94 's ideas of an `@cotributor` tag are currently my favourite solution to the "giving credit" problem. I'm not sure about generating them, it might be enough to add them to the codebase and make them usable by the community (not sure if it is as easy as that).

But to play devil's advocate with myself: `@contributor` is just a slightly more contextual word for `@author`. So maybe the extra effort is not worth it - just allow `@author`?

**Comment by ttddyy** [comment] 2017-07-05 14:27
As a contributor to opensource, I feel good if my name shows up on sourcecode.
On the other hand, I agree opinions pointed by others in this thread about `@author` tag.

Alternatively, how about adding contributors on release notes or dedicated file(e.g. `CONTRIBUTORS.md`) for each release.
Format can be vary. It can be just a list of names or can include who did what.
Also, it can include contributors who worked on non source code or non java code.

**Comment by rstoyanchev** [comment] 2017-07-06 17:45
Subjective adding `@author` tags is not as bad as it sounds. It's one of those things where it's easy to understand and adhere to the principle but there will always be some degree of subjectivity. The goal is not to create a strict cut-off line but rather to eliminate certain obvious cases that would simply dilute the `@author` tags. 

One could compare to book authors where you also have reviewers and comments from readers that result in edits but just because someone has an impact on the book doesn't make them an author. As with any analogy this one also falls apart pretty easily but hopefully it helps to communicate the idea.

If a change is relatively minor such as minor edits to the Javadoc, adding missing hashcode/equals or modifiers, fixing faulty boolean checks, adding log statements, and a long list of other such minor possible changes, arguably you shouldn't add yourself as `@author`. This isn't to say your change isn't important or you don't deserve credit. You still get credit from being on the commit log and Github makes it very nice to see who has how many commits, number of lines edited, so the stats and credit are still there, just not in the source code. 

A project's wiki can lay this out with specific example like the above in order to set expectations. Then project committers who process pull requests can have the final say. I doubt this would create disputes and if in doubt why not just add the `@author` tag. You're still going to have plenty of noise filtered out and that's the idea.

**Comment by Thunderforge** [comment] 2017-07-06 22:08
To be brutally honest, if I could get a JUnit `@author` tag, I would do as little work as possible to warrant earning an `@author` tag, preferably on a commonly used class, then move to some other project once I have the bragging rights that I'm a JUnit `@author`. 

While I suppose it's a good thing that I worked on a project I wouldn't have otherwise contributed to, I'm not sure that this is the sort of outcome that the project is looking for. I think that contributors should want to contribute because they want to improve the project, not because they want name recognition.

Also, say that we reach a point where we have too many `@author` tags that it starts becoming noise. How would we go about pruning the list? As @slu-it pointed out, it's often seen as rude to delete someone's authorship, so I think that there might be some disagreements at that point.

**Comment by JLLeitschuh** [comment] 2017-08-04 02:04
This is a quote from the awesome book [Team Geek](http://shop.oreilly.com/product/0636920018025.do) that I quote whenever this topic comes up on new projects that I Work on:

> # Putting Your Name in Source Code Files
> *(a.k.a., the “Author Tags” Issue)*
>
> Everyone wants to get credit for work they do, from the artist 
who signs her painting to the author who puts her name on the
spine of her book or the top of her blog. It’s human nature to crave
recognition in one way or another, but littering source files with
your name is, in our opinion, more trouble than it’s worth. We’ve
all seen these attributions at the top of source files, nestled snugly
against the copyright declarations:
> ```
> ————————————---—————————————————
> Created: October 1998 by Brian W. Fitzpatrick <fitz@red-bean.com>
> ————————---—————————————————————
> ```
> The tradition of putting your name at the top of your source code
is an old one (heck, both of us have done it in the past), and may
have been appropriate in an age where programs were written by
individuals and not teams. Today, however, many people may touch
a particular piece of code, and the issue of name attribution in a file
is the cause of much discussion, wasted time, and hurt feelings. As a
result, we advocate strongly against names as a sign of ownership in
source code files (at best, include a name to designate a first choice 
to review any changes you might make to the file, but be careful
that you don’t imply ownership).
Let’s imagine, for example, that you create a new file in your team’s
project—you write a few hundred lines of code, smack your name
and the appropriate copyright header at the top of the file and send
it off for code review, and later, commit it to the repository. No
problems, no drama, no disagreements so far. Let’s say that your
teammate Adrian comes along and makes some changes to the file:
at what point does he get to put his name at the top of the file? Does
he have to fix a bug? Five bugs? Does he have to write a function?
Two functions? How many lines of code does he have to write?
What if he writes a function, slaps his name on the file, and then
someone else comes along and rewrites “his” function? Does this
person now get to put her name on the file? Does she get to take
Adrian’s name off? Unlike other collaborative pieces of creative
work—plays, novels, films—software keeps changing even after it’s
“done.” So, while listing contributor credits at the end of a movie is
a safe and static thing, attempting to add and remove names from a
source file is a never-ending exercise in insanity.
Certainly you can answer all these questions and extensively
document every possible edge case, but maintaining this, tracking
it, and keeping an eye out for violations is an incredible waste of
time—time that could be spent actually writing code. It’s for this
very reason that we advocate tracking credit at the project level, 
not in the code itself. If you need more detail, your version control
system can tell you. All those moments will be lost in time, like tears
in rain.
>
>\- Team Geek: A Software Developer's Guide to Working Well with Others, Brian Fitzpatrick, Ben Collins-Sussman

I personally tend to be in the camp of not having author tags in the code and letting git do the authorship documentation for me.

**Comment by bechte** [comment] 2017-09-07 04:24
I personally do understand both ways of doing it and I am not in favour of any way. But we should decide on it and put the topic aside. ;-)

**Comment by sbrannen** [comment] 2017-09-07 15:45
Introduced _Benefits Above and Beyond Git History_ section to this issue's description.

**Comment by JLLeitschuh** [comment] 2017-09-07 16:22
Re Eclipse Public License:  
> Each Contributor must identify itself as the originator of its Contribution, if any, in a manner that reasonably allows subsequent Recipients to identify the originator of the Contribution.

Git history goes back to the beginning of the repository. Isn't that enough?

--- 

Re: Needing recognition

Personally, I see my github profile as sufficiently providing that history.
I'm going to [re-quote a subsection of the quote above](https://github.com/junit-team/junit5/issues/914#issuecomment-320136804):

>  Let’s say that your teammate Adrian comes along and makes some changes to the file: at what point does he get to put his name at the top of the file? Does he have to fix a bug? Five bugs? Does he have to write a function? Two functions? How many lines of code does he have to write? What if he writes a function, slaps his name on the file, and then someone else comes along and rewrites “his” function? Does this person now get to put her name on the file? Does she get to take Adrian’s name off? Unlike other collaborative pieces of creative work—plays, novels, films—software keeps changing even after it’s “done.” So, while listing contributor credits at the end of a movie is a safe and static thing, attempting to add and remove names from a source file is a never-ending exercise in insanity. 
> Certainly you can answer all these questions and extensively document every possible edge case, but maintaining this, tracking it, and keeping an eye out for violations is an incredible waste of time—time that could be spent actually writing code. It’s for this very reason that we advocate tracking credit at the project level, not in the code itself.

If you were to implement the `@author` tag, what rules would be implemented?

**Comment by sbrannen** [comment] 2017-09-07 16:28
> Git history goes back to the beginning of the repository. Isn't that enough?

No.

If you move files or refactor them to the extent that git does not recognize them as the same files (just renamed/moved), the history is not traceable and you consequently can no longer see the original authors of the files.

But the `@author` tag remains in place in such situations.

**Comment by sbrannen** [comment] 2017-09-07 16:31
> If you were to implement the `@author` tag, what rules would be implemented?

We would do something along the lines of what was proposed by @rstoyanchev: https://github.com/junit-team/junit5/issues/914#issuecomment-313468920

This practice has met with much success in the Spring Framework, and I have never encountered a single issue (e.g., debate) regarding `@author` tags when I have processed pull requests and contributions to the Spring Framework over the past decade.

**Comment by jbduncan** [comment] 2017-09-08 08:43
@sbrannen 

>> Git history goes back to the beginning of the repository. Isn't that enough?
> No.
>
> If you move files or refactor them to the extent that git does not recognize them as the same files (just renamed/moved), the history is not traceable and you consequently can no longer see the original authors of the files.

Oh, really? Does not `git log --follow path/to/potentially/renamed/file` (which I discovered recently over at this [SO question](https://stackoverflow.com/questions/2314652/is-it-possible-to-move-rename-files-in-git-and-maintain-their-history)) work for you in such situations?

**Comment by marcphilipp** [comment] 2017-09-08 11:27
Thank you all for your valuable input! We have thoroughly discussed this issue in the team. We were not able to reach a consensual decision. Thus, in my role as JUnit's current benevolent dictator (["keeper of the green bar"](https://groups.yahoo.com/neo/groups/junit/conversations/topics/24737)), I have taken it upon myself to decide:

**We will continue to not include `@author` tags in source files.**

I will document this decision in our contribution guidelines later today. I have closed this issue for additional comments because by now everyone has had a chance to voice her opinion and all arguments have been heard. Now, we want to focus on the upcoming GA release.

**Comment by marcphilipp** [comment] 2017-09-08 20:10
Contribution Guidelines have been updated, Checkstyle check has been added.

**Closed by marcphilipp** 2017-09-08 20:10 UTC
Labels: component: Jupiter, component: Platform, component: Vintage, theme: documentation, type: task
