### ISSUE TITLE
@BeforeEach & @AfterEach methods are not invoked using extensions registered at the test method level

### ISSUE THREAD

**Issue by schlauergerd** [junit-team/junit5#523] opened 2016-09-26 12:16 UTC
A ParameterResolver, which is configured at test-method-level, is not used for the corresponding BeforeEach-method.

Given this test class:
```java
public class DummyTest {

    @BeforeEach
    public void setUp(MyParameter param) {
        System.out.println("setUp with " + param.value);
    }

    @Test
    @ExtendWith(FirstParameterResolver.class)
    public void firstTest(MyParameter param) {
        System.out.println("running with " + param.value);
    }

    @Test
    @ExtendWith(SecondParameterResolver.class)
    public void secondTest(MyParameter param) {
        System.out.println("running with " + param.value);
    }

    // inlined for completeness

    static class MyParameter {

        public String value;

        public MyParameter(String value) {
            this.value = value;
        }

    }

    static class FirstParameterResolver implements ParameterResolver {

        @Override
        public boolean supports(ParameterContext parameterContext, ExtensionContext extensionContext) throws ParameterResolutionException {
            return true;
        }

        @Override
        public Object resolve(ParameterContext parameterContext, ExtensionContext extensionContext) throws ParameterResolutionException {
            return new MyParameter("FirstParameterResolver");
        }

    }

    static class SecondParameterResolver implements ParameterResolver {

        @Override
        public boolean supports(ParameterContext parameterContext, ExtensionContext extensionContext) throws ParameterResolutionException {
            return true;
        }

        @Override
        public Object resolve(ParameterContext parameterContext, ExtensionContext extensionContext) throws ParameterResolutionException {
            return new MyParameter("SecondParameterResolver");
        }

    }

}
```

I expected this output:
```
setUp with FirstParameterResolver
running with FirstParameterResolver
setUp with SecondParameterResolver
running with SecondParameterResolver
```

but got: org.junit.jupiter.api.extension.ParameterResolutionException: No ParameterResolver registered for parameter [mypackage.DummyTest$MyParameter arg0] in executable [public void mypackage.DummyTest.setUp(mypackage.DummyTest$MyParameter)]

I also tried to add a @ExtendWith to my BeforeEach-method, but this results in the same exception.

**Comment by marcphilipp** [comment] 2016-09-26 20:51
Thanks for reporting! Looks like a bug at first sight. We'll look into it and get back to you.

**Comment by sbrannen** [comment] 2016-10-07 15:54
Marked this issue as a _bug_ slated to be addressed in M3 so that we are reminded to look into this in the near future.

**Comment by sbrannen** [comment] 2016-10-07 19:34
FYI: I have confirmed the described _unexpected_ behavior against `master`. So I am inclined to say that this is in fact a _bug_.

**Comment by sbrannen** [comment] 2016-10-07 19:40
> I also tried to add a @ExtendWith to my BeforeEach-method, but this results in the same exception.

That's actually expected since `@ExtendWith` can currently only be declared on classes, interfaces, or `@Test` / `@TestFactory` methods.

**Comment by sbrannen** [comment] 2016-10-07 19:50
_in progress_

**Comment by sbrannen** [comment] 2016-10-07 19:52
I have confirmed that is in fact a **major bug**.

Specifically, `@BeforeEach` and `@AfterEach` methods are invoked with the `ExtensionRegistry` for the test class instead of the `ExtensionRegistry` for the test method.

Consequently, extensions registered at the method level are never invoked for `@BeforeEach` and `@AfterEach` methods.

**Closed** 2016-10-08 16:43 UTC
Labels: bug, extensions, in progress, Jupiter, programming model

**Comment by sbrannen** [comment] 2016-10-08 16:45
This has been fixed in `master`.

@schlauergerd, I ran your `DummyTest` against `master` and verified your expected output. Thus, you should be able to confirm this in the next available snapshot.
