### ISSUE TITLE
Support object field access for ParameterizedTest's name

### ISSUE THREAD

**Issue by Phlegethonyarre** [junit-team/junit5#2572] opened 2021-03-17 14:52 UTC
@ParameterizedTest(name = "...") provides feature to get it's argument value into it's name by using '{0}'.

The common use is that i want to use an Object within an argument (for example User).
In this case i have to go with providing another string argument into test source, that looks like
@ParameterizedTest(name = "I am testing user with name {0}")
void testUser(String userName, User user) {
...
}

But what people need is provide only User argument and access needed field through name (user.getName() or user.name):
@ParameterizedTest(name = "I am testing user with name user.name")
void testUser(User user) {
...
}

Please allow us to do this <3

**Comment by sbrannen** [comment] 2021-03-17 15:38
Closing as a duplicate of #1154.

**Closed by sbrannen** 2021-03-17 15:38 UTC
