### ISSUE TITLE
Long test execution time (gradle)

### ISSUE THREAD

**Issue by nyakto** [junit-team/junit5#1194] opened 2017-12-02 05:40 UTC
I'm experiencing slow builds on pretty simple test configuration

[configuration, test & log](https://gist.github.com/nyakto/b18f7cb0a8fa2a393394e95d3f8edd23)

Test execution takes pretty stable 5-6 seconds (never lower than 5 seconds, looks like threshold), though it makes nothing
But overall build taken even longer (for another 5 seconds!)
It's total 10-11 seconds for do-nothing test

I've played with configuration a bit and found, that removing ```logManager``` from configuration reduces build time for 5 seconds (test execution time unaffected)

**Comment by sormuras** [comment] 2017-12-02 06:04
Hi @nyakto -- our "do-nothing" [vanilla test](https://github.com/junit-team/junit5-samples/tree/master/junit5-vanilla-gradle) with a [minimal Gradle setup](https://github.com/junit-team/junit5-samples/blob/master/junit5-vanilla-gradle/build.gradle) takes [105 ms](https://travis-ci.org/junit-team/junit5-samples/jobs/309966502#L477) for test plan execution.

There is some other component that adds the constant(?) amount of time to your build process. Some general JRE configuration that slows down startup time when a JVM launches?

**Comment by nyakto** [comment] 2017-12-02 06:08
It sure looks like constant amount of time

```
# java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

Nothing special

**Comment by nyakto** [comment] 2017-12-02 06:14
My digging shows that long-running task in build process is executing command for ConsoleLauncher (you can find it in provided log)
And ```logManager``` affection on build time is VERY suspicious
Maybe you can provide some hints for tracing the problem?

**Comment by sormuras** [comment] 2017-12-02 06:47
The reported test plan execution time is measured here: https://github.com/junit-team/junit5/blob/6e50d4379ff4bbc5e7f8a93e218424b1c4b74b95/junit-platform-console/src/main/java/org/junit/platform/console/tasks/ConsoleTestExecutor.java#L62-L67

It includes the time needed for discovery and execution of tests. The discovery process parses the entire class-path [1] for tests using this (default) `^.*Tests?$` regex pattern for candidates. Maybe that can be speed up by adding your "base" package to the front of pattern: `ru.realtymag` using [`includeClassNamePattern`](http://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle-filters) in your Gradle configuration.

> And logManager affection on build time is VERY suspicious

I have no idea what the cause for this may be.

[1]  class-path from your gist
```
-cp /Users/nyakto/IdeaProjects/realtymag-services/feed-loader/build/classes/java/test
/Users/nyakto/IdeaProjects/realtymag-services/feed-loader/build/classes/kotlin/test
/Users/nyakto/IdeaProjects/realtymag-services/feed-loader/build/resources/test
/Users/nyakto/IdeaProjects/realtymag-services/feed-loader/build/classes/java/main
/Users/nyakto/IdeaProjects/realtymag-services/feed-loader/build/classes/kotlin/main
/Users/nyakto/IdeaProjects/realtymag-services/feed-loader/build/resources/main
/Users/nyakto/IdeaProjects/realtymag-services/utils/build/libs/utils.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jre8/1.1.60/9690932bceff9116dba0094dece6d24ba9e52596/kotlin-stdlib-jre8-1.1.60.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-lang3/3.7/557edd918fd41f9260963583ebf5a61a43a6b423/commons-lang3-3.7.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.jdbi/jdbi3-guava/3.0.0/19be4fb560ec98e761ebfdf3838beb46b92ebaa5/jdbi3-guava-3.0.0.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/23.4-jre/dfed5a4d90eb13e47b62ccf735cdce87c9c4e522/guava-23.4-jre.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.5.3/d1577ae15f01ef5438c5afc62162457c00a34713/httpclient-4.5.3.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/mysql/mysql-connector-java/6.0.6/1d19b184dbc596008cc71c83596f051c3ec4097f/mysql-connector-java-6.0.6.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/com.zaxxer/HikariCP/2.7.4/c101cbc2d07c0adffa0857e742229ef785892699/HikariCP-2.7.4.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.jdbi/jdbi3-kotlin-sqlobject/3.0.0/4fc04fa8d0a07bb3be86bd4ecbb9cfc3309601b0/jdbi3-kotlin-sqlobject-3.0.0.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.jdbi/jdbi3-sqlobject/3.0.0/3ac27e76f93cac1afaf029b146bcd928ff6bd427/jdbi3-sqlobject-3.0.0.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.jdbi/jdbi3-kotlin/3.0.0/65fbcde0d9263b206baa5db1d45184fee57bdf6/jdbi3-kotlin-3.0.0.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.jdbi/jdbi3-core/3.0.0/52a14139d2c3a324c86f6d0527a3eddf3f50853f/jdbi3-core-3.0.0.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-params/5.0.2/ccd504f1897e1f8813513efdf994acd644ad3693/junit-jupiter-params-5.0.2.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-engine/5.0.2/e57de973ac81662ec2b9b225df6c882a641fabe6/junit-jupiter-engine-5.0.2.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.junit.jupiter/junit-jupiter-api/5.0.2/4024737a023e98dc6c9cbbd89fe0dd83975df65/junit-jupiter-api-5.0.2.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-launcher/1.0.2/7cd136827fbfe3e6301b95f0340d654ad54feaa4/junit-platform-launcher-1.0.2.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-core/2.9.0/52f6548ae1688e126c29b5dc400929dc0128615/log4j-core-2.9.0.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-jul/2.9.0/42fcf24286676172f2cf4665a6bdf23e1fbf6bae/log4j-jul-2.9.0.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jre7/1.1.60/51aaa4c2a3dab2054bc1554d29632cc5510bdb4f/kotlin-stdlib-jre7-1.1.60.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.module/jackson-module-kotlin/2.9.2/a9cf72ae68a641ade45c400b6cec2d363818f11b/jackson-module-kotlin-2.9.2.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.1.3/bfc9458443666b1be1d66813f3a90a03afa30730/kotlin-reflect-1.1.3.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.1.60/ac63d0e86e690fe4eded7f1f8998996c28499989/kotlin-stdlib-1.1.60.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.6/815893df5f31da2ece4040fe0a12fd44b577afaf/commons-io-2.6.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.module/jackson-module-parameter-names/2.9.2/be78ca220839b2c53ebd33fd4d580b5a0cacdd5a/jackson-module-parameter-names-2.9.2.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jdk8/2.9.2/9b0b7c623262e29c73e8f6a78f6150372d2066f8/jackson-datatype-jdk8-2.9.2.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.datatype/jackson-datatype-jsr310/2.9.2/e1653d338703d8233cc1ac18c6722510bdaceb4f/jackson-datatype-jsr310-2.9.2.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-databind/2.9.2/1d8d8cb7cf26920ba57fb61fa56da88cc123b21f/jackson-databind-2.9.2.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-core/2.9.2/aed20e50152a2f19adc1995c8d8f307c7efa414d/jackson-core-2.9.2.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/com.fasterxml.jackson.core/jackson-annotations/2.9.2/bb0f1a93c122723906420b7a77b6c4b669da0fc2/jackson-annotations-2.9.2.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/1.3.9/40719ea6961c0cb6afaeb6a921eaa1f6afd4cfdf/jsr305-1.3.9.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_annotations/2.0.18/5f65affce1684999e2f4024983835efc3504012e/error_prone_annotations-2.0.18.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/com.google.j2objc/j2objc-annotations/1.1/ed28ded51a8b1c6b112568def5f4b455e6809019/j2objc-annotations-1.1.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.codehaus.mojo/animal-sniffer-annotations/1.14/775b7e22fb10026eed3f86e8dc556dfafe35f2d5/animal-sniffer-annotations-1.14.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore/4.4.6/e3fd8ced1f52c7574af952e2e6da0df8df08eb82/httpcore-4.4.6.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/commons-logging/commons-logging/1.2/4bfc12adfe4842bf07b657f0369c4cb522955686/commons-logging-1.2.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.9/9ce04e34240f674bc72680f8b843b1457383161a/commons-codec-1.9.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.25/da76ca59f6a57ee3102f8f9bd9cee742973efa8a/slf4j-api-1.7.25.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.antlr/antlr-runtime/3.4/8f011408269a8e42b8548687e137d8eeb56df4b4/antlr-runtime-3.4.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/net.jodah/expiringmap/0.5.6/11833abbdd64050d455187f374dc096944f9ffb0/expiringmap-0.5.6.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-engine/1.0.2/ae5d9b8c44d78da636e4e1e00a907fe0fb7bcb8f/junit-platform-engine-1.0.2.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.opentest4j/opentest4j/1.0.0/6f09c598e9ff64bf0ce2fa7e7de49a99ba83c0b4/opentest4j-1.0.0.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-commons/1.0.2/e348a3a67940694f0718d04f9b0784b3dfb7819b/junit-platform-commons-1.0.2.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-api/2.9.0/e0dcd508dfc4864a2f5a1963d6ffad170d970375/log4j-api-2.9.0.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.antlr/stringtemplate/3.2.1/59ec8083721eae215c6f3caee944c410d2be34de/stringtemplate-3.2.1.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/antlr/antlr/2.7.7/83cd2cd674a217ade95a4bb83a8a14f351f48bd0/antlr-2.7.7.jar
/Users/nyakto/.gradle/caches/modules-2/files-2.1/org.junit.platform/junit-platform-console/1.0.2/2bf2cd18040bfe229bad813c7ab150a0f7ea8153/junit-platform-console-1.0.2.jar
```

**Comment by nyakto** [comment] 2017-12-02 06:59
I've found a problem: it's hostname lookup by logger... and ```XmlReportWriter```
It tries to resolve "iMac-Stanislav.local" into InetAddress
And it happens twice
And constant 5s delay is obviously a timeout

**Comment by marcphilipp** [comment] 2017-12-02 13:01
From where in `XmlReportWriter` is the hostnname lookup triggered?

**Comment by sbrannen** [comment] 2017-12-02 17:21
@marcphilipp, that happens in `XmlReportWriter.writeSuiteAttributes(TestIdentifier, List<TestIdentifier>, NumberFormat, XMLStreamWriter)`:

```java
	private void writeSuiteAttributes(TestIdentifier testIdentifier, List<TestIdentifier> tests,
			NumberFormat numberFormat, XMLStreamWriter writer) throws XMLStreamException {

		writer.writeAttribute("name", testIdentifier.getDisplayName());
		writeTestCounts(tests, writer);
		writer.writeAttribute("time", getTime(testIdentifier, numberFormat));
		writer.writeAttribute("hostname", getHostname().orElse("<unknown host>"));
		writer.writeAttribute("timestamp", ISO_LOCAL_DATE_TIME.format(getCurrentDateTime()));
	}
```

**Comment by sbrannen** [comment] 2017-12-02 17:23
Slated for 5.1 M2 in order to investigate if we can speed up the hostname lookup.

**Comment by nyakto** [comment] 2017-12-02 18:09
I propose to ignore this issue
It's a platform bug on Mac OS High Sierra, which is easy to fix by modifying ```/etc/hosts```
At best it's worth mentioning somewhere in documentation for those experiencing this problem

**Comment by sormuras** [comment] 2017-12-14 11:24
Thanks for the feedback.

Closing this issue as "external issue".

**Closed by sormuras** 2017-12-14 11:24 UTC
Labels: component: Gradle, component: Platform, status: waiting-for-feedback, theme: reporting, type: enhancement

**Comment by smoyer64** [comment] 2017-12-14 18:29
@sormuras - Do you want to relabel the issue then?

**Comment by sbrannen** [comment] 2017-12-17 15:42
@smoyer64, what _label_ would you suggest?

**Comment by smoyer64** [comment] 2017-12-21 18:23
Well ... you removed the one that caught my eye since a closed issue might be waiting a long time.  The alternative (I guess) would have been to remove ```status: waiting-for-feedback``` and replace it with ``` status: works-as-designed ```.

**Comment by sbrannen** [comment] 2017-12-22 17:07
OK. I've added the "works as designed" label.
