### ISSUE TITLE
TestEngine with ID 'junit-jupiter' failed to discover tests v5.8.2 java 17

### ISSUE THREAD

**Issue by kasdihacene** [junit-team/junit5#2881] opened 2022-04-09 11:47 UTC
## Steps to reproduce

Upgrading the junit-jupiter-api and junit-jupiter-engine from 5.7.0 to 5.8.2 under JDK 17

## Context
I have faced an issue when upgrading my Jupiter version from 5.7.0 to 5.8.2 on Java 17 project with these errors : 

```
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:111)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:85)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:92)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: org.junit.platform.commons.JUnitException: ClassSelector [className = 'com.azure.monitoring.application.service.PostServiceTest'] resolution failed
	at org.junit.platform.launcher.listeners.discovery.AbortOnFailureLauncherDiscoveryListener.selectorProcessed(AbortOnFailureLauncherDiscoveryListener.java:39)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:102)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:46)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:69)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:103)
	... 9 more
Caused by: java.lang.NoSuchMethodError: 'java.util.Optional org.junit.platform.commons.util.AnnotationUtils.findAnnotation(java.lang.Class, java.lang.Class, boolean)'
	at org.junit.jupiter.engine.descriptor.DisplayNameUtils.getDisplayNameGenerator(DisplayNameUtils.java:110)
	at org.junit.jupiter.engine.descriptor.DisplayNameUtils.lambda$createDisplayNameSupplierForClass$2(DisplayNameUtils.java:98)
	at org.junit.jupiter.engine.descriptor.DisplayNameUtils.determineDisplayName(DisplayNameUtils.java:88)
	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.<init>(JupiterTestDescriptor.java:69)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.<init>(ClassBasedTestDescriptor.java:96)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.<init>(ClassTestDescriptor.java:51)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.newClassTestDescriptor(ClassSelectorResolver.java:119)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.lambda$resolve$0(ClassSelectorResolver.java:71)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.createAndAdd(EngineDiscoveryRequestResolution.java:246)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution$DefaultContext.addToParent(EngineDiscoveryRequestResolution.java:209)
	at org.junit.jupiter.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:71)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:134)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)
	... 14 more
```

 - Used versions (Jupiter): 5.8.2
 - Build Tool/IDE: Intellij

## Deliverables

- [ ] ...

**Comment by marcphilipp** [comment] 2022-04-09 12:00
[`AnnotationUtils.findAnnotation(java.lang.Class, java.lang.Class, boolean)`](https://junit.org/junit5/docs/current/api/org.junit.platform.commons/org/junit/platform/commons/util/AnnotationUtils.html#findAnnotation(java.lang.Class,java.lang.Class,boolean)) was added in 1.8 so you're probably using a pre-1.8 version of `junit-platform-commons`.

Generally, if you update Jupiter to 5.8.2, you also need to update all JUnit Platform artifacts to 1.8.x.

If you're using a build tool like Maven or Gradle you can use the junit-bom to align those versions.

I'm optimistically closing this issue but please let us know if this resolved the problem for you.

**Closed by marcphilipp** 2022-04-09 12:00 UTC
Labels: status: invalid, 3rd-party: IntelliJ IDEA

**Comment by kasdihacene** [comment] 2022-04-09 12:33
The issue is solved after upgrading the version of spring boot from 2.4.x to 2.6.x 
Thank you so much @marcphilipp

**Comment by leandroboeing-zebra** [comment] 2023-09-20 21:45
I can confirm this is happening again with the combination of spring in version `3.1.2` and junit-engine in `5.10.0`.

**Comment by hegazy2017** [comment] 2023-09-24 12:51
This is my gradle 
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.8.2'
    testImplementation 'org.junit.platform:junit-platform-launcher:1.8.2'

and When run tests and error 
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:134)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:80)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:78)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.discover(DefaultLauncherSession.java:81)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.discover(SessionPerRequestLauncher.java:46)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.<init>(JUnit5TestReference.java:46)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createUnfilteredTest(JUnit5TestLoader.java:88)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.createTest(JUnit5TestLoader.java:69)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestLoader.loadTests(JUnit5TestLoader.java:56)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:513)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.NoClassDefFoundError: org/junit/jupiter/api/io/CleanupMode
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:66)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
	... 15 more
Caused by: java.lang.ClassNotFoundException: org.junit.jupiter.api.io.CleanupMode
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 17 more

using spring version '3.1.4'    java : 19

**Comment by hegazy2017** [comment] 2023-09-24 12:51
can any one give me the solution

**Comment by sbrannen** [comment] 2023-09-25 11:35
@leandroboeing-zebra and @hegazy2017, please see the User Guide for details on how to properly upgrade JUnit versions when using Spring Boot.

https://junit.org/junit5/docs/current/user-guide/#running-tests-build-spring-boot

**Comment by sandrooco** [comment] 2023-12-05 08:40
For those who have this issue too using Spring Boot: you can probably just remove the explicit junit dependencies in your pom.xml because Spring Boot (at least 3.2.0+) can handle junit versions properly.

**Comment by sbrannen** [comment] 2024-01-05 10:12
@landoephan, please see https://github.com/junit-team/junit5/issues/2881#issuecomment-1733489729.

If you have further issues with dependency management and `spring-batch-test`, please raise an issue on the Spring Batch issue tracker.

Thanks

**Comment by erikvasilyan** [comment] 2024-07-24 10:33
I got this error because my test file tests were commented so there was a empty test file, solved by just deleting that file

**Comment by keanerickson-mc** [comment] 2024-08-14 22:02
Non-spring user here. I encountered this issue when updating to JUnit 5.11, with NoSuchMethodError "returnsPrimitiveVoid". 
The fix was thus: it turns out I was using the "org.mockito mockito-junit-jupiter" package which was included "org.junit.jupiter junit-jupiter-api". However this included -api package was  still pointing to 5.10.x. So I excluded junit-jupiter-api from mockito-junit-jupiter and added it myself using 5.11. Problem solved

**Comment by marcphilipp** [comment] 2024-08-15 08:33
@keanerickson-mc That's probably because in your POM, you've declared `mockito-junit-jupiter` before `junit-jupiter-api` and Maven picks the first version. Rather than excluding the dependency, our recommended solution is to use the `junit-bom` to [align the versions](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven-bom) of JUnit artifacts.

**Comment by coinzz** [comment] 2024-08-23 11:57
> [`AnnotationUtils.findAnnotation(java.lang.Class, java.lang.Class, boolean)`](https://junit.org/junit5/docs/current/api/org.junit.platform.commons/org/junit/platform/commons/util/AnnotationUtils.html#findAnnotation(java.lang.Class,java.lang.Class,boolean)) was added in 1.8 so you're probably using a pre-1.8 version of `junit-platform-commons`.
> 
> Generally, if you update Jupiter to 5.8.2, you also need to update all JUnit Platform artifacts to 1.8.x.
> 
> If you're using a build tool like Maven or Gradle you can use the junit-bom to align those versions.
> 
> I'm optimistically closing this issue but please let us know if this resolved the problem for you.

Thanks that fixed it for me for a newer version as well. Didn't know there exist a dependency. Isn't it possible that these packages already use the required version of `junit-platform-commons`.

**Comment by marcphilipp** [comment] 2024-09-01 09:51
Maven just picks the first version it sees in the dependency tree for transitive dependencies if you're not importing the BOM. :shrug:

**Comment by Rockio-sy** [comment] 2024-11-18 19:18
I faced this error with version 5.11.3 of (junit-jupiter-api, junit-jupiter-engine) and 5.11.1 junit-platform-launcher
do mvn -X clean instlall to check the program can be compiled 
in my case i couldn't cus there is no specific method to run so that  i get  "java.lang.NoSuchMethodErro"
Just add the dependencies of jupiter to run the methods 
by adding 
`        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-runner</artifactId>
            <version>1.11.3</version> 
            <scope>test</scope>
        </dependency>
`
