### ISSUE TITLE
Support methods from external classes in @MethodSource

### ISSUE THREAD

**Issue by karollewandowski** [junit-team/junit5#1088] opened 2017-09-30 18:12 UTC
## Overview

Currently only methods from the same class as test can be referenced. It limits possibility of reusing code, eg. if multiple tests from multiple classes need "blank strings" then there is no simple way of defining it once and using in all tests.

There are 2 ideas for allowing to reference external class methods.

1. Allow to provide Fully Qualified Method Name (FQMN) in `@MethodSource` annotation, like:
```java
@ParameterizedTest
@MethodSource("com.example.test.StringDataFactory#blankStrings()")
void testSomething(String blankString) {
    // ...
}
```

2. Extend`@MethodSource` annotation with additional attribute declaring class containing referenced method source, eg. `location`:
```java
@ParameterizedTest
@MethodSource(value = "blankStrings", location = StringDataFactory.class)
void testSomething(String blankString) {
    // ...
}
```

I think that second option is better choice as it is more type safe and easier to write. Probably IDE like IntelliJ IDEA will support FQMN references in strings, but I doubt other IDE like Eclipse or NetBeans will get such feature as well (to be honest I have no idea how advanced are those IDEs these days).

I wouldn't recommend implementing both options. IMHO two ways of achieving the same goal is not the best idea. Developers in teams would have different preferences and argue about which way should be used in project. Also having two ways of doing the same doesn't provide any additional value here (or at least I don't see it).

**Comment by sbrannen** [comment] 2017-09-30 20:04
Thanks for creating the issue!

Added to the 5.1 backlog for the time being and open to "team discussion" for which approach to implement.

**Comment by karollewandowski** [comment] 2017-10-09 09:46
I'd like to volunteer to implement this one when decision will be made.

**Comment by mkobit** [comment] 2017-10-16 16:54
The current `@MethodSource` is not `@Repeatable` (possibly by design?) so option 2 might need to factor in method sources from different classes.

**Comment by islandsvinur** [comment] 2017-11-14 12:30
When addressing this issue, please also take into account that parameterized tests inside `@Nested` classes cannot at the moment use a `@MethodSource`.

In the following example, from `theTest` the `outerMethodSource` cannot be referred to. The `innerMethodSource` cannot exist because it must be static for `@MethodSource`, but it can't live inside the non-static class `NestedTests`.

```java
class Tests {
    @Nested
    class NestedTests {
        @ParameterizedTest
        @MethodSource("???")
        void theTest(String string) { ... }

        static Stream<String> innerMethodSource() { ... }
    }

    static Stream<String> outerMethodSource() { ... }
}
```

**Comment by sbrannen** [comment] 2017-11-14 13:54
@islandsvinur, actually... you can declare a non-static method source if the `@Nested` test class is annotated with `@TestInstance(PER_CLASS)`. 😉

**Comment by sbrannen** [comment] 2017-11-14 13:56
> The current `@MethodSource` is not `@Repeatable` (possibly by design?)

I _believe_ that's more of a result of a limitation in annotation processing.

> so option 2 might need to factor in method sources from different classes.

Good catch! 👍 

That would in fact require the use of an array of nested annotations in order to support multiple sources.

**Comment by sbrannen** [comment] 2017-11-14 13:57
... which makes me lean more toward option \#1 for the sake of simplicity, even if it's less _type safe_ at compile time.

**Comment by sbrannen** [comment] 2018-03-02 21:29
@junit-team/junit-lambda, I think we should go with the FQMN variant (i.e., option # 1) and pull this into 5.2 M1.

Rationale: AFAICT, the only way to reasonably implement option # 2 would require that `@MethodSource` become a `@Repeatable` annotation. That would in turn require that we support both non-repeatable and repeatable source annotations simultaneously (already experimenting locally)  and might also necessitate removal of the `AnnotationConsumer` API. Note, however, that the latter might actually be a good thing in general in terms of simplifying the published API before we change the `@API` status of parameterized tests. That would require that implementations of `ArgumentsProvider` and `ArgumentConverter` look up their own annotations, but that would would actually give those implementations more power by allowing them to decide if they support repeatable annotations.

Thoughts?

**Comment by sbrannen** [comment] 2018-03-02 21:29
Tentatively slated for 5.2 M1 for _team discussion_.

**Comment by marcphilipp** [comment] 2018-03-16 11:20
Team decision: Implement option # 1.

**Comment by marcphilipp** [comment] 2018-03-16 11:21
@karollewandowski I've just tagged this issue _up-for-grabs_ so feel free to pick it up. 😉

**Comment by dnccfu** [comment] 2018-03-16 16:33
Hello @marcphilipp

I apologize for posting non-issue content related here but i could not find any information about this subject. I have noticed you are marking some issues as up-for-grabs. Does that mean that anyone is free to submit a PR regarding those? 

Also i would like to ask a question about your repo etiquette. Before submitting a PR should one ask the original issue author (in this case karollewandowski) before doing anything in case he wants to implement this?  I am very dedicated to contributing but i would not want to do that while someone else is already working on it.

Thank you in advance and sorry again for the irrelevant post.

**Comment by marcphilipp** [comment] 2018-03-16 17:35
> I apologize for posting non-issue content related here but i could not find any information about this subject.

No worries! There's a short Contributing section in the repo's readme:

> Issues marked with an up-for-grabs label are specifically targeted for community contributions.

> Also i would like to ask a question about your repo etiquette. Before submitting a PR should one ask the original issue author (in this case karollewandowski) before doing anything in case he wants to implement this?

We haven't written it down as a rule but you're right: it has become a common courtesy to do so. In this case, @karollewandowski has already expressed his interest so that's why I asked him. Let's give him a day or so to respond and then see, ok?

**Comment by dnccfu** [comment] 2018-03-16 17:54
Great, thanks! Not in a rush for this particular issue, but you guys are lightning fast with the features and bug fixes (great work btw), so if someone wants the opportunity to work on an existing issue he needs to be a ninja.

Still i have found junit5 much more accessible and interesting to pontentially work on compared to behemoths like Spring where a pull request can take 7 months due to the sheer size. Thanks again for the info

**Comment by karollewandowski** [comment] 2018-03-18 20:47
Sorry I didn't respond yet, I had a week of holidays without computer :-) I will start to work on this one in few days if it's not a problem. If it's more urgent, please let me know.

**Comment by sormuras** [comment] 2018-03-19 08:17
No problem at all, @karollewandowski -- looking forward to your PR.

**Comment by karollewandowski** [comment] 2018-03-19 21:42
One question regarding the FQMN - are parentheses required here? If method from current class is referenced, then parentheses are omitted. Maybe it would be more consistent to use method name without `()` in FQNM as param methods can't take arguments? So:
```java
@MethodSource("com.example.test.StringDataFactory#blankStrings")
```
instead of:
```java
@MethodSource("com.example.test.StringDataFactory#blankStrings()")
```
I guess forgetting about `()` will be common and annoying mistake made by developers.
Another solutions:
- meaningful error message - if FQMN doesn't contain `()`, then give a hint to developer that he forgot to add it
- make parentheses optional - two styles of doing the same introduces inconsistency and potential conflicts between developers about which approach is the correct one and should be used in project

**Comment by sbrannen** [comment] 2018-03-20 15:02
The parentheses are already optional with the existing support for FQMNs. 

Here's the documentation for the supported syntax:

https://junit.org/junit5/docs/current/api/org/junit/platform/engine/discovery/DiscoverySelectors.html#selectMethod-java.lang.String-

So, you don't actually have to do much with regard to the syntax: just emulate what `selectMethod(String)` already does. 😉

**Comment by sbrannen** [comment] 2018-03-20 15:05
And I say "emulate", I don't mean copy-n-paste.

Rather, we might want to extract the common parsing algorithm from `org.junit.platform.engine.discovery.DiscoverySelectors.selectMethod(String)` and move it somewhere like `ReflectionUtils`.

For this particular issue, we just have to keep in mind that such a factory method is actually _not_ allowed to have parameters.

**Comment by karollewandowski** [comment] 2018-03-20 18:23
Thanks @sbrannen, all is clear now.

**Comment by sbrannen** [comment] 2018-03-24 14:44
_in progress_ by @karollewandowski

**Comment by sbrannen** [comment] 2018-04-01 16:31
Closing this issue since #1340 has been merged into `master`.

**Closed by sbrannen** 2018-04-01 16:31 UTC
Labels: component: Jupiter, status: in progress, theme: parameterized tests, theme: programming model, type: enhancement, up-for-grabs
