### ISSUE TITLE
OutOfMemoryError in test suite when upgrading from JUnit 5.2 to 5.3

### ISSUE THREAD

**Issue by tcfurrer** [junit-team/junit5#1578] opened 2018-09-06 18:31 UTC
## Overview

I work on a large project which runs Junit 5 under Gradle (currently version 4.8).  One of our test suites which previously ran fine with a 8 GB max heap size now requires an ~11 GB heap to run without OutOfMemoryError (~12 GB to run without OutOfMemoryError AND without GC overhead slowing things down significantly).

Looking at the release notes, I see nothing that should cause such a significant increase in memory usage from Junit 5 itself, so I was surprised to see this new problem while upgrading versions.

I only found one other open issue mentioning OutOfMemoryError and it involves dynamic tests, which my suite isn't using at all.

I suppose it's possible that some small behavior change in Junit 5.3 sensitizes an issue with my test suite that increases memory consumption, but I can't think of what that might be. 

Are there any changes in Junit 5.3 that are known to increase memory consumption, and thus increase risk of OutOfMemoryError while running tests?

My apologies if this issue seems more like a question and not a real bug report... but I figured it was better to raise the issue quickly after Junit 5.3 release just in case others are going to start hitting the same problem soon.

Unfortunately, I can't share my unit tests from this project.  However, I am going to try to pare down the test suite to see if I can narrow down where the memory increase is happening.  I may or may not be able to come back here later and provide more specific information, after doing that work.

## Deliverables

**Team Decision**:

- [x] Implement the _quick fix_ mentioned by @sbrannen.
- [x] Investigate other possibilities for freeing up unnecessary memory consumption in the `HierarchicalTestEngine` and related infrastructure (specifically in `NodeTestTask`).
- [ ] Backport fix and release notes to a new `5.3.1` branch.

**Comment by sormuras** [comment] 2018-09-06 18:35
Can you tell us the amount of tests executed in that suite?

**Comment by tcfurrer** [comment] 2018-09-06 18:48
It is ~2,750 testcases, across about 200 test classes.  Most are very fast-running, small/lightweight/low memory tests.  Just a handful of them use a lot more memory and run for several seconds.

The suite takes about 3 minutes to run when using gradle to run it across 4 JVM processes in parallel.  So really those numbers are sort of divided by 4 in the process that actually hits OutOfMemoryError.  (In my upcoming experiment to pare down the list to try to narrow down the problem, I'll be turning off parallel runs to help unmuddy the waters.)

I should also have mentioned that we are running everything using Java 8.  And I reproduced the same issue on both Linux and Windows.

**Comment by tcfurrer** [comment] 2018-09-06 18:58
Also notable: we have 20 subprojects, each with 1000's of tests, and only two of our subprojects hit this issue.  The info I already provided was all from just one of those problematic subprojects, which I selected to work with to try to root cause the issue (because it is the fastest-running).

**Comment by nicolaiparlog** [comment] 2018-09-06 18:59
If paring down does not reveal the source (it may just be higher overall memory consumption of JUnit 5 due to some implementation detail), it may be helpful to run the suite with 5.2 and 5.3 and create a heap dump during peak memory consumption. An inspection might show what kind of objects make up the addition GBs. That may end up being a lot of work, though.

**Comment by tcfurrer** [comment] 2018-09-06 19:04
That's a great idea.  I'm experienced with Java heap analysis and memory leak debugging already, so I know how to do that.  I think this experiment is somewhat likely to clarify whether this is really a Junit 5.3 issue, or an issue with our tests.  I'll report back here when I have more clues.

**Comment by tcfurrer** [comment] 2018-09-06 23:38
What I see in my heap dump is that there are tons of test class instances being accumulated in memory.  I think this consistitutes a "memory leak", and becomes especially noticeable when the test classes hold final fields which themselves retain a large amount of heap space.

Using "find nearest GC root" , I see that the test classes are being held in memory by org.junit.jupiter.engine.descriptor.MethodExtensionContext

**Comment by tcfurrer** [comment] 2018-09-07 00:00
Ok here is a minimal test which demonstrates the issue.

When run with a 2GB max heap size, this test passes on Junit 5.2, but hits OutOfMemoryError on Junit 5.3.  And I find that unacceptable... never before has any version of Junit so heavily punished test classes which store large amounts of data.

import org.junit.jupiter.api.Test;

/**
 * Demonstrates the Junit 5.3 memory leak issue discussed at:
 *   https://github.com/junit-team/junit5/issues/1578
 * Intended to be run using a 2 GB max heap size.
 */
class Junit53MemoryLeakDemoTest {
    private final byte[] gigabyte = new byte[1073741824];

    @Test void test1() { }
    @Test void test2() { }
    @Test void test3() { }
}

**Comment by tcfurrer** [comment] 2018-09-07 00:10
By the way, the minimal testcase I provided here might be used as inspiration for a Junit 5 regression test, to guard the requirement that the memory held by a test class should not be multipled by the number of test methods in that class in order to set the max heap size requirement... that's too expensive and will certainly break lots of project's existing tests.

**Comment by tcfurrer** [comment] 2018-09-07 00:16
Looks like this issue was created by the changes to support parallel test execution.  I suspect there may be some passing around of lists where perhaps iterators/streams could be used to avoid holding everything in memory simulatenously?

**Comment by tcfurrer** [comment] 2018-09-07 00:52
Note that I'm not enabling parallel test execution.  I think it's totally reasonable to impose some memory usage increases upon parallel test execution (since of course it cannot be avoided).  But when running with the feature disabled, the mere existence of the feature shouldn't impose major memory usage increases.  Indeed, I think the memory usage implications of parallel test execution will be a significant consideration for users to consider before enabling it... some will choose to stick with something more like gradle's multi-JVM-process parallelism, while others will need Junit 5's version of parallelism.

**Comment by nicolaiparlog** [comment] 2018-09-07 05:14
Great detective work, @tcfurrer! :+1: Just to clarify, do the test class instances you see belong to the currently executed test or are the references retained even though the tests were already executed in the past. Being fastidious, I think only the latter would be a memory leak (or the Java variant thereof) that _must_ be fixed whereas the former _could_ be judged as a valid trade-off. (Although I agree that it's not nice to punish users for a feature that they don't use.)

Quick tip: To format code snippets, start and end them with three backticks on an otherwise empty line. To improve highlighting, you can even mention the language:

    ```java
    System.out.println("Java code snippet)";
    ```

Results in:

```java
System.out.println("Java code snippet)";
```

**Comment by sormuras** [comment] 2018-09-07 06:07
Thanks for the detailed analysis and the minimal show-case.

**Comment by sormuras** [comment] 2018-09-07 06:08
Marked as a "bug" for now, as it is a regression.

**Comment by sbrannen** [comment] 2018-09-07 09:19
@tcfurrer, thank you for reporting the issue, the detailed analysis, and the sample to reproduce the bug.

Much appreciated!

**Comment by sbrannen** [comment] 2018-09-07 09:36
I can confirm that this is a bug thanks to the example provided by @tcfurrer.

And as @sormuras mentioned elsewhere, switching to test instance per-class lifecycle avoids the issue, as expected.

**Comment by sbrannen** [comment] 2018-09-07 09:43
> Looks like this issue was created by the changes to support parallel test execution. I suspect there may be some passing around of lists where perhaps iterators/streams could be used to avoid holding everything in memory simulatenously?

Perhaps. 

We'll keep in that mind.

Thanks for brainstorming.

**Comment by sbrannen** [comment] 2018-09-07 10:12
_in progress_

**Comment by sbrannen** [comment] 2018-09-07 12:15
For anyone interested, it turns out that there is a simple _quick fix_ for this issue.

Namely, setting the `context` and `parentContext` fields in `NodeTestTask` after they are no longer in use allows the supplied sample test class to execute without problems.

**Comment by sbrannen** [comment] 2018-09-07 12:18
**Team Decision**:

1. Implement the _quick fix_ mentioned by @sbrannen.
    * This work has already been performed and will be pushed to `master` soon.
2. Investigate other possibilities for freeing up memory consumption in the `HierarchicalTestEngine` and related infrastructure (specifically in `NodeTestTask`).

**Comment by sbrannen** [comment] 2018-09-07 12:55
**Update**:

The _quick fix_ has been pushed to `master` in 05b4bc29dc6984e0c11954aa25520ded3a4e95a5.

Note, however, that the fix and release notes will need to be backported to the `5.3.1` branch once we've created it.

**Comment by tcfurrer** [comment] 2018-09-07 16:28
Thanks everyone for the quick work here. I'm looking forward to `5.3.1`!

**Comment by marcphilipp** [comment] 2018-09-07 19:15
Reopening because the last deliverable has not been addressed.

**Comment by sbrannen** [comment] 2018-09-09 13:45
Backported to the `5.3.x` release branch: https://github.com/junit-team/junit5/commits/releases/5.3.x

**Closed by sbrannen** 2018-09-09 13:45 UTC
Labels: component: Jupiter, component: Platform, theme: execution, type: bug
