### ISSUE TITLE
junit-jupiter:5.4.0-M1 does not provide 5.4.0-M1 dependencies

### ISSUE THREAD

**Issue by octopus-prime** [junit-team/junit5#1711] opened 2018-12-26 12:40 UTC
Using
`testImplementation("org.junit.jupiter:junit-jupiter:5.4.0-M1")`
does not provide 5.4.0-M1 dependencies
![image](https://user-images.githubusercontent.com/7620013/50446139-97f5ae80-0913-11e9-9f49-8a973e059def.png)

**Comment by sbrannen** [comment] 2018-12-26 13:41
What version of Gradle are you using?

**Comment by marcphilipp** [comment] 2018-12-26 14:50
I'be changed our samples to use the aggregator dependency in https://github.com/junit-team/junit5-samples/commit/a5604a7aeba443a27b04b1f96bfa83dc7436503a. It works in the build and in IDEA.

@octopus-prime Could you please provide a reproducible sample project?

**Comment by octopus-prime** [comment] 2018-12-26 15:10
Just created a project with spring initializr.
Added dependency `testImplementation("org.junit.jupiter:junit-jupiter:5.4.0-M1")`.
Still wrong library versions.

![image](https://user-images.githubusercontent.com/7620013/50449593-a5696380-0928-11e9-81aa-003821227147.png)

[jupiter.zip](https://github.com/junit-team/junit5/files/2710428/jupiter.zip)

**Comment by sbrannen** [comment] 2018-12-26 15:11
Ahhh... that's likely because Spring Boot is pulling in the JUnit BOM hardcoded to 5.3.2.

You'll need to override the versions used by Spring Boot.

If you can't figure out how to do that, let us know. 😉 

In the interim, I'm closing this issue.

**Closed by sbrannen** 2018-12-26 15:11 UTC
Labels: 3rd-party: Gradle, component: Jupiter, status: waiting-for-feedback, theme: build

**Comment by sbrannen** [comment] 2018-12-26 15:13
If you need some inspiration for how to override the JUnit versions used by Spring Boot, see if the following helps...

https://github.com/sbrannen/spring-events/blob/master/build.gradle#L38

**Comment by octopus-prime** [comment] 2018-12-26 15:15
Thanks for help. Removing spring stuff leads to correct versions:

![image](https://user-images.githubusercontent.com/7620013/50449729-5f60cf80-0929-11e9-8f57-7fd15fbeb436.png)

I will try overriding the junit-verion.

**Comment by sbrannen** [comment] 2018-12-26 15:17
Glad to hear it.

Happy Testing... and please do let us know if you run into any issues with new features in JUnit 5.4 M1!
