### ISSUE TITLE
@ParameterizedTest display custom names for arguments

### ISSUE THREAD

**Issue by SarathBabu** [junit-team/junit5#2452] opened 2020-10-18 03:48 UTC
When using `@ParamerizedTest` annotation, will it be possible to display a string other than what is supplied by toString()?
When we are using some big objects the toString value is very large and displays lots of informations which are not relevant

It would be helpful if we can give provision to
* display some parameter on the argument like `{0.shortName}` or `{0.route.origin}` etc
* Provide another class name which will generate the string to display for each argument

## Deliverables
Provision to customise the name of the arguments in `@ParamerizedTest`

**Comment by sbrannen** [comment] 2020-10-19 08:20
Closing this issue since it is effectively a duplicate of  #1154.

I'll link to this issue from  #1154, since this issue targets parameterized tests explicitly; however, a general purpose solution should be implemented in conjunction with #1154 that is usable with display names for parameterized tests as well.

**Closed by sbrannen** 2020-10-19 08:20 UTC
Labels: component: Jupiter, theme: parameterized tests, type: enhancement
