### ISSUE TITLE
Introduce @YamlFileSource similar to @CsvFileSource

### ISSUE THREAD

**Issue by RunningSanil** [junit-team/junit5#1996] opened 2019-08-31 08:02 UTC
`@CsvFileSource` is useful, but structured data structures are not supported.

I suggest to add a `@YamlFileSource` for explicit YAML support like `@CsvFileSource` to support structured data structures.

I have created a little demo locally, but it may not be complete. I want to know what everyone thinks.

**Comment by sbrannen** [comment] 2019-09-01 13:54
This is related to #1571.

**Comment by sbrannen** [comment] 2019-09-01 13:55
I'm inclined to label this as a duplicate of #1794.

@junit-team/junit-lambda Thoughts?

**Comment by sbrannen** [comment] 2019-09-01 14:28
**Team Decision**: closing as a duplicate of #1794.

**Closed by sbrannen** 2019-09-01 14:28 UTC
Labels: component: Jupiter, theme: parameterized tests, theme: programming model
