### ISSUE TITLE
ExecutionCondition: Test fail if the condition doesn't met, and message doesn't print. Kotlin

### ISSUE THREAD

**Issue by SaherAlSous** [junit-team/junit5#3034] opened 2022-09-15 13:38 UTC
I created context execution condition for my test, and tested the code with several contexts. the test is supposed to run if the condition is `regular` or `low`, and if not the test should be disabled.
The test run correctly when the condition is met. but fails when it doesn't. meanwhile it should be disabled.

## Steps to reproduce

```
class ExecutionContextExtension: ExecutionCondition {

    override fun evaluateExecutionCondition(context: ExtensionContext?): ConditionEvaluationResult {
        val properties = Properties()
        try {
            properties.load(ExecutionContextExtension::class.java.classLoader.getResourceAsStream("context.properties"))
            val executionContext = properties.getProperty("context")

            if (executionContext != "regular" && executionContext != "low")
                return ConditionEvaluationResult.disabled("Test disabled on this context")

        }catch (e: IOException) {
            throw RuntimeException("No Idea!")
        }
        return ConditionEvaluationResult.enabled("Test enabled on this context")
    }
    
}
```
Test file:
```
@DisplayName("Testing Passenger Data Class")
@ExtendWith(ExecutionContextExtension::class)
class PassengerTest {

    @ParameterizedTest
    @CsvSource("123-456-789, John Smith", "987-654-321, Abo AlSous")
    fun `Testing Passenger Data Class`(identifier: String, name: String) {
        val passenger = Passenger(identifier, name)
        assertEquals("Passenger $name with identifier $identifier", passenger.toString())
    }

}
```

## Context

 - Used versions (Jupiter/Vintage/Platform): Jupiter 5.9.0
 - Build Tool/IDE: IntelliJ Gradle.

## Deliverables

- When the Extension send back `ConditionEvaluationResult.disabled("Test disabled on this context")` test should be disabled not failed.
- I can't see the disabled/enabled message in the console also.

**Comment by marcphilipp** [comment] 2022-09-16 10:41
Similarly to printing report entries (see https://github.com/junit-team/junit5/issues/3033#issuecomment-1249208795), printing "disabled" reasons is an IntelliJ feature so it only works when running the test via IntelliJ, not Gradle. I suspect that's the root cause here. Therefore, closing this issue as a duplicate of #3033.

**Comment by marcphilipp** [comment] 2022-09-16 10:42
Duplicate of #3033

**Closed by marcphilipp** 2022-09-16 10:42 UTC
Labels: 3rd-party: Gradle, 3rd-party: IntelliJ IDEA, status: new
