### ISSUE TITLE
Feature Request: Convert underscores to spaces while reporting

### ISSUE THREAD

**Issue by brsanthu** [junit-team/junit5#811] opened 2017-04-27 17:11 UTC
It is great that we have DisplayName that helps us give meaningful names for our tests. But it means, we have to type same things twice. Once in `DisplayName` and another type in method name.

What if the junit reporter, converts the method names, changes the underscores to spaces and report it? This way, we can just name the methods longer and it will be reported in a easy to use way.

For ex.,
```
@Test
void handles_missing_request_body() {
...
}
```
would be reported as
```
<some class>
    handles missing request body
```

Thank you for your review of this request.

**Comment by sormuras** [comment] 2017-04-27 18:42
Duplicate of https://github.com/junit-team/junit5/issues/162

**Closed by sormuras** 2017-04-27 18:42 UTC
