### ISSUE TITLE
Kotlin extension function ArgumentsAccessor.get<T> is unusable, i.e.compiled to private

### ISSUE THREAD

**Issue by juergenzimmermann** [junit-team/junit5#1490] opened 2018-07-08 06:26 UTC
The extension function ArgumentsAccessor.get<T>(...) was introduced in https://github.com/junit-team/junit5/issues/1382. However, I cannot `import org.junit.jupiter.params.aggregator.get` because the extension function is compiled to a _private static_ method:
```
> javap -c -p -cp .\junit-jupiter-params-5.3.0-M1.jar org.junit.jupiter.params.aggregator.ArgumentsAccessorKt
Compiled from "ArgumentsAccessor.kt"
public final class org.junit.jupiter.params.aggregator.ArgumentsAccessorKt {
  private static final <T> T get(org.junit.jupiter.params.aggregator.ArgumentsAccessor, int);
    Code:
       0: aload_0
       1: iload_1
       2: iconst_4
       3: ldc           #26                 // String T
       5: invokestatic  #32                 // Method kotlin/jvm/internal/Intrinsics.reifiedOperationMarker:(ILjava/lang/String;)V
       8: ldc           #4                  // class java/lang/Object
      10: invokeinterface #37,  3           // InterfaceMethod org/junit/jupiter/params/aggregator/ArgumentsAccessor.get:(ILjava/lang/Class;)Ljava/lang/Object;
      15: dup
      16: ldc           #39                 // String this.get(index, T::class.java)
      18: invokestatic  #43                 // Method kotlin/jvm/internal/Intrinsics.checkExpressionValueIsNotNull:(Ljava/lang/Object;Ljava/lang/String;)V
      21: areturn
```

**Comment by marcphilipp** [comment] 2018-07-08 18:06
@juergenzimmermann Thanks for reporting!

`javap` reports the same thing for the `assertThrows` extension function, though:

```
  private static final <T extends java.lang.Throwable> T assertThrows(kotlin.jvm.functions.Function0<kotlin.Unit>);
    Code:
       0: iconst_4
       1: ldc           #177                // String T
       3: invokestatic  #181                // Method kotlin/jvm/internal/Intrinsics.reifiedOperationMarker:(ILjava/lang/String;)V
       6: ldc           #37                 // class java/lang/Throwable
       ...
```

IDEA's decompiler shows this:

<img width="1206" alt="screen shot 2018-07-08 at 19 56 48" src="https://user-images.githubusercontent.com/214207/42422590-1ae64748-82e9-11e8-9843-e1e5ee5b08e2.png">

However, when I try to use it from a sample project, I cannot import it either:

<img width="378" alt="screen shot 2018-07-08 at 20 01 53" src="https://user-images.githubusercontent.com/214207/42422629-cbf3bd5e-82e9-11e8-8ad8-cf6b2cbb890e.png">

However, when trying to do the same thing from a test in a different package directly in `junit-jupiter-params` (by moving the `ArgumentsAccessorKotlinTests` class to a different package), it works.

Being not familiar with Kotlin in detail, my only hunch is that it might be the warning we ignore here after all:
https://github.com/junit-team/junit5/blob/d5290b447d127ffdad2fa06aa78f02b4e2a86f08/junit-jupiter-params/src/main/kotlin/org/junit/jupiter/params/aggregator/ArgumentsAccessor.kt#L23-L25

@JLLeitschuh @wilder Any ideas?

**Comment by wilder** [comment] 2018-07-08 18:47
This happens because ```inline``` functions with ```reified``` type can't be accessed from Java code.

The ```reified``` type is used so we can access the value of ```T``` at runtime without requiring the class type to be passed as argument to the function. 

It would work in Java code if we removed the ```reified``` type and added a Class parameter to the function, but I don't think that would make much sense since it would look exactly as the Java function.

**Comment by wilder** [comment] 2018-07-08 19:44
Hm... If the function isn't accessible even from Kotlin code then I think the problem is not related to ```reified```. 

The ```inline``` is necessary so the ```reified``` can be used. And the ```reified``` is required so we can get the value of the class we called the extension function at.

In the [Pivotal's Project Reactor extension function](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/kotlin/reactor/core/publisher/FluxExtensions.kt#L49) you mentioned they don't use ```reified``` because they don't need to get the value of ```T``` inside that function. [Here is a function they also had to use ```reified``` to get the class type](https://github.com/reactor/reactor-core/blob/f88ea67c7b6caa984a69805df28bab4945a7b616/reactor-core/src/main/kotlin/reactor/core/publisher/MonoExtensions.kt#L82).

**Comment by juergenzimmermann** [comment] 2018-07-09 06:12
`import reactor.core.publisher.cast` works fine:

![grafik](https://user-images.githubusercontent.com/734334/42433408-8a6e179c-834f-11e8-97c6-6cdd64e867b6.png)

**Comment by marcphilipp** [comment] 2018-07-09 06:55
Could you please put together and share a small sample project, e.g. based on the Kotlin sample in junit5-samples, that demonstrates the issue so we‘re all talking about the same thing here?

**Comment by juergenzimmermann** [comment] 2018-07-09 16:02
Here is a reduced testcase. Just invoke `.\gradlew`, since "test" is the default task.
[testcase1490.zip](https://github.com/junit-team/junit5/files/2176987/testcase1490.zip)

**Comment by wilder** [comment] 2018-07-09 19:16
@marcphilipp I run some tests here and figured out that the problem is really what you've mentioned...

The function is being shadowed by [org.junit.jupiter.params.aggregator.get](https://github.com/junit-team/junit5/blob/master/junit-jupiter-params/src/main/java/org/junit/jupiter/params/aggregator/ArgumentsAccessor.java#L55).

I've changed the name of the extension function locally and could access it from another package.

I can make a PR fixing this. Any suggestions for the new function name?

**Comment by juergenzimmermann** [comment] 2018-07-09 19:57
Maybe `getAt(index: Int)` or `from(index: Int)`

**Comment by marcphilipp** [comment] 2018-07-16 10:49
Team Decision: Let's go with `getAs<Type>(Int)`.

@wilder Do you have time to take care of changing it?

**Comment by wilder** [comment] 2018-07-16 23:46
@marcphilipp yes, I do!

**Comment by wilder** [comment] 2018-07-17 00:47
Done.

**Comment by marcphilipp** [comment] 2018-08-14 19:11
Now that we've found the root cause in #1546, we should revisit whether `getAs<Type>(Int)` is actually better than `get<Type>(Int)` which is closer to the Java equivalent of `get(int, Class<Type>)`.

**Comment by sbrannen** [comment] 2018-08-15 08:50
Awesome!

So, can we now close this issue?

**Comment by sbrannen** [comment] 2018-08-15 09:00
Ahhhh, now I see that commit was from the `issues/1490-switch-back-to-get` branch.

I thought you'd already pushed to `master`. 

Methinks you should rename the branch to `issues/1490-get-back-to-basics`. 😝

**Comment by sbrannen** [comment] 2018-08-15 09:01
> Now that we've found the root cause in #1546, we should revisit whether `getAs<Type>(Int)` is actually better than `get<Type>(Int)` which is closer to the Java equivalent of `get(int, Class<Type>)`.

I vote ✅ for `get()`.

**Comment by marcphilipp** [comment] 2018-08-15 14:43
**Team Decision:** Switch back to using `get<Type>(Int)`.

**Comment by marcphilipp** [comment] 2018-08-15 14:43
_in progress_

**Closed** 2018-08-15 14:55 UTC
Labels: component: Jupiter, component: Kotlin, status: in progress, status: team discussion, type: bug

**Comment by wilder** [comment] 2018-08-15 17:34
Nice work @marcphilipp, I'm sorry for not noticing it before!

**Comment by marcphilipp** [comment] 2018-08-15 17:47
Thanks and no worries – that was a tricky one!
