### ISSUE TITLE
Add a way for TestInstanceFactory implementations to use any existing ParameterResolver extensions

### ISSUE THREAD

**Issue by dweiss** [junit-team/junit5#2732] opened 2021-09-29 08:43 UTC
It would be great if the API provided a way for custom test instance factories to leverage the existing infrastructure for processing constructor parameters (what ExecutableInvoker does, internally). Otherwise you're forced to recreate the same functionality so that parameter resolvers work, for example. In fact, I'm not even sure it'd be possible to recreate it in an identical way (because the extension registry is not available)?

**Comment by sbrannen** [comment] 2021-09-29 08:47
Hi @dweiss,

Thanks for raising the issue.

We agree: that should be possible: https://github.com/junit-team/junit5/issues/2393#issuecomment-765349501

So I'm closing this as a duplicate of #2393.

**Closed by sbrannen** 2021-09-29 08:47 UTC
Labels: status: new

**Comment by dweiss** [comment] 2021-09-29 08:55
Ah, sorry - I scanned the existing issues but didn't find this one!
