### ISSUE TITLE
Global namespace is reset when running via maven surefire

### ISSUE THREAD

**Issue by stickfigure** [junit-team/junit5#1215] opened 2017-12-21 22:26 UTC
I am using the `Namespace.GLOBAL` namespace to avoid recreating an expensive resource in the `BeforeAllCallback` of an extension. This works great when running tests via IDEA's junit test runner.

When running the tests via `maven test`, the global namespace appears to be reset for every test class. My "if resource is already created, do nothing" code is always creating the resource.

This is using Jupiter 5.0.2, Platform 1.0.2, and Surefire 2.19.1.

Here's the (very simple) extension. You see "Creating new LocalDatastoreHelper" logged many times instead of once: https://github.com/objectify/objectify/blob/v6/src/test/java/com/googlecode/objectify/test/util/LocalDatastoreExtension.java

If I had to take a wild guess, the surefire plugin is forking for every test class? If this is something that can be fixed as a parameter to surefire, can we put instructions in the Junit5 maven chapter?

**Comment by sbrannen** [comment] 2017-12-22 16:59
What happens if you properly use `getOrComputeIfAbsent()` instead of hand crafting your own non-threadsafe version with `get()` and `put()`?

**Comment by stickfigure** [comment] 2017-12-22 17:23
It makes no difference - exact same behavior.

**Comment by sbrannen** [comment] 2017-12-22 17:25
OK. Thanks for checking!

But... I'd still recommend you stick with `getOrComputeIfAbsent()`. 😉

**Comment by sbrannen** [comment] 2017-12-22 17:25
Tentatively slated for 5.1 M2 for investigation

**Comment by sbrannen** [comment] 2017-12-24 15:46
> This was already fixed by #1113 in 5.1 M1.

@marcphilipp, shouldn't we then label #1113 as a _bug_ and backport it to 5.0.x?

**Comment by marcphilipp** [comment] 2017-12-28 09:45
We could backport it, but I'm not sure it's important enough to warrant a 5.0.3 release on its own.

@junit-team/junit-lambda Thoughts?

**Comment by sbrannen** [comment] 2017-12-29 16:16
IMHO, it depends on how soon we release 5.1... which I think we should discuss during our next team call.

**Comment by marcphilipp** [comment] 2018-01-08 19:01
I've verified that the resource is only created once for the provided example project. Thus, this issue as a duplicate of #1113.

We still have to decide whether to backport #1113 and release a 5.0.3.

**Comment by marcphilipp** [comment] 2018-01-12 13:37
Team Decision: We will ship a 5.0.3 bugfix release and include #1113. Closing this issue as a duplicate.

**Closed by marcphilipp** 2018-01-12 13:37 UTC
Labels: component: Jupiter, component: Surefire, status: duplicate, status: team discussion
