### ISSUE TITLE
Is the JUnit 4 Timeout rule supported with the Vintage engine?

### ISSUE THREAD

**Issue by Vazzilena** [junit-team/junit5#2280] opened 2020-04-30 07:10 UTC
Hey,

Is junit4 timeout rule supported with the vintage engine? 

We are experiencing an issue similar to https://github.com/junit-team/junit5/issues/1742 when we started migrating to junit5 runners and switched to junit-platform-console-standalone-1.6.0-RC1.jar. 

My impression is that old junit4 tests will be working out of the box with the junit vintage engine. 

What we observe:

JUnit4's FailOnTimeout rule would create a separate thread group and thread to run the test in (including any other rule's before()/after()) : https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java

JUnit5 does it differently, and it would try to run rule's after() statements on its own (in its own main thread). This results in rule's before() and after() statements run in separate threads and run in parallel which must not happen and eventually causes `IllegalThreadStateException `in our tests.

Is there a way to workaround this without having to migrate all the tests to junit5?

**Comment by Vazzilena** [comment] 2020-04-30 07:26
[JUnit5_vintage_engine_threaddump.txt](https://github.com/junit-team/junit5/files/4556731/JUnit5_vintage_engine_threaddump.txt)

**Comment by sbrannen** [comment] 2020-04-30 10:33
Can you please provide us a minimal example project demonstrating the behavior you are describing?

**Comment by Vazzilena** [comment] 2020-05-02 11:36
> Can you please provide us a minimal example project demonstrating the behavior you are describing?

Well, we figured the problem is probably caused by a fix in junit4 itself:
https://github.com/junit-team/junit4/commit/63fd27710ee2bab6fdf00965f41ef12b79120c70#diff-b88578d0a5d0fccd1c83761372cd8cc3

Since we are originally using junit 4.12 and the platform console runner bundles internally junit 4.13 we ended up with this problem as the console runner is loaded first on our classpath. We will have to adapt our code anyway...

**Comment by marcphilipp** [comment] 2020-05-03 09:54
@Vazzilena Thanks for the feedback! I'm thus closing this issue for now since it's root cause is in JUnit 4 and not the Vintage engine. Please report an issue in the junit4 repo in case you think there's a bug.

**Closed by marcphilipp** 2020-05-03 09:54 UTC
Labels: component: Vintage

**Comment by Vazzilena** [comment] 2020-05-04 13:02
Guys,
Just  just a question - is there a console launcher that bundles junit 4.12 instead 4.13?
We are running into far to many issues to fix them at once…

**Comment by marcphilipp** [comment] 2020-05-04 14:16
@Vazzilena Can you rollback to 5.5.2?

**Comment by Vazzilena** [comment] 2020-05-05 20:20
> @Vazzilena Can you rollback to 5.5.2?

I did and it helped. Thanks.
