### ISSUE TITLE
AsciiDoctor task does not support Rouge on MS Windows

### ISSUE THREAD

**Issue by Andrei94** [junit-team/junit5#799] opened 2017-04-20 19:40 UTC
## Overview

When running the `asciidoctor` task on Windows, Gradle gives the following error: 

> (RuntimeError) asciidoctor: FAILED: required gem 'rouge' is not installed. Processing aborted.
:documentation:asciidoctor FAILED

The ruby, jruby and ruby-devkit are installed.
This problem doesn't appear on Linux and Mac systems.

## Related Issues

- #652 
- #770 
- #777 
- https://github.com/asciidoctor/asciidoctor/issues/1040

**Comment by sbrannen** [comment] 2017-04-20 20:04
There is unfortunately a known issue with using Rouge on Windows.

See https://github.com/asciidoctor/asciidoctor/issues/1040 for details.

In any case, thanks for raising the issue.

In the interim, you might try running the Gradle build in a Bash shell on Windows (e.g., Cygwin, or Windows Subsystem for Linux (WSL)).

**Comment by sbrannen** [comment] 2017-04-20 20:05
FYI: Added _Related Issues_ section.

**Comment by sbrannen** [comment] 2017-04-20 20:06
Currently slated for 5.0 M5, in case there is any action we can take.

**Comment by jbduncan** [comment] 2017-04-20 20:19
@sbrannen When I personally tried `asciidoctor` on Cygwin, it gave me the same error. So I think the error is so Windows-centric that a UNIX layer does little if anything to resolve the problem.

**Comment by Andrei94** [comment] 2017-04-20 20:23
@sbrannen The problem with the gem also appears with the [spring repository](https://github.com/spring-projects/spring-framework). I had to make a local hack there as well. 😄
For JUnit, a temporary solution is to leave only 

> html5 

from 

> backends 'html5', 'pdf' // , 'epub3' 

in `documentation.gradle`.

**Comment by Andrei94** [comment] 2017-04-20 20:26
Good touch 😉

**Comment by sbrannen** [comment] 2017-04-20 20:28
> Good touch 😉

Huh?

**Comment by sbrannen** [comment] 2017-04-20 20:29
Glad you figured out the workaround, since I was just about to suggest that as a fallback option.

**Comment by Andrei94** [comment] 2017-04-20 20:30
> Huh?

I was also thinking of referencing the issue.

**Comment by sbrannen** [comment] 2017-04-20 20:42
Ah, OK. I didn't make the connection to the "sbrannen referenced this issue..." link, since my brain ignores those entries. 😉

**Comment by sbrannen** [comment] 2017-04-22 16:11
@mojavelinux figured out the cause and reported the underlying bug here: https://github.com/jneen/rouge/issues/661

**Comment by sbrannen** [comment] 2017-04-22 16:16
Due to the bug in Rouge that prevents its usage on MS Windows, I am going to revert back to coderay for both the HTML and PDF versions of the User Guide for the time being.

Consequently, I am closing this issue.

**Comment by sbrannen** [comment] 2017-04-22 16:17
See #770 and #777 for further details.

**Closed by sbrannen** 2017-04-22 16:16 UTC
Labels: bug, build, documentation
