### ISSUE TITLE
warning: unknown enum constant Status.STABLE while compiling org.junit.jupiter.api.Test using Java9 

### ISSUE THREAD

**Issue by namannigam** [junit-team/junit5#1104] opened 2017-10-12 05:13 UTC
## Overview

**Bug report.** Using the `junit-jupiter-api-5.0.0` with java version `"9" (build 9+181)` in IntelliJ `2017.2.5`(if that might matter)

Steps to reproduce:-
1. Add a JDK9 based module to the project.
2. Add JUnit5 to the classpath using IntelliJ's shortcut. (lib folder) [`junit-jupiter-api-5.0.0.jar`]
3. Note that it brings along the `opentest4j-1.0.0.jar` along with to the lib/ folder.
4. Compile the [sample project](https://github.com/namannigam/Jigsaw/tree/master/junit5jdk9trial/src) (shared just to draw a picture of the directory structure in use) using the command 
`javac --module-path lib -d "target" $(find src -name "*.java")`

Results into warnings post the compilation of the classes as - 
> warning: unknown enum constant Status.STABLE
>   reason: class file for org.apiguardian.api.API$Status not found
> warning: unknown enum constant Status.STABLE
> 2 warnings

## Deliverables

- [x] Ensure that such warnings are not displayed out of the box.

On a side note, it would be good to know what exactly is causing these warnings to occur. Since, if I comment out the code using JUnit and execute the same command, things seems to be working fine.

**Comment by sormuras** [comment] 2017-10-12 05:31
Include module `org.apiguardian.api` from https://github.com/apiguardian-team/apiguardian into your `lib` folder.

See Gradle example here: https://github.com/junit-team/junit5-samples/blob/master/junit5-java9-engine/build.gradle#L9

**Comment by namannigam** [comment] 2017-10-12 05:45
@sormuras thanks for the prompt reply.
1. The link shared is Gradle. I am unable to find such an option for plain java project on IntelliJ(IJ). Is this a transitive dependency of `junit-jupiter-api`? Shouldn't IJ add that to the classpath as well?
2. Manually added the jar to the lib folder and the warning are no more there. But could you share any relevant link or provide some information about what was the error about and why did it turn up?

**Comment by sormuras** [comment] 2017-10-12 08:58
See https://youtrack.jetbrains.com/issue/IDEA-178888 for details.

**Comment by sbrannen** [comment] 2017-10-12 14:36
Closing this issue as _invalid_.

**Closed by sbrannen** 2017-10-12 14:36 UTC

**Comment by franklinyu** [comment] 2018-01-05 19:41
I still got this warning. Tried 5.0.2 and 5.1.0-M1. Any ideas?

**Comment by marcphilipp** [comment] 2018-01-05 21:27
You got this warning without including apiguardian, right?

It will become a mandatory dependency again starting in 5.1.0-RC1.

**Comment by franklinyu** [comment] 2018-01-06 06:51
Wait what? Why? And Why didn't Gradle/Maven automatically pick it up?

**Comment by marcphilipp** [comment] 2018-01-06 11:48
That's a long story. In short, it is declared as an `optional` dependency in its [POM](http://search.maven.org/remotecontent?filepath=org/junit/jupiter/junit-jupiter-api/5.0.2/junit-jupiter-api-5.0.2.pom). Thus, Gradle/Maven will not pick it up by default. Since it's confusing and annoying we'll remove the `optional` tag starting in 5.1.0-RC. Then, Maven/Gradle will pick it up automatically and you won't see these warnings anymore.

**Comment by franklinyu** [comment] 2018-01-06 16:37
Oh, so I won't need to declare the dependency myself? Looking forward to 5.1.0-RC1 then!

**Comment by sbrannen** [comment] 2018-01-06 16:58
Right. It will then be an automatic transitive dependency.

**Comment by memelet** [comment] 2018-06-09 04:50
I have `compile 'org.apiguardian:apiguardian-api:1.0.0'` but still get the warning

**Comment by sormuras** [comment] 2018-06-09 04:53
`NeedMoreInformationToHelpException` ;-)

**Comment by memelet** [comment] 2018-06-09 15:31
I don't even know (yet) if the problem is due to junit. I stated to get the error after I added `exclude group: 'junit', module: 'junit'` so IDEA and Gradle would use the correct runner, but that could be a decoy.

I was able to remove the warnings by adding `compileOnly 'com.google.code.findbugs:jsr305:3.0.2'`. apiguardian had no effet.
