### ISSUE TITLE
Reports Generate <method_name>[1][34][21] Instead of DisplayName

### ISSUE THREAD

**Issue by kirkpabk** [junit-team/junit5#2077] opened 2019-10-22 17:11 UTC
So when using dynamic tests with nested containers, the TestSuite, Test Case DisplayName output of junit xml reporting is formatted as:

<method_name>[n][n][n]

e.g., testRunner()[1][4][21]…

So when the reports are generated, there's no correlation with the Test Suite or Test Case Display Name.   This makes any of the output that worked with previous version of JUnit useless for us.

**Comment by marcphilipp** [comment] 2019-10-22 17:34
@kirkpabk Could you please share more details on your setup?

**Comment by kirkpabk** [comment] 2019-10-23 12:10
A Java application, the dynamic portion is basically this:

```
[@TestInstance(Lifecycle.PER_METHOD)
public class TestRunner extends BaseTest {
    private Collection<DynamicContainer> dynamicTestCaseContainer = new ArrayList<>(); 
    ....
    @TestFactory
    @DisplayName("Dynamic UI Tests")
    Stream<DynamicContainer> runTestCases() {
        Collection<DynamicContainer> dynamicTestPlans = new ArrayList<>();
        Collection<DynamicTest> dynamicTestCases;
        ....
        for(TestPlan testPlan : testPlans) {
            dynamicTestCaseContainer = new ArrayList<>();
            int testCaseSize = testCaseDtoList.size();
            ....
            for (int testCase = 0; testCase < testCaseSize; testCase++) {		
                dynamicTestCases = new ArrayList<>();
                ....
                List<TestCaseStepDTO> stepList = testCaseDto.getStepList();
                int stepSize = stepList.size();
                for (int step = 0; step < stepSize; step++) {
                    ....
                    Executable exec = () -> {
                        try {
                            //perform step action
                            ....
                        } catch (Throwable e) {
                            logger.error(...
                            assertTrue(false);
                        }       
                    };
    
                    DynamicTest newDynamicTest = dynamicTest(testName, exec);
                    dynamicTestCases.add(newDynamicTest);
                }
                dynamicTestCaseContainer.add(DynamicContainer.dynamicContainer(testCaseTitle, dynamicTestCases.parallelStream()));
                dynamicTestCases = null;
            }
            dynamicTestPlans.add(DynamicContainer.dynamicContainer(testPlanTitle, dynamicTestCaseContainer.parallelStream()));
        }
        return dynamicTestPlans.parallelStream();
    }
}](url)
```

So the testCaseTitle, testPlanTitle and testName values never show up in the JUNIT XML report or the description of the test.   Only the dynamic name such as runTestCase()[3][37][3].  But even if that can't be changed, the resulting XML does not contain the testCaseTitle, testPlanTitle or testName variable values...However, when running in eclipse, they show up fine in the JUNIT test display window. So, the XML and HTML derived from the XSLT/XML report are not showing the values.  Note that the testName does show up in the display-name below.  However, the testCaseTitle and testPlanTitle are not present at all.  

```
    <testcase classname="com.somecompany.TestRunner" name="runTestCase()[3][37][3]" time="0.94">
      <system-out><![CDATA[
unique-id: [engine:junit-jupiter]/[class:com.somecompany.TestRunner]/[test-factory:runTestCase()]/[dynamic-container:#3]/[dynamic-container:#37]/[dynamic-test:#3]
display-name: TEST - ACTION: 'gotourl'  SYMBOL: ''  VALUE: 'https://somecompany.com/someapp/home.jsf'
]]></system-out>
```

Not sure if this helps to understand what I'm seeing...   From the eclipse side, JUnit displays,
> TestRunner [Runner: JUnit 5]
   > Dynamic UI Tests   <-- from the Display Name Annotation
      > BK_SUITE...   <-- from the dynamicContainer method
         > Reset Cookies and Browser Type   <-- from the dynamicContainer method
            >Test 1.0 Delete Cookies  <-- from the dynamicTest method


In the JUnit XML HTML report, all we see is:

Class                Name                           Status          Type           Time(s)
JUnit Jupiter    runTestCase()[1][7][2]   Success                          0.010
JUnit Jupiter    runTestCase()[1][7][1]   Success                          0.001
JUnit Jupiter    runTestCase()[1][3][2]   Success                          0.069

Not very helpful in correlating....  I figured that if the values passed to the methods somehow made it into the XML, then we would at least be able to adapt the XSLT to display it correctly.  

As other users have said...reverting to previous versions is what our leadership is expecting us to do, if we can't get this to work.  Open for any ideas--but super job folks!!  Keep up the great work!

**Comment by sormuras** [comment] 2019-10-23 12:40
Is `"TEST - ACTION: 'gotourl'  SYMBOL: ''  VALUE: 'https://somecompany.com/someapp/home.jsf'"` the `String` supplied to `dynamicTest(testName, exec)` as `testName`?

**Comment by sbrannen** [comment] 2019-10-23 13:00
> So when using dynamic tests with nested containers, the TestSuite, Test Case DisplayName output of junit xml reporting is formatted as:
> 
> <method_name>[n][n][n]
> 
> e.g., testRunner()[1][4][21]…

That's to be expected.

This is the "technical name" of the element.

Since the "legacy JUnit 4 XML reporting format" is based solely on technical names without support for custom display names (introduced in the JUnit Platform in JUnit 5), the only way for us to output the display name is via the CDATA section as you have noted.

> So when the reports are generated, there's no correlation with the Test Suite or Test Case Display Name. 

The reason you can't find a correlation between the dynamic test invocation and its enclosing dynamic container(s) is that the legacy XML reporting format does not support arbitrary hierarchies like the JUnit Platform does.

> This makes any of the output that worked with previous version of JUnit useless for us.

If you need that level of detail in your own custom reports, you can always implement your own `TestExecutionListener`.

Let us know if you have any further questions.

**Comment by kirkpabk** [comment] 2019-10-23 13:22
@sormura, yes exactly.

**Comment by kirkpabk** [comment] 2019-10-23 13:25
@sbrannen, <grin> was suspecting this...  well, hopefully it will all catch up soon.  There's a huge need for adopters.   Great quick response, though Sam!

**Comment by sormuras** [comment] 2019-10-23 13:27
> [...] yes exactly.

Then you're in control of the "char data". Just enhance it to your liking/needs. Granted, composing the display name of all parent containers might lead to loooong names when viewed in an IDE, but it should "fix" your correlation issue within the legacy XML file.

Winter 2019 is coming. It might bring https://github.com/ota4j-team/opentest4j/issues/9 to life.

**Comment by marcphilipp** [comment] 2019-10-23 17:53
@kirkpabk Thanks for the feedback! I'm closing this as a duplicate of #373.

**Closed by marcphilipp** 2019-10-23 17:53 UTC
Labels: status: waiting-for-feedback
