### ISSUE TITLE
Dynamic parameters for Parameterized tests

### ISSUE THREAD

**Issue by arturmkr** [junit-team/junit5#2561] opened 2021-03-02 13:38 UTC
It would be great, if it would be possible to pass dynamic argument to the method that provides data for parameterised test.

For example, there is following class with methods, which provides test data:

```java
public class MyTestData {
    public static Stream<Arguments> someDataProvider() {
        return Stream.of(
                Arguments.of("Jake", 63, 31, 32, 0),
                Arguments.of("Mike", 81, 41, 32, 2),
                Arguments.of("Jake", 63, 31, 32, 0),
                Arguments.of("Mike", 81, 41, 32, 2),
                Arguments.of("Jake", 63, 31, 32, 0),
                Arguments.of("Mike", 81, 41, 32, 2),
                Arguments.of("Jake", 63, 31, 32, 0),
                Arguments.of("Mike", 81, 41, 32, 2),
                Arguments.of("Mike", 20, 21, 19, 0));
    }
}
```

There is a class with a test:

```java
class MyTestRun {
  private String someName;

  @BeforeEach
  void setUp() {
    someName = "Jake";
  }

  @ParameterizedTest()
  @MethodSource("com.example.MyTestData#someDataProvider")
  void someTest(String name, int a, int b, int c, int d) {
    System.out.println(name);
  }
}
```

I would like from `someTest` method pass `someName` variable to `someDataProvider` method.
And inside `someDataProvider` method filter values.
As a result, `someTest` method would receive data only, where name equals "Jake".

**Comment by sbrannen** [comment] 2021-03-02 13:49
> I would like from `someTest` method pass `someName` variable to `someDataProvider` method.

In general, I understand your overall goal, but how should `someTest` "pass" anything to `someDataProvider`?

`someTest` cannot practically pass/send anything to the `@MethodSource` method, because `someTest` cannot be invoked until after the `@MethodSource` method has been invoked.

On the other hand, I could imagine that JUnit Jupiter could provide the `someDataProvider` method a reference to the method for which it is currently being invoked. Then `someDataProvider` could look up annotations on `someTest` -- for example, `@Filter("Jake")` for your particular use case.

Would something like that meet your needs?

**Comment by sbrannen** [comment] 2021-03-02 13:52
Note that this is a potential duplicate of #2191, since `TestInfo` provides access to the test method.

**Comment by arturmkr** [comment] 2021-03-04 21:49
@sbrannen , thanks you for the reply.

Here is another problem:

```
class SomeTestClass {
  protected String user;
  SomeClass someClass;

  @BeforeEach
  void setUp() {
    someClass = new SomeClass();
    user = someClass.someNotStaticMethod();
  }

  static Stream<BasePage> someDataClasses() {
    return Stream.of(new PageA(user), new PageB(user));
  }

  @ParameterizedTest()
  @MethodSource("someDataClasses")
  void someTestRun(BasePage basePage) {
    basePage.open();
  }
}

```
PageA and PageB extends BasePage.
To create instance of PageA and PageB - `String user` variable should be passed to the constructor.
String user - is not static variable, it's always dynamic.

How to pass to the test instance of the class, if for its creation not static variable is needed?

**Comment by marcphilipp** [comment] 2021-03-05 11:19
**Team decision:** We don't think this use case is generally useful enough to change how parameterized tests work. Instead of using parameterized tests for this, you could write your own extension that implements `TestTemplateInvocationContextProvider` and `BeforeEachCallback`.

**Closed by marcphilipp** 2021-03-05 11:19 UTC
Labels: component: Jupiter, status: waiting-for-feedback, theme: parameterized tests, type: enhancement
