### ISSUE TITLE
JUnit Platform Surefire Provider does not distinguish between failure and error

### ISSUE THREAD

**Issue by bonigarcia** [junit-team/junit5#1019] opened 2017-08-15 00:14 UTC
I am using JUnit 5 RC2 to execute the following simple test case, both with Maven and Gradle:

```java
package io.github.bonigarcia;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class PlayingWithReportingTest {

    @Test
    void successTest() {
        assertTrue(true);
    }

    @Test
    void failureTest() {
        assertTrue(false);
    }

    @Test
    void errorTest() {
        throw new RuntimeException("This test is broken!");
    }

}
```

When running with Maven, I get the following:

```
> mvn clean test
[INFO] Scanning for projects...
...

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running io.github.bonigarcia.PlayingWithReportingTest
Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.106 sec <<< FAILURE! - in io.github.bonigarcia.PlayingWithReportingTest
errorTest()  Time elapsed: 0.021 sec  <<< FAILURE!
java.lang.RuntimeException: This test is broken!
        at io.github.bonigarcia.PlayingWithReportingTest.errorTest(PlayingWithReportingTest.java:37)

failureTest()  Time elapsed: 0.003 sec  <<< FAILURE!
org.opentest4j.AssertionFailedError:
        at io.github.bonigarcia.PlayingWithReportingTest.failureTest(PlayingWithReportingTest.java:32)


Results :

Failed tests:
  PlayingWithReportingTest.errorTest:37 Runtime This test is broken!
  PlayingWithReportingTest.failureTest:32

Tests run: 3, Failures: 2, Errors: 0, Skipped: 0
```

... which I think is incorrect, since I would expect that 1 test (`failureTest`) is declared as failure (assertion error), other one (`errorTest`) is declared and error (exception in the test), and the other one as success. Instead, the Maven output says there are 2 failures.

Moreover, when running the same test with Gradle:

```
> gradle clean test
:clean
...

Failures (2):
  JUnit Jupiter:PlayingWithReportingTest:errorTest()
    MethodSource [className = 'io.github.bonigarcia.PlayingWithReportingTest', methodName = 'errorTest', methodParameterTypes = '']
    => java.lang.RuntimeException: This test is broken!
  JUnit Jupiter:PlayingWithReportingTest:failureTest()
    MethodSource [className = 'io.github.bonigarcia.PlayingWithReportingTest', methodName = 'failureTest', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError:

Test run finished after 128 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         3 tests found           ]
[         0 tests skipped         ]
[         3 tests started         ]
[         0 tests aborted         ]
[         1 tests successful      ]
[         2 tests failed          ]

:junitPlatformTest FAILED
```

Similaryly, there are 2 tests declared as failure and besides, the output says there that 2 containers found, but if I'm not wrong there should be just one, since there is only one test class in the project.

Is this a bug or I am misinterpreting something here?

Thanks in advance. Keep up with great work!

PS: Source code [here](https://github.com/bonigarcia/mastering-junit5/tree/master/junit5-reporting).

**Comment by sbrannen** [comment] 2017-08-15 22:14
>  JUnit 5 does not distinguish between failure and error

That's correct. The JUnit Platform does not distinguish between different types of `Throwable` with regard to the _exception_ associated with a _failed_ `TestIdentifier`.

See `org.junit.platform.engine.TestExecutionResult.failed(Throwable)` for details.

**Comment by sbrannen** [comment] 2017-08-15 22:15
> Instead, the Maven output says there are 2 failures.

That's correct.

**Comment by sbrannen** [comment] 2017-08-15 22:17
> Similaryly, there are 2 tests declared as failure and besides, the output says there that 2 containers found, but if I'm not wrong there should be just one, since there is only one test class in the project.
> 
> Is this a bug or I am misinterpreting something here?

You're misinterpreting something here. 😉 

The 1st _container_ is the `JupiterTestEngine`; the 2nd _container_ is the `PlayingWithReportingTest` test class. Thus, there are in fact 2 containers.

**Comment by sbrannen** [comment] 2017-08-15 22:18
Closing this issue as _works as designed_.

**Comment by sbrannen** [comment] 2017-08-15 22:19
> Keep up with great work!

Thanks! 😎

**Comment by marcphilipp** [comment] 2017-08-19 18:12
I'm reopening this issue because while neither JUnit Platform, JUnit Jupiter, nor JUnit 4 distinguish between failures and errors, Maven Surefire does (e.g. to support JUnit 3).

So, our Surefire provider should take the same approach as the one Surefire provides for JUnit 4:
https://github.com/apache/maven-surefire/blob/b54e33e68e9c3e13f8fca4b66dbb5c89a0a30715/surefire-providers/common-junit4/src/main/java/org/apache/maven/surefire/common/junit4/JUnit4RunListener.java#L112-L119

**Comment by marcphilipp** [comment] 2017-08-19 18:33
_in progress_

**Closed** 2017-08-19 18:47 UTC
Labels: component: Surefire, status: in progress, type: bug
