### ISSUE TITLE
Gradle plugin to support 'ignoreFailures'

### ISSUE THREAD

**Issue by cschwarz-inco** [junit-team/junit5#1107] opened 2017-10-13 23:04 UTC
The Gradle plugin for JUnit 4 allows you to set 'ignoreFailures = true' so that failing tests do not fail the task.

There is no such option for the JUnit 5 gradle plugin. Please consider adding it.

The absence of this feature is a major roadblock for migrating to JUnit 5 as our builds rely on it heavily.

**Comment by sbrannen** [comment] 2017-10-14 17:07
Closing this issue as a duplicate of #315.

**Closed by sbrannen** 2017-10-14 17:07 UTC
