### ISSUE TITLE
Complain when @Test is applied to an inappropriate method

### ISSUE THREAD

**Issue by islandsvinur** [junit-team/junit5#1074] opened 2017-09-25 08:28 UTC
## Overview

When writing tests in Groovy, it's tempting to use `def` for the test methods, since that is typically the way to go in Groovy. However, for `def` the compiler produces a method that returns `Object`.

If this was a method annotated with `@Test`, it would be silently ignored by JUnit, as it should be a `void` method. This leads to lots of pulled hairs and other frustrations.

```
Test run finished after 13 ms
[         2 containers found      ]
[         0 containers skipped    ]
[         2 containers started    ]
[         0 containers aborted    ]
[         2 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]
```

I would like JUnit to shout in my face that I'm using it wrong.

## Deliverables

- [ ] ...

**Comment by bechte** [comment] 2017-09-25 09:42
Thanks for bringing up this issue. 

We will have a look into it and provide a validation message that complains about the generated method or provide a fallback (and only printing a warning).

**Comment by sbrannen** [comment] 2017-09-25 13:50
Closing this issue since it is a duplicate of #242.

**Closed by sbrannen** 2017-09-25 13:50 UTC
Labels: component: Jupiter, status: team discussion, theme: discovery, type: enhancement
