### ISSUE TITLE
Upload Gradle Plugin to plugins.gradle.org to support Gradle DSL

### ISSUE THREAD

**Issue by jochenchrist** [junit-team/junit5#877] opened 2017-06-09 09:09 UTC
I'd be great to use the nice [Gradle Plugin DSL](https://docs.gradle.org/3.5/userguide/plugins.html#sec:plugins_block) for running JUnit Platform in Gradle builds.

I suggest to upload the _junit-platform-gradle-plugin_ to https://plugins.gradle.org

Instead of
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.0-M4'
    }
}

apply plugin: 'org.junit.platform.gradle.plugin'
apply plugin: 'java'
```

the build.gradle could then look like:

```
plugins {
    id 'java'
    id 'org.junit.platform.gradle.plugin' version '1.0.0-M4'
}
```

Which is much more compact.

**Comment by sormuras** [comment] 2017-06-09 09:11
Duplicate of https://github.com/junit-team/junit5/issues/768

**Closed by sormuras** 2017-06-09 09:11 UTC
Labels: status: duplicate
