### ISSUE TITLE
JUnit 5 console launcher requires include classes pattern even when test class specified

### ISSUE THREAD

**Issue by georgeharley** [junit-team/junit5#2289] opened 2020-05-06 13:06 UTC
## Steps to reproduce

When using the 1.7.0-M1 JUnit 5 console launcher to run Spock tests from the command it failed to discover and run the tests even though `--select-class` was correctly specifiying the name of the Spock test class which was on the classpath along with the other required dependencies. To resolve the problem the `--include-classname` option also needs to be supplied with a regex that the value of `--select-class` satisfies. Given that the name of the test class has been explicitly supplied and there is no classpath scanning going on it feels unnecessary to also have to supply this regex pattern.

I've created a small GitHub [repo](https://github.com/georgeharley/spock-test-app) to help demonstrate the problem.

## Context

 - Used versions (Jupiter/Vintage/Platform): JUnit5 console launcher version 1.7.0-M1
 - Spock version: Spock version 2.0-groovy-2.5-SNAPSHOT
 - Build Tool/IDE: IntelliJ
 - Java version: Java 8
 - OS: macOS

**Comment by sbrannen** [comment] 2020-05-06 13:36
Duplicate of #2270 which has already been addressed in 5.7 M2.

**Closed by sbrannen** 2020-05-06 13:36 UTC
