### ISSUE TITLE
Provide a way to find out arguments in parameterized tests in setup methods (@BeforeEach and @BeforeAll)

### ISSUE THREAD

**Issue by bonigarcia** [junit-team/junit5#2559] opened 2021-02-25 16:16 UTC
To the best of my knowledge, arguments in parameterized tests are injected into `@Test` methods, but it is not possible to know these values in the previous stages of the test lifecycle (i.e., in `@BeforeEach` and `@BeforeAll`). I face some use cases in which this is desirable. Would it be possible to implement some mechanism to find out the value of these arguments before the actual test?

As a possible alternative, we could have an enhanced version of `@TestInfo` providing some accessor for arguments in parameterized tests. A `@TestInfo` parameter, injected at  `@BeforeEach` or `@BeforeAll` methods, could do the trick.

**Comment by sbrannen** [comment] 2021-02-26 09:02
Closing as a duplicate of #944.

**Closed by sbrannen** 2021-02-26 09:02 UTC
