### ISSUE TITLE
Allow ParameterResolver to tell apart parameters with a Source in a ParameterizedTest

### ISSUE THREAD

**Issue by serandel** [junit-team/junit5#2216] opened 2020-03-16 12:39 UTC
I've got a `ParameterResolver` that I'm very keen of that injects any parameter in a test class or method with a fresh mock. My problem is that I'm trying to include some ParametererizedTests in my suite and now JUnit is telling me that:

```
Discovered multiple competing ParameterResolvers for parameter [float arg0] in method [public final void com.package.TestClass.testMethod(float, boolean, MyClass)]: MyTestExtensionClass@33b5ad8e, org.junit.jupiter.params.ParameterizedTestParameterResolver@44b312e
```

In my extension, I have this method to filter parameters

```kotlin
    override fun supportsParameter(parameterContext: ParameterContext, extensionContext: ExtensionContext): Boolean
    // We just support regular parameters
            = !parameterContext.parameter.isImplicit
            && !parameterContext.parameter.isSynthetic
            && !parameterContext.parameter.isVarArgs
```

but I'm seeing nothing in `parameterContext.parameter` to filter by parameters that will be supplied by a Source (in my case `@CsvSource`, but it could be any other).

My workaround is going to be to filter out Int, Boolean, String, etc. (I'm using Kotlin), as I'm not going to mock those basic types, but I wonder if I'm overlooking something or if this can be included in a future version, as other extensions may not be able to leverage such a crude solution.

Thanks!

**Comment by sbrannen** [comment] 2020-03-16 12:43
Have you read the [Consuming Arguments](https://junit.org/junit5/docs/current/user-guide/#writing-tests-parameterized-tests-consuming-arguments) section of the User Guide?

> Specifically, a parameterized test method must declare formal parameters according to the following rules.
> * Zero or more indexed arguments must be declared first.
> * Zero or more aggregators must be declared next.
> * Zero or more arguments supplied by a ParameterResolver must be declared last.

**Comment by serandel** [comment] 2020-03-16 12:49
Yes, I think I'm following that, if I understood correctly.

My code is the following:

```
    @ParameterizedTest
    @CsvSource("0f, false",
            "5f, false",
            "10f, true")
    fun `condition with only an upper threshold`(value: Float, satisfied: Boolean, entity: Entity) {
        ...
    }
```

My ParameterResolver can supply Entity with no problem, but I think the clash comes because it will also gladly supply a mock for Float and Boolean, per the `supportsParameter` function in the description. :/

**Comment by serandel** [comment] 2020-03-16 12:50
All the examples I've seen filter by parameter class in `supportsParameter`, so they don't hit my problem.

**Comment by sormuras** [comment] 2020-03-16 12:54
How about an extra tagging annotation, like `@FreshMock`, to pre-select your resolver?

`test(float f, boolean b, @FreshMock Entity entity) {...}`

**Comment by sbrannen** [comment] 2020-03-16 13:00
> All the examples I've seen filter by parameter class in `supportsParameter`, 

As a general guideline, a `ParameterResolver` should **never** be greedy: it should never resolve _anything_.

Rather, in order for a `ParameterResolver` to be a "good citizen", it must claim that it _supports_ a parameter based on a unique type or the presence of a custom annotation.

Any `ParameterResolver` that does not follow the "good citizen" rules cannot reliably be used in conjunction with any other resolvers.

> so they don't hit my problem.

Exactly. If you don't follow the "good citizen" rules, you'll run into that problem.

**Comment by sbrannen** [comment] 2020-03-16 13:02
Though, to be honest, if your `@CsvSource` is supplying only two arguments, and the third argument is resolved by your custom resolver, I'm not sure why there is a conflict.

I _thought_ that would be avoided, but perhaps I am not recalling correctly.

**Comment by sbrannen** [comment] 2020-03-16 13:11
> I _thought_ that would be avoided, but perhaps I am not recalling correctly.

I was mixing up the logic in `ParameterizedTestParameterResolver` in my head. 

`ParameterizedTestParameterResolver` won't interfere with your custom resolver, but the inverse is not true. That's why you're hitting this problem: your custom resolver conflicts with `ParameterizedTestParameterResolver`.

**Comment by serandel** [comment] 2020-03-16 13:12
I didn't realize tagging with an annotation was a best practice or that greedy resolvers would be problematic. I think it might be a good addition to the docs. (It also may well be possible that I've overlooked that part!)

Anyway, using the annotation, even if I don't love it (my tests looked so clean ;) ) seems a completely reasonable way to go forward, so I'll just do that.

Having said that, I think that there might be an underlying bug here, as the parameters covered by a Source perhaps shouldn't be passed to other ParameterResolvers down the line, should they?

Thank you for your kind help. :)

**Comment by sbrannen** [comment] 2020-03-16 13:17
> I didn't realize tagging with an annotation was a best practice or that greedy resolvers would be problematic. I think it might be a good addition to the docs. (It also may well be possible that I've overlooked that part!)

Hmmm.... I've certainly explained it like that multiple times over the years, but perhaps it's not actually documented (yet).

Oh wait...... speak of the 😈 ....... there's that issue I raised to address this: #1190. 🤦‍♂ 

> Anyway, using the annotation, even if I don't love it (my tests looked so clean ;) ) seems a completely reasonable way to go forward, so I'll just do that.

Sounds good!

> Having said that, I think that there might be an underlying bug here, as the parameters covered by a Source perhaps shouldn't be passed to other ParameterResolvers down the line, should they?

I wouldn't say it's a bug. It's actually "by design", though I understand that it's not perfect. Speaking of which, you might be interested in #1945.

> Thank you for your kind help. :)

You're welcome.

**Comment by sbrannen** [comment] 2020-03-17 10:46
In light of the above, I am closing this issue in favor of #1190 and #1945.

**Closed by sbrannen** 2020-03-17 10:46 UTC
Labels: component: Jupiter, theme: parameterized tests
