### ISSUE TITLE
TestReporter does not capture the correct TestIdentifier when used with DynamicTests

### ISSUE THREAD

**Issue by nilsga** [junit-team/junit5#393] opened 2016-07-11 17:45 UTC
I'm investigating JUnit5 for a project, and I find the concept of `TestFactory` and `DynamicTests` interesting for our use case. During the execution of a `DynamicTest`, I would also like to report some additional information for that particular test, so I added a `TestReporter` parameter to the `TestFactory` method: 

``` java
@TestFactory
public void createTests(TestReporter reporter) {
  Stream<DynamicTest> tests = createTests(reporter);
}
```

Using a `TestExecutionListener`, I can see that the `ReportEntry`s are published, but they are all associated with the wrong `TestIdentifier`. Quite obvious, when thinking about it, since the `TestReporter`, once injected, is associated with the `ExtensionContext` it was assigned when it was created.

So it does not seem to be possible to use a `TestReporter` in conjunction with `DynamicTest` this way. Is it possible to achieve this some other way? Since the `TestExecutionListener` reports the correct `TestIdentifier` for lifecycle events (e.g. `executionFinished`) for the other `DynamicTest`s, it seems like it should be possible somehow to dynamically assign the correct context to a `TestReporter`.
## Related Issues
- #14 
- #378 
- #386

**Comment by sbrannen** [comment] 2016-07-11 20:04
FYI: this is related to #378 and #386.

**Comment by sbrannen** [comment] 2016-07-11 20:05
> So it does not seem to be possible to use a `TestReporter` in conjunction with `DynamicTest` this way. 

That's correct.

> Is it possible to achieve this some other way?

**Comment by nilsga** [comment] 2016-07-11 20:08
Yes, found those issues after posting this. Thanks. Sorry about the duplication.

**Comment by sbrannen** [comment] 2016-07-11 20:11
No worries!

The use of a `TestReporter` in dynamic tests will be addressed in #378, so I'll close this issue as a _duplicate_ now.

**Closed by sbrannen** 2016-07-11 20:11 UTC
Labels: status: duplicate, theme: extensions, theme: programming model, theme: execution, theme: reporting

**Comment by whytox** [comment] 2024-12-30 19:23
One simple solution would be to save the dynamicTest's TestIdentifier in a variable of the TestExecutionListener when the testExecutionStarted lifecycle method kicks and use that instead of the TestIdentifier supplied in the arguments of reportEntryPublished.

So, for example, supposing that your dynamic test has access to the TestFactory's TestReport and use it to publishEntries:

```
public class MyReportListener extends SummaryGeneratingListener {

     private TestIdentifier currentTestBeingExecuted;

    @Override
    public void executionStarted(TestIdentifier testIdentifier) {
        super.executionStarted(testIdentifier);
        if (testIdentifier.isContainer()) {
            return;
        }
        currentTestBeingExecuted = testIdentifier;
    }


    @Override
    public void reportingEntryPublished(TestIdentifier testIdentifier, ReportEntry entry) {
        super.reportingEntryPublished(testIdentifier, entry);
        TestIdentifier dynamicTestIdentifier = testIdentifier;
        if (!testIdentifier.equals(currentTestBeingExecuted)) {
            // then the entry has been probably been published by a dynamic test
            // using its container TestReporter
            dynamicTestIdentifier = currentTestBeingExecuted;
         }
        // do your stuff with the real testIdentifier
    }
```

**Comment by marcphilipp** [comment] 2024-12-31 10:05
Here's another workaround: https://github.com/junit-team/junit5/discussions/4175#discussioncomment-11508863

**Comment by marcphilipp** [comment] 2025-01-27 07:16
Duplicate of #378
