### ISSUE TITLE
Build error in Intellij

### ISSUE THREAD

**Issue by IgorGanapolsky** [junit-team/junit5#2084] opened 2019-10-25 19:56 UTC
Please provide us the version of JUnit 5 you are using and, if possible, a failing unit test with your bug report. Don't forget to describe the rationale for this issue (e.g. expected vs. actual behavior).

## Steps to reproduce
Open project in IntelliJ Ultimate EAP 2019.3.
Select Build -> Rebuild project.
Observe the error

Please insert a code snippet or a link to another repo along with instructions how to reproduce the issue here.
> Execution failed for task ':junit-platform-commons:jar'.  No value present

## Context

 - Used versions (Jupiter/Vintage/Platform): latest from **master** branch
 - Build Tool/IDE: 
IntelliJ IDEA 2019.3 EAP (Ultimate Edition)
Build #IU-193.4778.7, built on October 23, 2019
IntelliJ IDEA EAP User
Expiration date: November 21, 2019
Runtime version: 1.8.0_212-release-b1596 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by marcphilipp** [comment] 2019-10-26 10:47
@IgorGanapolsky I cannot reproduce this with the latest Community Edition EAP version. Could you please add `publishAlways()` to the `buildScan {}` block in `build.gradle.kts`, run it again and share the resulting build scan with us?

**Comment by IgorGanapolsky** [comment] 2019-10-26 15:23
Hello @marcphilipp.  When running from commandline with `./gradlew build`, it works.  However, the IDE shows a ton of warnings (red highlights) in all `.kts` files, and clicking **Build -> Rebuild Project** produces the aforementioned error: https://scans.gradle.com/s/kpnmxkorkr4uw

**Comment by marcphilipp** [comment] 2019-10-26 16:33
From the [failure](https://scans.gradle.com/s/kpnmxkorkr4uw/failure?openFailures=WzBd&openStackTraces=WzFd#top=0), it seems the JDK you're using does not have a `ToolProvider` for `jar`:
https://github.com/junit-team/junit5/blob/4f801d02082610ec3851eebddb8466c807926ed0/junit-platform-commons/junit-platform-commons.gradle.kts#L17

You're using [JetBrains s.r.o OpenJDK Runtime Environment 11.0.4+10-b520.2](https://scans.gradle.com/s/kpnmxkorkr4uw/infrastructure). Please change the JDK you're using in IDEA:

<img width="1094" alt="Screenshot 2019-10-26 at 18 31 14" src="https://user-images.githubusercontent.com/214207/67622860-eff48e80-f81e-11e9-9435-af0516c35ad7.png">

AdoptOpenJDK or OpenJDK should work.

**Comment by marcphilipp** [comment] 2019-10-26 16:35
I'm closing this issue assuming the above instructions will resolve the problem.

@IgorGanapolsky Please let me know if that helped.

**Closed by marcphilipp** 2019-10-26 16:35 UTC
Labels: theme: build

**Comment by marcphilipp** [comment] 2019-10-26 16:39
@IgorGanapolsky Would you mind reporting this issue to JetBrains?

**Comment by IgorGanapolsky** [comment] 2019-10-27 15:07
Could you please explain why one JDK works vs the other one?

**Comment by IgorGanapolsky** [comment] 2019-10-27 15:13
I opened issue with JetBrains, however I believe they'll tell me to come back to you  :)
https://youtrack.jetbrains.com/issue/IDEA-225679?project=IDEA&clearDraft=true&description=%0A%0AIU-193.4778.7,%20JRE%201.8.0_212-release-b1596x64%20JetBrains%20s.r.o,%20OS%20Mac%20OS%20X(x86_64)%20v10.15.1,%20screens%201680x1050;%20Retina

**Comment by marcphilipp** [comment] 2019-10-27 15:29
Thanks for creating the issue, I added a comment there.

**Comment by sormuras** [comment] 2019-10-27 17:57
> Runtime version: `1.8.0_212-release-b1596 x86_64`

If I read the initial issue description correctly, I see that you're using a Java **8** runtime -- but at least JDK **11** is needed: https://github.com/junit-team/junit5#building-from-source

**Comment by IgorGanapolsky** [comment] 2019-10-27 18:05
@sormuras That is the default on Macbook Pro that I bought.  Do we have to upgrade?

**Comment by sormuras** [comment] 2019-10-27 18:17
If you want to build "JUnit 5" from source, yes. At least, you need to install and use a JDK 11 distro for this project.

**Comment by IgorGanapolsky** [comment] 2019-10-27 18:22
IntelliJ should have that bundled with IDE, as far as I know....

**Comment by sormuras** [comment] 2019-10-27 18:59
> IntelliJ should have that bundled with IDE, as far as I know....

They offer both variants at https://www.jetbrains.com/idea/nextversion/

![image](https://user-images.githubusercontent.com/2319838/67639742-c48fa380-f8f3-11e9-9453-98dd55825278.png)

- **INTELLIJ IDEA + JETBRAINS RUNTIME 11**
- **INTELLIJ IDEA + JETBRAINS RUNTIME 8**

**Comment by sormuras** [comment] 2019-10-27 19:02
Having said this, I confirm that the "JBR 11" only provides a single `ToolProvider`, namely:

```
javac [module jdk.compiler@11.0.4] com.sun.tools.javac.main.JavacToolProvider
```

Like @marcphilipp wrote above, this does **not** suffice to build JUnit 5. Please install a JDK 11+ for your OS and use this to build JUnit 5.

**Comment by IgorGanapolsky** [comment] 2019-10-28 13:42
@sormuras Most unassuming users - when they search for IntelliJ on google, will land on the following page.  There isn't a clear indicator there which darn Java version is required or comes bundled with IntelliJ:
<img width="1680" alt="Screen Shot 2019-10-28 at 9 40 41 AM" src="https://user-images.githubusercontent.com/201209/67683126-29381600-f967-11e9-8815-757699920f71.png">
<img width="1680" alt="Screen Shot 2019-10-28 at 9 40 43 AM" src="https://user-images.githubusercontent.com/201209/67683127-29381600-f967-11e9-9cdc-b7edb9b8a630.png">
