### ISSUE TITLE
Cannot build JUnit 5 on Microsoft Windows

### ISSUE THREAD

**Issue by PeterWippermann** [junit-team/junit5#398] opened 2016-07-13 22:21 UTC
Tried to run `gradlew clean test`, but at least two tests fail although [CI status is "green"](https://travis-ci.org/junit-team/junit5/jobs/144558735).
```
:platform-tests:junitPlatformTest

Test failures (2):
  JUnit Jupiter:ColoredPrintingTestListenerTests:exceptionMessageIndented()
    JavaMethodSource [javaClass = 'org.junit.platform.console.tasks.ColoredPrintingTestListenerTests', javaMethodName = 'exceptionMessageIndented', javaMethodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <Finished:    failingTest [[engine:junit]]
             => Exception: Fail
               expected: <foo> but was: <bar>
> but was: <Finished:    failingTest [[engine:junit]]
             => Exception: Fail
                expected: <foo> but was: <bar>
>
  JUnit Jupiter:ColoredPrintingTestListenerTests:executionSkippedMessageIndented()
    JavaMethodSource [javaClass = 'org.junit.platform.console.tasks.ColoredPrintingTestListenerTests', javaMethodName = 'executionSkippedMessageIndented', javaMethodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <Skipped:     failingTest [[engine:junit]]
             => Reason: Test
                  disabled
> but was: <Skipped:     failingTest [[engine:junit]]
             => Reason: Test
                   disabled
>

Test run finished after 2363 ms
[       360 tests found     ]
[         0 tests skipped   ]
[       360 tests started   ]
[         0 tests aborted   ]
[       358 tests successful]
[         2 tests failed    ]

:platform-tests:junitPlatformTest FAILED

FAILURE: Build failed with an exception.
```

Also tried to run `gradlew clean check`, but got:
```
:spotlessDocumentationCheck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':spotlessDocumentationCheck'.
> Format violations were found. Run 'gradlew spotlessApply' to fix them.
    .github\PULL_REQUEST_TEMPLATE.md
    CONTRIBUTING.md
    documentation\README.md
    documentation\src\docs\asciidoc\advanced-topics.adoc
    documentation\src\docs\asciidoc\api-evolution.adoc
    documentation\src\docs\asciidoc\contributors.adoc
    documentation\src\docs\asciidoc\extensions.adoc
    documentation\src\docs\asciidoc\index.adoc
    documentation\src\docs\asciidoc\launcher-api.adoc
    documentation\src\docs\asciidoc\migration-from-junit4.adoc
    documentation\src\docs\asciidoc\overview.adoc
    documentation\src\docs\asciidoc\release-notes-5.0.0-ALPHA.adoc
    documentation\src\docs\asciidoc\release-notes-5.0.0-M1.adoc
    documentation\src\docs\asciidoc\release-notes.adoc
    documentation\src\docs\asciidoc\running-tests.adoc
    documentation\src\docs\asciidoc\writing-tests.adoc
    LICENSE.md
    README.md

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Tried to build with Gradle 2.14 as well as 3.0-20160702000020+0000.
Do I have a local problem?

**Comment by smoyer64** [comment] 2016-07-13 22:45
I built locally this afternoon as of commit 4aa8827.

**Comment by sbrannen** [comment] 2016-07-14 14:47
I have no problems building against the current `master`.

Can you please share with us the output from `./gradlew -version`?

**Comment by PeterWippermann** [comment] 2016-07-14 15:53
Regarding your feedback in #397 I switched back to 2.14, but the error stays the same.

```
C:\Users\pwippermann\git\junit5>gradlew -version

------------------------------------------------------------
Gradle 2.14
------------------------------------------------------------

Build time:   2016-06-14 07:16:37 UTC
Revision:     cba5fea19f1e0c6a00cc904828a6ec4e11739abc

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Windows 10 10.0 amd64
```

**Comment by sbrannen** [comment] 2016-07-14 17:23
Thanks for sharing the Gradle version information.

Since you're building on windows, it is now apparent that it is almost certainly an issue with EOL characters.

Oh the joy of _Write Once, Debug Everywhere_! 😞 

We'll look into it.

**Comment by jbduncan** [comment] 2016-07-14 17:32
I know that projects like [Checkstyle](https://github.com/checkstyle/checkstyle) use AppVeyor to test against Windows VMs (in addition to using TravisCI for Linux coverage). Perhaps using AppVeyor would prevent these sorts of errors cropping up again in the future?

**Comment by sbrannen** [comment] 2016-07-14 17:53
AppVeyor (or similar) sounds like a very good idea.

I'll create an issue to track this.

Cheers!

**Comment by sbrannen** [comment] 2016-07-14 17:56
See #403 regarding setting up a build on Windows.

**Comment by sbrannen** [comment] 2016-07-14 18:00
_in progress_

**Comment by sbrannen** [comment] 2016-07-14 18:12
@PeterWippermann, I _believe_ I have resolved the build issue regarding the failing tests in commmit bd7128af868e1c784233fa4eef3833b136cce168.

However, I do not have access to a Windows development machine at the moment. Thus, I would be grateful if you could try the build again locally on your machine with the latest state of `master`.

Thanks!

Sam

**Comment by sbrannen** [comment] 2016-07-14 18:12
FYI: bd7128af868e1c784233fa4eef3833b136cce168 does _not_ address the issues with Spotless.

**Comment by sbrannen** [comment] 2016-07-14 18:21
**Update**

It appears that Spotless will provide a solution for the EOL mismatch in Spotless 2.0: https://github.com/diffplug/spotless/issues/23

**Comment by sbrannen** [comment] 2016-07-14 18:24
@PeterWippermann, have you tried checking out the JUnit 5 code base _with CRLF-line-endings under Windows_ (see https://github.com/diffplug/spotless/pull/22)?

**Comment by sbrannen** [comment] 2016-07-14 19:18
No longer _in progress_ --> _waiting for feedback_.

**Comment by nedtwigg** [comment] 2016-07-14 22:01
I'm not positive, but I think you can fix this in Spotless 1.x:

in `build.gradle`
```
spotless {
    ...
    lineEndings 'UNIX'
}
```

in `.gitattributes`
````
* text eol=lf
```

Now git will always checkout `\n`, and spotless will enforce them.

**Comment by sbrannen** [comment] 2016-07-15 13:48
@nedtwigg, thanks for the tips!

I'm investigating a solution.

**Comment by sbrannen** [comment] 2016-07-15 13:50
@PeterWippermann, can you please let us know what the output of the following command is on your Windows machine?

`git config --global core.autocrlf`

Thanks in advance

**Comment by sbrannen** [comment] 2016-07-15 14:06
I set up a Windows 10 environment that reproduced the initially reported problem by running `git config --global core.autocrlf false`.

Then, after dc5e8753963928850b3092a456090b5e1560e981, I performed `git pull` and ran `./gradlew clean build` again without any complaints from Spotless.

I am therefore closing this issue.

@PeterWippermann, it would be great if you could confirm that the last two commits solve your issues on Windows.

Cheers,

Sam

**Closed by sbrannen** 2016-07-15 14:06 UTC
Labels: bug, build, in progress

**Comment by PeterWippermann** [comment] 2016-07-15 16:00
@sbrannen I can happily confirm that it's working now! 
`clean check` `clean test` `clean build` pass without any errors. :+1:

I'm glad to have been the first beta tester on Windows :-D

**Comment by sbrannen** [comment] 2016-07-15 16:17
@PeterWippermann, thanks for confirming that the build works now!

> I'm glad to have been the first beta tester on Windows

Yeah... It does in fact appear you were the first beta tester on Windows. 😉

**Comment by marcphilipp** [comment] 2016-07-16 13:58
@PeterWippermann We now have an additional CI build that runs on Windows, see https://github.com/junit-team/junit5/issues/403#issuecomment-233131456.
