### ISSUE TITLE
Introduce variant of Assertions.fail() without arguments

### ISSUE THREAD

**Issue by MattiasWrang** [junit-team/junit5#1333] opened 2018-03-18 08:37 UTC
## Overview

`org.junit.jupiter.api.Assertions.fail` variants currently require arguments. If you simply want to fail the test and think an explanation is not not needed since it's clear from the test structure, a simple `fail()` without parameters would be nice.

## Analysis

I work on a commercial project that uses JUnit 4 and we would like to upgrade to JUnit 5. We have a large amount of existing tests, and many of them use `fail()`. By far the most common usage is the version without parameters: http://junit.sourceforge.net/javadoc_40/org/junit/Assert.html#fail()

It would be nice if this method was provided in JUnit Jupiter as well. If it was not provided, what would happen is that we would simply go and replace all usages of `fail()` with `fail("")`, which wouldn't really improve readability. I can understand if the parameter-less version was not included to force you to write a message, but if it's not required, it would be good to have an option without it.

## Deliverables

- Introduce `Assertions.fail()` method without parameters

**Comment by marcphilipp** [comment] 2018-03-18 09:19
Makes sense to me.

@junit-team/junit-lambda Any objections?

**Comment by sbrannen** [comment] 2018-03-18 17:53
> If it was not provided, what would happen is that we would simply go and replace all usages of `fail()` with `fail("")`

Actually, `fail(null)` would be the appropriate substitute.

**Comment by sbrannen** [comment] 2018-03-18 17:58
> I can understand if the parameter-less version was not included to force you to write a message

That's correct: I intentionally left it out in order to _encourage_ developers to provide either a custom failure message or an exception as the cause of the failure.

I say "enourage" instead of "force", because one could easily create his or her own `void static fail()` method that simply delegates to `Assertions.fail(null)`.

The reason I highly encourage this is that I have seen numerous projects where a simple invocation of `org.junit.Assert.fail()` did not make it clear what the reason was when viewing failures in a build report (e.g., on a CI server).

The same rationale applies to why we retroactively added meaningful error messages for invocations of `assertTrue(false)` and `assertFalse(true)` in JUnit Jupiter even though JUnit 4 did not do that.

**Comment by sbrannen** [comment] 2018-03-18 18:00
> @junit-team/junit-lambda Any objections?

Well... I am (obviously?) not really in favor of it.

But... if the rest of the team wishes to add it, I suppose I wouldn't outright object it. 😇

**Comment by marcphilipp** [comment] 2018-03-20 15:53
Hmm, after giving this some more thought I agree with Sam. `fail(null)` seems an easy enough workaround and looks ugly as it's supposed to... 😉

**Comment by sormuras** [comment] 2018-03-20 16:44
> Hmm, after giving this some more thought I agree with Sam. fail(null) seems an easy enough workaround and looks ugly as it's supposed to...

That's almost the reasoning we came to just before 5.0 GA, iirc.

`fail()` without reason is like `catch(Exception e) { throw new RuntimeException(e); }`

**Comment by sbrannen** [comment] 2018-03-20 17:22
FWIW, the team applied the same rationale (for not supporting `fail()`) for not having default constructors for `JUnitException`, `PreconditionViolationException`, etc.

In other words, we do our best to promote best practices in the APIs we publish.

**Comment by mmerdes** [comment] 2018-03-20 21:09
Apart from the maintenance arguments above omitting the argument can be seen as a deliberate choice on the test author"s side. The desired intent could be expressed in other ways, e.g. short tests with long names if someone wishes so...

**Comment by MattiasWrang** [comment] 2018-03-20 22:04
Thanks for the input for everyone. I just have a few comments:

> one could easily create his or her own static void fail() method that simply delegates to Assertions.fail(null)

This is actually not that easy in our case, because we have about 70 Maven modules. It's significantly easier to just have each of the modules depend on JUnit, rather than having all of them depend on JUnit as well as our additional new test helper module that only provides a wrapper around fail(null). It would mean a new dependency in each pom file simply for this, that people would need to understand why it's there, instead of having a simple dependency on JUnit.

> The reason I highly encourage this is that I have seen numerous projects where a simple invocation of org.junit.Assert.fail() did not make it clear what the reason was when viewing failures in a build report (e.g., on a CI server).

But if you always run your tests on your machine before pushing your changes and almost never have build server failures (we do) then getting to know which test failed and why it failed is enough. If it's not clearly promoting a bad practice, can't you be given the choice to use it?

> fail() without reason is like catch(Exception e) { throw new RuntimeException(e); }

The first is a way to abort a test if something unexpected happened, the second is a way to work around the mistake of adding checked exceptions to Java :) Can you explain how they are related?

----------------------------------------------------

Finally, I would like to elaborate on the point of migrating from JUnit 4 to JUnit 5 in my original comment:

An upgrade is not very straightforward for a larger project. You have to replace all imports, replacing annotations as well as replacing any assertion where you have a message, since they've been reordered. This is especially hard where strings were being compared, because we wouldn't get a compile error. However, I can see that these changes are being justified for better readability. However, having to replace fail() with fail(null) everywhere where it's used wouldn't lead to better readability and would be seen as a downgrade. We are just regular users of JUnit and don't use any advanced features:. assertThrows is the main reason that we would like to upgrade, but we don't see any other real features that would be attractive for us yet, therefore something like this would be quite important before a potential upgrade.

**Comment by sbrannen** [comment] 2018-03-21 10:33
Thanks for taking the time to provide additional input, @MattiasWrang.

We will discuss it amongst the team and hopefully come to  conclusion by the end of the week.

**Comment by sbrannen** [comment] 2018-03-21 10:33
Tentatively slated for 5.2 M1 for _team dicsussion_.

**Comment by smoyer64** [comment] 2018-03-21 11:38
>   An upgrade is not very straightforward for a larger project.

@boyarski wrote an [amazing JUnit 4 to JUnit 5 conversion tool](https://github.com/boyarsky/convert-junit4-to-junit5).  She's written [a blog post](https://www.selikoff.net/2017/09/02/converting-2k-tests-to-junit-5-in-one-day/) about its efficacy and what types of conversions it couldn't make on its own.  From our conversations at J1-2017, I'm also remembering that it was used on more than just CodeRanch tests.  I'll let her comment here so I don't get the details wrong and/or say anything that was supposed to be kept private.

Perhaps we should help publicize this project - at a minimum we can link to it from the users guide, website and pioneer.

**Comment by sbrannen** [comment] 2018-04-02 15:52
**Team Decision**: ntroduce `Assertions.fail()` method without parameters.

**Comment by mmerdes** [comment] 2018-04-05 09:55
in progress

**Comment by sbrannen** [comment] 2018-04-06 14:32
FYI: with the upcoming fix in the OTA (https://github.com/ota4j-team/opentest4j/issues/42), the new `fail()` method should simply `throw new AssertionFailedError()`.

**Comment by mmerdes** [comment] 2018-04-11 10:47
Merged PR.

**Closed by mmerdes** 2018-04-11 10:47 UTC
Labels: component: Jupiter, status: in progress, theme: programming model, type: enhancement
