### ISSUE TITLE
Combine annotations `Source` annotations to create cartesian product

### ISSUE THREAD

**Issue by throwable-one** [junit-team/junit5#3861] opened 2024-06-14 16:32 UTC
There is no easy and clean way to implement something like 
```

enum class OS {
    Windows,
    Linux
}

enum class Arch {
    X86_64,
    AA64
}


class MyTest {

    @ParameterizedTest
    @EnumSource(OS::class)
    @EnumSource(Arch::class)
    fun myTest(os:OS, arch: Arch) {

    }
}
```

**Comment by jbduncan** [comment] 2024-06-14 18:35
Hi @throwable-one - I believe this is a duplicate of https://github.com/junit-team/junit5/issues/3063, which was closed, sadly.

I'm not aware of any plans from the JUnit team, but I believe [junit-pioneer](https://junit-pioneer.org/docs/cartesian-product/) (which is unofficially endorsed by the JUnit team) and [github.com/google/TestParameterInjector](https://github.com/google/TestParameterInjector) do exactly what you're looking for. 

I hope this helps!

**Comment by marcphilipp** [comment] 2024-06-15 11:01
Duplicate of #3063

**Closed by marcphilipp** 2024-06-15 11:01 UTC
Labels: status: new
