### ISSUE TITLE
Provide support for setting a custom parent directory for `@TempDir`

### ISSUE THREAD

**Issue by rkrisztian** [junit-team/junit5#2088] opened 2019-10-29 18:38 UTC
My project requires that I do not write to `/tmp` or whichever location it is when I use the [`TempDirectory` extension](https://junit.org/junit5/docs/current/user-guide/#writing-tests-built-in-extensions-TempDirectory). So right now I have no choice but to still use [`junit-pioneer`'s implementation](https://junit-pioneer.org/docs/temp-directory/), e.g. like this:

 ```java
@RegisterExtension
Extension tempDirectory = TempDirectory.createInCustomDirectory(() -> Paths.get("build"));
 
@BeforeEach
void setup(@TempDir Path testProjectDir) {
    // Do something with "testProjectDir".
}
```

But it would be nicer if I could just use stock JUnit 5 for this. JUnit 4 supported setting the parent dir, so I find the JUnit 5 way a bit too limiting.

Thanks in advance.

**Comment by sbrannen** [comment] 2019-10-29 20:38
Tentatively slated for 5.6 M2 solely for the purpose of _team discussion_

**Comment by marcphilipp** [comment] 2019-10-31 11:25
If your project requires you not to write to the default location of temporary files, you should set the `java.io.tmpdir` system property.

@rkrisztian Could you please try that?

**Comment by rkrisztian** [comment] 2019-11-01 11:44
Worked, thanks! I wish I knew about this. :)

**Comment by sbrannen** [comment] 2019-11-01 12:05
Assigned to the general backlog and labeled as waiting for interest.

**Comment by rkrisztian** [comment] 2020-01-14 07:53
FYI: A co-worker of mine suggested the use of `AbstractTask#getTemporaryDir()`:

```groovy
tasks.withType(Test) {
  systemProperty 'java.io.tmpdir', temporaryDir
}
```

**Comment by dariocutillas** [comment] 2020-08-13 15:24
I'm also interested in this functionality.

In my case I only want to affect the parent directory of one `@TempDir` and therefore it does not make sense to use `java.io.tmpdir`.

**Comment by bes1002t** [comment] 2022-01-25 21:31
in my case junit always set it tempDir to the working directory of the project. This is annoying because it always generates a mess into my source code directories.

Additionally this mess is not deleted after the tests were executed. I mean in this case this is good, because I don't want my source code directories to be deleted. Do you think I forget to configure something, or is this function as intended?

**Comment by sbrannen** [comment] 2022-01-26 11:03
@bes1002t, are you using the `@TempDir` support in JUnit Jupiter?

If so, then the behavior you are describing sounds like a bug, and we would appreciate it if you would open a separate issue describing your setup and providing a failing example.

**Comment by bes1002t** [comment] 2022-04-25 22:13
@sbrannen yes I'm using JUnit 5:

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.8.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>5.8.2</version>
            <scope>test</scope>
        </dependency>


If you don't see an issue here with my dependency declaration, I could create a new ticket with further explanation. :)

**Comment by AdrienHorgnies** [comment] 2022-07-25 15:33
I'm setting the property using the command line of Maven `-Djava.io.tmpdir=/tmp/parentdir/` and `@TmpDir` doesn't honor the property.

I have a test where I inject the temporary directory by annotating a parameter with `@TempDir` and the parent of this parameter is not `System.getProperty("java.io.tmpdir")`. Instead, the parent is `/tmp`.

I'm surprised, as it seems the advice @marcphilipp gave should apply to my project. Or did I understand it incorrectly ?

I'm using JUnit 5.8.2, obviously.

**Comment by sbrannen** [comment] 2022-07-27 12:35
> in my case junit always set it tempDir to the working directory of the project. This is annoying because it always generates a mess into my source code directories.

@bes1002t, it sounds like something else is setting the temp dir system property.

What is the output of `System.out.println(System.getProperty("java.io.tmpdir"))` in your tests?

If it's the project's working directory, you'll need to figure out what is setting the `java.io.tmpdir` JVM system property to that.

**Closed** 2023-04-26 07:39 UTC
Labels: type: enhancement, theme: extensions, theme: programming model, component: Jupiter
