### ISSUE TITLE
[junit-platform] Add interrupt/cancellation support

### ISSUE THREAD

**Issue by kriegfrj** [junit-team/junit5#2462] opened 2020-10-26 02:21 UTC
As part of the Bndtools project we've been working on an interactive OSGi testing environment based on JUnit Platform. It supports hot re-deployment of code (both application code and test code) and re-running of the tests without having to restart the framework. This is extremely useful for speeding up the development cycle for integration tests of code in the framework when that framework has a long startup time. It makes the Test-Driven Development cycle much more feasible and efficient.

While it is clear that JUnit was not originally designed with interactivity in mind, nevertheless it seems to work pretty well for the most part. But there is one major feature missing from JUnit Platform that would make it work even better, and that's the lack of a reliable cancellation mechanism - once the launcher has started executing a `TestPlan`, there is no reliable way to stop it. In an interactive scenario, I have often found that I start a new test run only to notice that the tests all start failing due to some bug I introduced. I find and fix the bug, but then I still have to wait a minute or so for the test plan to finish executing before I can run the tests again. Alternatively, I have to terminate the container and restart it (which is usually even slower). What I would really like is to be able to cancel the test run once I notice the first few failures so that I don't have to wait before restarting it with the fix included.

It seems to me that this would not be a difficult feature to add, although it probably couldn't be implemented in the platform alone - it would need each individual engine to support it too. As a quick idea:

* `Launcher.execute()` will require an asynchronous variant that returns an object representing the current execution (`LauncherExecutionHandle`, perhaps). This interface implemented by this object would contain (among possible other things) a `cancel()` method.
* `TestEngine` will likewise require an asynchronous variant that returns an object representing the current engine execution (`EngineExecutionHandle`). This too would contain a `cancel()` method.
* It is possible that the execution handles could simply extend or contain a `Future` to facilitate this.

An alternative is to assume that a `Launcher` and a `TestEngine` can only have one concurrent execution, and simply add the `cancel()` method to these interfaces.

Thoughts?

**Comment by marcphilipp** [comment] 2020-10-26 06:46
Thanks for raising the issue! We already brainstormed similar ideas in https://github.com/junit-team/junit5/issues/1880#issuecomment-575120923

**Comment by marcphilipp** [comment] 2020-10-26 06:46
Duplicate of #1880

**Closed by marcphilipp** 2020-10-26 06:46 UTC

**Comment by kriegfrj** [comment] 2020-10-26 13:36
So sorry! I searched for "interrupt" and "cancel", but not "stop"! :smile: Glad to see similar solutions being proposed in the other issue.

**Comment by marcphilipp** [comment] 2020-10-26 13:37
No problem at all! I struggle finding issues all the time. 😉
