### ISSUE TITLE
Could you please reconsider the addition of `@RangeSource`?

### ISSUE THREAD

**Issue by k163377** [junit-team/junit5#3946] opened 2024-09-07 13:31 UTC
I have a heavy test for a very large range and am trying to parallelize this.

In doing so, I have noticed that if I use a `@MethodSource`, it will not be parallelized.

If this is a limitation due to circumstances specific to `@MethodSource`, could we introduce a `@RangeSource`?

In my layman's opinion, I think it would be easier to implement since the internal processing can be done in the same way as a `@ValueSource`.

Also, I feel that `@MethodSource` is a bit difficult to use in several ways, so I would like a `@RangeSource` in that sense.

I realize that this is a feature that has already been denied once with #851, but could you please consider it again?

**Comment by sbrannen** [comment] 2024-09-07 14:54
> Also, I feel that `MethodSource` is a bit difficult to use in several ways, so I would like a `RangeSource` in that sense.

How about using a `@FieldSource`?

```java
class RangeTests {

	@ParameterizedTest
	@FieldSource("range")
	void testWithRangeFieldSource(int argument) {
		assertTrue(argument >= 110 && argument <= 200);
	}

	static Supplier<IntStream> range = () -> IntStream.rangeClosed(100, 200).skip(10);

}
```

I find that rather compelling and straightforward.

Thoughts?

**Comment by k163377** [comment] 2024-09-07 15:41
> Have you tried JUnit Pioneer's support for [Range Sources](https://junit-pioneer.org/docs/range-sources/)?

Sorry, I had missed this.
This is exactly what I was looking for, thank you.

> How about using a @FieldSource?

Sorry, I missed this as well.
If it can run concurrently, this would be useful for my use case.

> Thoughts?

I've made the point a bit vague, but I think the problem remains that the `MethodSource` is not executed concurrently.
However, is this a duplication of #3373?
If so, I will close it.

**Comment by sbrannen** [comment] 2024-09-08 11:42
Thanks for the feedback, @k163377.

> > Have you tried JUnit Pioneer's support for [Range Sources](https://junit-pioneer.org/docs/range-sources/)?
> 
> Sorry, I had missed this. This is exactly what I was looking for, thank you.

👍 

> > How about using a @FieldSource?
> 
> Sorry, I missed this as well.

No worries. It's "new" since JUnit Jupiter 5.11 which was just recently released.

> I've made the point a bit vague, but I think the problem remains that the `MethodSource` is not executed concurrently.

I don't think there's anything particular about `@MethodSource` with regards to parallel execution: every `ArgumentsProvider` for a parameterized test ends up producing a `Stream` of `Arguments`.

> However, is this a duplication of #3373? If so, I will close it.

Indeed, I am closing this as a duplicate of the following.

- #851
- #3373

**Closed by sbrannen** 2024-09-08 11:42 UTC
Labels: type: enhancement, component: Jupiter, theme: parameterized tests, status: new
