### ISSUE TITLE
Overloaded assertions fail for Kotlin

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1859] opened 2019-04-11 16:17 UTC
As described in https://github.com/junit-team/junit5/issues/1710#issuecomment-482147200 the following snippet

```kotlin
assertEquals(2, jsonValidator.getList("actions")?.size)
```

produces an error at runtime:

```
java.lang.NoSuchMethodError: org.junit.jupiter.api.Assertions.assertEquals(ILjava/lang/Integer;)V
	at org.projectforge.rest.json.JsonValidatorTest.parseJson(JsonValidatorTest.kt:27)
```

Not sure whether this is an issue with Jupiter's overloads or it's bug in Kotlin.

@JLLeitschuh -- any idea?

**Comment by sormuras** [comment] 2019-04-11 16:20
Blind guess: `I` is the `int` primitive generated for `2` and `Ljava/lang/Integer;` is the return type from `Collection::size()`. Right?

**Comment by sbrannen** [comment] 2019-04-11 16:44
I'm not positive, but `org.junit.jupiter.api.Assertions.assertEquals(ILjava/lang/Integer;)V` does not appear to be valid for the description of a method in Java byte code, but perhaps that's coming from something in Kotlin.

Do we have a complete stack trace?

**Comment by sbrannen** [comment] 2019-04-11 16:44
I'm not positive, but `org.junit.jupiter.api.Assertions.assertEquals(ILjava/lang/Integer;)V` does not appear to be valid for the description of a method in Java byte code, but perhaps that's coming from something in Kotlin.

Do we have a complete stack trace?

**Comment by JLLeitschuh** [comment] 2019-04-11 20:59
Any idea what the compiled bytecode for that file actually looks like once compiled? Sounds like possibly a bug in the compiler?

What version of the compiler is being used?

How many overloads for `assertEquals` currently exist?

What version of Junit5 is being used?

**Comment by sormuras** [comment] 2019-04-12 06:08
> What version of the compiler is being used?

`javac` 1.8 for the "main" code, `kotlinc` 1.3.21 for "test" code ... used via the Maven Plugin here:

https://github.com/micromata/projectforge/blob/PROJECTFORGE-3614-ReactJS/projectforge-jax-rs/pom.xml#L25-L51

> How many overloads for assertEquals currently exist?
> What version of Jupiter is being used?

Due to SpringBoot being involved, the version of Jupiter is 5.3.2 -- and here are like 30 overloads of `assertEquals`: https://github.com/junit-team/junit5/blob/releases/5.3.x/junit-jupiter-api/src/main/java/org/junit/jupiter/api/Assertions.java

> Is there a minimal reproduction?

No. Not, yet. Might create one later... attending a Kotlin workshop today.

**Comment by sormuras** [comment] 2019-04-12 06:41
The following **works** like a charm:

```kotlin
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

class KotlinAssertionsOverloadsTests {
    @Test
    fun `junit5 issues 1859()`() {
        assertEquals(0, 0)
        assertEquals(1, listOf("a").size)
        assertEquals(2, listOrNull()?.size)
    }

    private fun listOrNull(): List<*>? {
        return arrayListOf("a", "b")
    }
}
```

Perhaps the implementation of [`jsonValidator.getList("actions")`](https://github.com/micromata/projectforge/blob/PROJECTFORGE-3614-ReactJS/projectforge-jax-rs/src/main/kotlin/org/projectforge/rest/json/JsonValidator.kt#L48) (using `Any?` internally in `getElement(path: String)`) erases too much type information? /cc @kreinhard

**Comment by marcphilipp** [comment] 2019-04-12 10:15
I think we should definitely get in touch with JetBrains because if it compiles and doesn't find the method at runtime that doesn't right to me.

@sormuras Can you try to create a minimal example and open an issue for Kotlin?

**Comment by JLLeitschuh** [comment] 2019-04-12 13:23
@sormuras 

Looks like the closest recreation might be something like this:

```kotlin
val testList : List<*>? = listOf("a")

assertEquals(1, testList?.size)
```
Another valid test might be:
```kotlin
val testList : List<*>? = null

assertEquals(1, testList?.size)
```

The second one should fail, but not with a `NoSuchMethodError`.

**Comment by sormuras** [comment] 2019-04-12 16:49
Works for me...

```kotlin
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.Test

class KotlinAssertionsOverloadsTests {
    @Test
    fun `junit5 issues 1859`() {
        assertEquals(0, 0)
        assertEquals(1, listOf("a").size)
        assertEquals(2, listOrNull()?.size)

        val listWithAnElement : List<*>? = listOf("a")
        assertEquals(1, listWithAnElement?.size)

        val nullableList : List<*>? = null
        assertEquals(null, nullableList?.size)
    }

    private fun listOrNull(): List<*>? {
        return arrayListOf("a", "b")
    }
}
```

**Comment by marcphilipp** [comment] 2019-04-12 16:55
@sormuras Have you tried with `Any?`?

**Comment by sormuras** [comment] 2019-04-12 16:59
`Any` has no `size`.

Tried it with:
```kotlin
    private fun listOrNull(): List<*>? {
        val result: Any? = arrayListOf("a", "b")
        return result as List<*>?
    }
```
...works, too.

**Comment by JLLeitschuh** [comment] 2019-04-12 17:57
@sormuras Can you upload the compiled `.class` file that the compiler produced?

**Comment by sormuras** [comment] 2019-04-12 18:05
Here you go.

[json.zip](https://github.com/junit-team/junit5/files/3074607/json.zip)

**Comment by sormuras** [comment] 2019-04-12 18:15
> Do we have a complete stack trace?

No. Don't get more lines, even with `-e` specified.

**Comment by JLLeitschuh** [comment] 2019-04-12 18:48
So, according to IJ, this is what this class decompiles to as Java code:

```java
@Metadata(
   mv = {1, 1, 13},
   bv = {1, 0, 3},
   k = 1,
   d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0000\u0018\u00002\u00020\u0001B\u0005¢\u0006\u0002\u0010\u0002J\b\u0010\u0003\u001a\u00020\u0004H\u0007¨\u0006\u0005"},
   d2 = {"Lorg/projectforge/rest/json/JsonValidatorTest;", "", "()V", "parseJson", "", "projectforge-jax-rs"}
)
public final class JsonValidatorTest {
   @Test
   public final void parseJson() {
      final JsonValidator jsonValidator = new JsonValidator("{'fruit1':'apple','fruit2':'orange','basket':{'fruit3':'cherry','fruit4':'banana'},'actions':[{'id':'cancel','title':'Abbrechen','style':'danger','type':'button','key':'el-20'},{'id':'create','title':'Anlegen','style':'primary','type':'button','key':'el-21'}]}");
      Assertions.assertEquals("apple", jsonValidator.get("fruit1"));
      Assertions.assertEquals("orange", jsonValidator.get("fruit2"));
      Assertions.assertEquals("cherry", jsonValidator.get("basket.fruit3"));
      Assertions.assertNull(jsonValidator.get("fruit3"));
      Assertions.assertNull(jsonValidator.get("basket.fruit1"));
      IllegalArgumentException ex = (IllegalArgumentException)Assertions.assertThrows(IllegalArgumentException.class, (Executable)(new Executable() {
         public final void execute() {
            jsonValidator.get("basket.unknown.fruit1");
         }
      }));
      Assertions.assertEquals("Can't step so deep: 'basket.unknown.fruit1'. 'fruit1' doesn't exist.", ex.getMessage());
      Assertions.assertNull(jsonValidator.get("basket.unknown"));
      Assertions.assertEquals("cancel", jsonValidator.get("actions[0].id"));
      Assertions.assertEquals("Anlegen", jsonValidator.get("actions[1].title"));
      List var10001 = jsonValidator.getList("actions");
      Assertions.assertEquals(2, var10001 != null ? var10001.size() : null);
      ex = (IllegalArgumentException)Assertions.assertThrows(IllegalArgumentException.class, (Executable)(new Executable() {
         public final void execute() {
            jsonValidator.get("actions.id");
         }
      }));
      Assertions.assertEquals("Can't step so deep: 'actions.id'. 'id' doesn't exist.", ex.getMessage());
      Assertions.assertEquals("cancel", jsonValidator.get("actions[0].id"));
   }
}
```

The part we are concerned with is:
```java
List var10001 = jsonValidator.getList("actions");
Assertions.assertEquals(2, var10001 != null ? var10001.size() : null);
```

```
javap -c JsonValidatorTest.class
Compiled from "JsonValidatorTest.kt"
public final class org.projectforge.rest.json.JsonValidatorTest {
  public final void parseJson();
    Code:
       0: new           #9                  // class org/projectforge/rest/json/JsonValidator
       3: dup
       4: ldc           #11                 // String {'fruit1':'apple','fruit2':'orange','basket':{'fruit3':'cherry','fruit4':'banana'},'actions':[{'id':'cancel','title':'Abbrechen','style':'danger','type':'button','key':'el-20'},{'id':'create','title':'Anlegen','style':'primary','type':'button','key':'el-21'}]}
       6: invokespecial #15                 // Method org/projectforge/rest/json/JsonValidator."<init>":(Ljava/lang/String;)V
       9: astore_1
      10: ldc           #17                 // String apple
      12: aload_1
      13: ldc           #19                 // String fruit1
      15: invokevirtual #23                 // Method org/projectforge/rest/json/JsonValidator.get:(Ljava/lang/String;)Ljava/lang/String;
      18: invokestatic  #29                 // Method org/junit/jupiter/api/Assertions.assertEquals:(Ljava/lang/Object;Ljava/lang/Object;)V
      21: ldc           #31                 // String orange
      23: aload_1
      24: ldc           #33                 // String fruit2
      26: invokevirtual #23                 // Method org/projectforge/rest/json/JsonValidator.get:(Ljava/lang/String;)Ljava/lang/String;
      29: invokestatic  #29                 // Method org/junit/jupiter/api/Assertions.assertEquals:(Ljava/lang/Object;Ljava/lang/Object;)V
      32: ldc           #35                 // String cherry
      34: aload_1
      35: ldc           #37                 // String basket.fruit3
      37: invokevirtual #23                 // Method org/projectforge/rest/json/JsonValidator.get:(Ljava/lang/String;)Ljava/lang/String;
      40: invokestatic  #29                 // Method org/junit/jupiter/api/Assertions.assertEquals:(Ljava/lang/Object;Ljava/lang/Object;)V
      43: aload_1
      44: ldc           #39                 // String fruit3
      46: invokevirtual #23                 // Method org/projectforge/rest/json/JsonValidator.get:(Ljava/lang/String;)Ljava/lang/String;
      49: invokestatic  #43                 // Method org/junit/jupiter/api/Assertions.assertNull:(Ljava/lang/Object;)V
      52: aload_1
      53: ldc           #45                 // String basket.fruit1
      55: invokevirtual #23                 // Method org/projectforge/rest/json/JsonValidator.get:(Ljava/lang/String;)Ljava/lang/String;
      58: invokestatic  #43                 // Method org/junit/jupiter/api/Assertions.assertNull:(Ljava/lang/Object;)V
      61: ldc           #47                 // class java/lang/IllegalArgumentException
      63: new           #49                 // class org/projectforge/rest/json/JsonValidatorTest$parseJson$ex$1
      66: dup
      67: aload_1
      68: invokespecial #52                 // Method org/projectforge/rest/json/JsonValidatorTest$parseJson$ex$1."<init>":(Lorg/projectforge/rest/json/JsonValidator;)V
      71: checkcast     #54                 // class org/junit/jupiter/api/function/Executable
      74: invokestatic  #58                 // Method org/junit/jupiter/api/Assertions.assertThrows:(Ljava/lang/Class;Lorg/junit/jupiter/api/function/Executable;)Ljava/lang/Throwable;
      77: checkcast     #47                 // class java/lang/IllegalArgumentException
      80: astore_2
      81: ldc           #60                 // String Can't step so deep: 'basket.unknown.fruit1'. 'fruit1' doesn't exist.
      83: aload_2
      84: invokevirtual #64                 // Method java/lang/IllegalArgumentException.getMessage:()Ljava/lang/String;
      87: invokestatic  #29                 // Method org/junit/jupiter/api/Assertions.assertEquals:(Ljava/lang/Object;Ljava/lang/Object;)V
      90: aload_1
      91: ldc           #66                 // String basket.unknown
      93: invokevirtual #23                 // Method org/projectforge/rest/json/JsonValidator.get:(Ljava/lang/String;)Ljava/lang/String;
      96: invokestatic  #43                 // Method org/junit/jupiter/api/Assertions.assertNull:(Ljava/lang/Object;)V
      99: ldc           #68                 // String cancel
     101: aload_1
     102: ldc           #70                 // String actions[0].id
     104: invokevirtual #23                 // Method org/projectforge/rest/json/JsonValidator.get:(Ljava/lang/String;)Ljava/lang/String;
     107: invokestatic  #29                 // Method org/junit/jupiter/api/Assertions.assertEquals:(Ljava/lang/Object;Ljava/lang/Object;)V
     110: ldc           #72                 // String Anlegen
     112: aload_1
     113: ldc           #74                 // String actions[1].title
     115: invokevirtual #23                 // Method org/projectforge/rest/json/JsonValidator.get:(Ljava/lang/String;)Ljava/lang/String;
     118: invokestatic  #29                 // Method org/junit/jupiter/api/Assertions.assertEquals:(Ljava/lang/Object;Ljava/lang/Object;)V
     121: iconst_2
     122: aload_1
     123: ldc           #76                 // String actions
     125: invokevirtual #80                 // Method org/projectforge/rest/json/JsonValidator.getList:(Ljava/lang/String;)Ljava/util/List;
     128: dup
     129: ifnull        143
     132: invokeinterface #86,  1           // InterfaceMethod java/util/List.size:()I
     137: invokestatic  #92                 // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
     140: goto          145
     143: pop
     144: aconst_null
     145: invokestatic  #95                 // Method org/junit/jupiter/api/Assertions.assertEquals:(ILjava/lang/Integer;)V
     148: ldc           #47                 // class java/lang/IllegalArgumentException
     150: new           #97                 // class org/projectforge/rest/json/JsonValidatorTest$parseJson$1
     153: dup
     154: aload_1
     155: invokespecial #98                 // Method org/projectforge/rest/json/JsonValidatorTest$parseJson$1."<init>":(Lorg/projectforge/rest/json/JsonValidator;)V
     158: checkcast     #54                 // class org/junit/jupiter/api/function/Executable
     161: invokestatic  #58                 // Method org/junit/jupiter/api/Assertions.assertThrows:(Ljava/lang/Class;Lorg/junit/jupiter/api/function/Executable;)Ljava/lang/Throwable;
     164: checkcast     #47                 // class java/lang/IllegalArgumentException
     167: astore_2
     168: ldc           #100                // String Can't step so deep: 'actions.id'. 'id' doesn't exist.
     170: aload_2
     171: invokevirtual #64                 // Method java/lang/IllegalArgumentException.getMessage:()Ljava/lang/String;
     174: invokestatic  #29                 // Method org/junit/jupiter/api/Assertions.assertEquals:(Ljava/lang/Object;Ljava/lang/Object;)V
     177: ldc           #68                 // String cancel
     179: aload_1
     180: ldc           #70                 // String actions[0].id
     182: invokevirtual #23                 // Method org/projectforge/rest/json/JsonValidator.get:(Ljava/lang/String;)Ljava/lang/String;
     185: invokestatic  #29                 // Method org/junit/jupiter/api/Assertions.assertEquals:(Ljava/lang/Object;Ljava/lang/Object;)V
     188: return

  public org.projectforge.rest.json.JsonValidatorTest();
    Code:
       0: aload_0
       1: invokespecial #108                // Method java/lang/Object."<init>":()V
       4: return
}
```

In particular, this line here:
```
     121: iconst_2
     122: aload_1
     123: ldc           #76                 // String actions
     125: invokevirtual #80                 // Method org/projectforge/rest/json/JsonValidator.getList:(Ljava/lang/String;)Ljava/util/List;
     128: dup
     129: ifnull        143
     132: invokeinterface #86,  1           // InterfaceMethod java/util/List.size:()I
     137: invokestatic  #92                 // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
     140: goto          145
     143: pop
     144: aconst_null
     145: invokestatic  #95                 // Method org/junit/jupiter/api/Assertions.assertEquals:(ILjava/lang/Integer;)V
```

I'm not all that good at reading Java bytecode, but this looks like the invalid call generated by the compiler.

**Comment by marcphilipp** [comment] 2019-04-13 11:09
@JLLeitschuh Thanks for the detailed analysis! Would you be interested in submitting a bug report to Kotlin?

**Comment by JLLeitschuh** [comment] 2019-04-15 02:30
@marcphilipp Uhhh. I still haven't figured out the root cause. I can certainly submit something though.

**Comment by JLLeitschuh** [comment] 2019-04-15 15:35
@sormuras If you can provide the minimal reproducible example of this demo as a project, that would be appreciated.
I don't have the time to create the example, so my current other option is to just point them to the entire project.

**Comment by sormuras** [comment] 2019-04-15 16:15
I tried hard to "deflate" it into a smaller example, to no avail. But I can reproduce it from the linked branch/commit. Maybe it's related to the Maven Plugin setup?

**Comment by JLLeitschuh** [comment] 2019-04-15 16:22
@sormuras, in this Kotlin Slack, Dmitry Savvinov suggested it might be caused by classpath-hell.

https://kotlinlang.slack.com/archives/C7L3JB43G/p1555095135001800

Are you able to reproduce it if you reduce the number of dependencies and extract that one file and its direct dependencies into their own project?

**Comment by JLLeitschuh** [comment] 2019-04-15 16:25
CC: @dsavvinov

**Comment by dsavvinov** [comment] 2019-04-15 16:32
Hi, folks

First of all, let me copy my message to @JLLeitschuh from Kotlinlang Slack:

```
I wasn’t able to deep dive into details, but a few notes:
- such JVM signature is valid and denotes a method with signature like `void assertEquals(int, Integer)`
- such method actually exists in `junit-jupiter-api-5.4.1`, but doesn’t in `junit-jupiter-api-5.3.2`
- hence I would re-check compile/runtime classpaths in build where such exception arises
```

That being said, it's absolutely fine to report an issue without minimal repro if you haven't managed to minimize the example; we will try to do it on our own.

**Comment by marcphilipp** [comment] 2019-04-15 16:47
@JLLeitschuh @dsavvinov Thanks for chiming in! 👍 

Judging by the comment in https://github.com/junit-team/junit5/issues/1710#issuecomment-482448767 and knowing that it's a Spring boot project "classpath hell" sounds rather likely. I'm therefore closing this issue as the originally reported problem was solved. Feel free to comment or reopen should it appear again.

**Closed by marcphilipp** 2019-04-15 16:47 UTC
Labels: component: Jupiter, type: bug
