### ISSUE TITLE
Support  randomizing test class order

### ISSUE THREAD

**Issue by atorok** [junit-team/junit5#1619] opened 2018-10-04 18:51 UTC
## Overview

#13 Implements support for random method order, but does not address class ordering. 
The benefits of pseudo random testing are described here: https://github.com/randomizedtesting/randomizedtesting/wiki/Core-Concepts
The framework is extensively used for Apache Lucene and Elasticsearch.

## Deliverables

- [ ] A  mechanism to control how classes are ordered, similar to what we have for methods. I'm not sure what the best way to implement it would be, as I imagine it couldn't be a similar annotation.

**Comment by VladRassokhin** [comment] 2018-10-05 23:01
Sorry for noise and duplication, though I'll just quote my comment from #13 with minor edit for reasons on especially classes reordering, not methods reordering:

>From CI (or Build Tool) perspective test classes reordering during tests invocation is extremely useful to run previously failed tests (classes) first to get feedback earlier.

**Comment by pauldingemans** [comment] 2020-02-11 19:54
Am I wright to assume that you want to be able to:
* Run classes in a stable order (e.g. alphabetically or based on a hash of a classname). What orders would be useful in which case?
* Run classes in a random order based on a seed which is reported back so that the cyclus van be repeated when specifying the exact same seed. 
* Run classes which had errors in last run before classes which ran successful.

For each of above the follow-up questions are:
* How would you expect to trigger a specific execution mode? Would that be in code or configuration?
* Will it work in command line only or is IDE integration also possible?

Note: I am not a committer on JUnit but just trying to help to get clear specifications.

**Comment by marcphilipp** [comment] 2020-02-13 11:07
Duplicate of #1948

**Closed by marcphilipp** 2020-02-13 11:07 UTC
