### ISSUE TITLE
Allow customization of parameterized test argument names

### ISSUE THREAD

**Issue by asarkar** [junit-team/junit5#2378] opened 2020-08-11 08:03 UTC
I've a parameterized test that receives a parameter of type [kotlin.reflect.KFunction](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect/-k-function/). For each execution of this test, I'd like to show the simple name of the `KFunction`, not the FQN that currently shoots out of the screen. I've seen the discussion in https://github.com/junit-team/junit5/issues/2301 and https://github.com/junit-team/junit5/issues/2375, but not clear how the `Named` solution proposed there would help my case. If I could get hold of the actual argument passed to the test method, then I could get the simple name out very easily. I think this problem holds for a Java `Method` too, so Kotlin or `KFunction` isn't the use issue.

**Comment by sbrannen** [comment] 2020-08-11 08:35
Closing as a duplicate of #1154

**Closed by sbrannen** 2020-08-11 08:35 UTC

**Comment by asarkar** [comment] 2020-08-11 09:12
@sbrannen Looks like https://github.com/junit-team/junit5/issues/1154 is almost 3 years old and not going anywhere.

**Comment by sbrannen** [comment] 2020-08-11 09:26
> @sbrannen Looks like #1154 is almost 3 years old and not going anywhere.

The origin is old, but the **Team Decision** to implement it dates only back to June of this year: https://github.com/junit-team/junit5/issues/1154#issuecomment-639413373.
