### ISSUE TITLE
Allow non void BeforeEach methods to act as a parameter supplier

### ISSUE THREAD

**Issue by xenoterracide** [junit-team/junit5#1657] opened 2018-10-30 20:41 UTC
I have this test

```java
@DataJpaTest
@SpringJUnitConfig
@AutoConfigureTestDatabase( replace = AutoConfigureTestDatabase.Replace.NONE )
class EmrRepoTest {

    private final EmrRepo repo;
    private final LocalDateTime now = LocalDateTime.now();
    private final Duration duration = Duration.ofSeconds( 5 );

    @Autowired
    EmrRepoTest( EmrRepo repo ) {
        this.repo = repo;
    }

    Emr save;

    @BeforeEach
    void setup() {
        var entity = new Emr();
        entity.setMrn( "abc123" );
        entity.setDescription( "mydesc" );
        entity.setTimestamp( now.minus( duration ).plusSeconds( 2 ) );
        entity.setUnits( "mg" );
        entity.setValue( "25" );
        save = repo.save( entity );
    }

    @Test
    void save() {
        assertThat( save ).extracting( Persistable::getId ).hasSize( 1 ).doesNotContainNull();
    }

    @Test
    void findByTimestampIsAfter() {
        assertThat( repo.findByTimestampIsAfter( now.minus( duration ) ) ).containsExactly( save );
    }

}
```

I would prefer to write

```java
@DataJpaTest
@SpringJUnitConfig
@AutoConfigureTestDatabase( replace = AutoConfigureTestDatabase.Replace.NONE )
class EmrRepoTest {

    private final EmrRepo repo;
    private final LocalDateTime now = LocalDateTime.now();
    private final Duration duration = Duration.ofSeconds( 5 );

    @Autowired
    EmrRepoTest( EmrRepo repo ) {
        this.repo = repo;
    }

    @BeforeEach
    Emr setup() {
        var entity = new Emr();
        entity.setMrn( "abc123" );
        entity.setDescription( "mydesc" );
        entity.setTimestamp( now.minus( duration ).plusSeconds( 2 ) );
        entity.setUnits( "mg" );
        entity.setValue( "25" );
        return repo.save( entity );
    }

    @Test
    void save( Emr save ) {
        assertThat( save ).extracting( Persistable::getId ).hasSize( 1 ).doesNotContainNull();
    }

    @Test
    void findByTimestampIsAfter( Emr save ) {
        assertThat( repo.findByTimestampIsAfter( now.minus( duration ) ) ).containsExactly( save );
    }

}
```

## Related Issues

- #1513

**Comment by sbrannen** [comment] 2018-10-31 12:20
This is basically a duplicate of #1513.

As I stated in https://github.com/junit-team/junit5/issues/1513#issuecomment-409177652:

> As a general rule, we do not allow lifecycle callback methods to have a return value, and to be honest, I don't foresee us diverging from that rule.

Consequently, I imagine the response will be the same as in https://github.com/junit-team/junit5/issues/1513#issuecomment-410209628

@junit-team/junit-lambda, thoughts?

**Comment by sormuras** [comment] 2018-10-31 12:21
I'm with #1513

**Comment by sbrannen** [comment] 2018-10-31 12:28
> My recommendation in such cases is to make `Emr save` a `private final` field and initialize it in the constructor.

But since you're using `@DataJpaTest` which makes your tests `@Transactional`, you'll probably want to continue creating and saving your entity in a `@BeforeEach` method so that it is cleaned up when the test transaction is automatically rolled back by Spring. 😉

**Comment by xenoterracide** [comment] 2018-10-31 14:42
ooh, I forgot about #1513 :/ sorry

**Comment by sbrannen** [comment] 2018-10-31 14:59
> ooh, I forgot about #1513 :/ sorry

Well, _you_ authored #1513.

So maybe you were just slightly sleep deprived when you authored _this_ issue, which I can totally understand. 😉

**Comment by sbrannen** [comment] 2018-11-01 10:44
Closing this issue as essentially a _duplicate_ of #1513.

**Closed by sbrannen** 2018-11-01 10:44 UTC
Labels: component: Jupiter, status: team discussion, theme: programming model, type: enhancement
