### ISSUE TITLE
PackageSelector does not select packages when running as a jar inside docker container

### ISSUE THREAD

**Issue by gagansuri** [junit-team/junit5#3357] opened 2023-06-15 13:05 UTC
I am using **jupiter 5.7.1 and junit-platform-launcher 1.9.2**
## Steps to reproduce

When I run this code from my local as a shaded jar it works fine
 requestBuilder
          .selectors(selectPackage(packagename))
          .filters(includeClassNamePatterns(".*Test"));

But when I run the same jar inside a container (docker) the selector is not able to find any classes and does not execute any test case
## Context

 - Used versions (Jupiter/Vintage/Platform):
 - juniper 5.7.1 junit-platform-launcher :  1.9.2
 - Build Tool/IDE: maven , intellij , Docker 

## Deliverables
jar inside a docker container to run the jar

- [ ] ...

**Comment by marcphilipp** [comment] 2023-06-15 13:23
@gagansuri Do you mean "Jupiter" or "Juniper"?

**Comment by sbrannen** [comment] 2023-06-15 14:53
If you would like us to investigate this, please provide a minimal example that reproduces the issue -- preferably something that we can download and run such as a ZIP file or a public Git repository.

**Comment by gagansuri** [comment] 2023-06-15 15:06
sure. I will have to create a sample. please keep it open. 
do I need to create the docker file as well? I will create a simple project and share that with you.

**Comment by sbrannen** [comment] 2023-06-16 08:18
> do I need to create the docker file as well?

Yes, please include everything needed to reproduce the issue so that we can literally download the example, run it, and see the failure.

**Comment by gagansuri** [comment] 2023-06-26 22:41
I was able to resolve this issue using https://github.com/junit-team/junit5/issues/2655

**Comment by sbrannen** [comment] 2023-06-27 09:21
Thanks for the feedback.

Closing as:

- duplicate of #2655

**Closed by sbrannen** 2023-06-27 09:21 UTC
Labels: status: waiting-for-feedback
