### ISSUE TITLE
junit-jupiter-params source JAR files have invalid prefix

### ISSUE THREAD

**Issue by electrum** [junit-team/junit5#3529] opened 2023-11-02 21:05 UTC
The source files in `junit-jupiter-params-5.10.0-sources.jar` have a `main` directory prefix. The previous versions are correct.

**Comment by sbrannen** [comment] 2023-11-03 10:06
Hi @electrum,

Thanks for reporting the issue.

Fortunately, it's already been reported and fixed for inclusion in the upcoming 5.10.1 release.

In the future, please make sure you search for existing issues to avoid reporting duplicates.

Closing this issue as a:

- duplicate of #3474

**Closed** 2023-11-03 10:06 UTC
Labels: status: new
