### ISSUE TITLE
Add CamelCase Display Name Generator

### ISSUE THREAD

**Issue by sormuras** [junit-team/junit5#1595] opened 2018-09-23 14:14 UTC
## Overview

As a follow-up from #1588 use the `DisplayNameGenerator` SPI to turn names of test classes and test methods using camel-case notation into human-readable display names.

## Related Issues

- #1596 

## Deliverables

- [ ] Create and implement `CamelCaseGenerator` in `org.junit.jupiter.api.DisplayNameGenerator`
- [ ] Integrate this new pre-defined generator into `org.junit.jupiter.engine.descriptor.DisplayNameUtils`
- [ ] Extend `org.junit.jupiter.api.DisplayNameGenerationTests` to verify the implementation

**Comment by andreybleme** [comment] 2018-09-25 14:12
Are there anyone already working on this issue? I can work on it.

**Comment by sormuras** [comment] 2018-09-25 14:27
Hi @andreybleme sure -- but wait until #1588 was merged to `master`. There might be changes in the API/SPI incoming.

**Comment by andreybleme** [comment] 2018-09-25 23:03
@sormuras ok I'll wait for it. Thanks.

**Comment by sormuras** [comment] 2018-09-26 08:07
Ready, set... **Go!**

The Display Name Generator SPI is now available.

**Comment by andreybleme** [comment] 2018-10-07 18:57
Seems that @zoltanersek already did it. I'll move to another issue.

**Comment by mitchellirvin** [comment] 2018-10-16 00:19
is this wrapped up? Can we remove the "up for grabs" label, if so?

**Comment by marcphilipp** [comment] 2019-07-19 10:35
Before implementing such a generator, we should come up with a table of example method names and agree on what the generated display names should be. Thus, I've changed the status to _blocked_ for the time being.

**Comment by marcphilipp** [comment] 2019-07-19 10:36
Blocked due to https://github.com/junit-team/junit5/issues/1595#issuecomment-513181707.

**Comment by mmerdes** [comment] 2019-09-13 11:43
see also here:
https://leeturner.me/blog/2019/02/building-a-camel-case-junit5-displaynamegenerator.html

**Comment by Kazhuru** [comment] 2019-12-12 18:09
Hi, @marcphilipp I would like to take a step on this, I can make a table with examples for team discussion and clarification on how this should be displayed, in order to remove the blocker and finish if there are missing modifications, sounds good?

**Comment by marcphilipp** [comment] 2019-12-17 13:02
@Kazhuru Sure, that sounds good! 👍

**Comment by Kazhuru** [comment] 2019-12-20 18:57
| Method/Class Original Names    | Generated Display Name |
| ------------- | ------------- |
| MyFirstJunitJupiterTests()  | My First Junit Jupiter Tests |
| testWithDisplayNameWithEmojis()  | test With Display Name With Emojis   |
| MyFirstJunitJupiterTests()  | My First Junit Jupiter Tests |

**Comment by Kazhuru** [comment] 2019-12-20 20:03
Hi there, I would like to propose this kind of output activity for this generator:

| Method/Class test name input | Display name generator output |
| ------------- | ------------- |
| MyFirstJunitJupiterTests()  | My First Junit Jupiter Tests |
| JunitTestNumber12OfToday()  | Junit Test Number 12 Of Today |
| timeoutNotExceededTest()  | timeout Not Exceeded Test |
| ThrowsNullPointerException()  | Throws Null Pointer Exception |
| test1() | test 1|
| underscore_test_here() | underscore_test_here |
| testingastack() | testingastack |
| OddSymbols#%-Method() | Odd Symbols#%- Method |

I dont' know if we could aggregate more scenarios or this is a good output?

**Comment by lsikora** [comment] 2020-02-22 18:27
Couldn't this be at least integrated into https://github.com/junit-pioneer/junit-pioneer in form that @Kazhuru  suggested instead of being still blocked after 7 months :/?

**Comment by marcphilipp** [comment] 2020-02-22 20:09
Sure, that sounds like a good idea!

**Comment by marcphilipp** [comment] 2020-04-02 12:53
**Team decision:** Since there are so many edge cases we feel that it might be not be feasible to implement an out-of-the-box general purpose camel case generator that meets the majority of users' needs. Thus, we close this issue for now. If you need one, the API is extensible by design and you can write your own.

**Closed by marcphilipp** 2020-04-02 12:53 UTC
Labels: component: Jupiter, status: blocked, status: team discussion, theme: reporting, type: new feature
