### ISSUE TITLE
When calling assertThrows, why isn't it checking the message when its expectedType is an instance of the catched object?

### ISSUE THREAD

**Issue by leobastiani** [junit-team/junit5#2485] opened 2020-12-01 20:27 UTC
https://github.com/junit-team/junit5/blob/177d808f886355fac552aee9495212a4041c0316/junit-jupiter-api/src/main/java/org/junit/jupiter/api/AssertThrows.java#L59

**Comment by marcphilipp** [comment] 2020-12-02 06:35
Duplicate of #2154

**Closed by marcphilipp** 2020-12-02 06:35 UTC
