### ISSUE TITLE
JUnit 4 interoperability

### ISSUE THREAD

**Issue by akozlova** [junit-team/junit5#171] opened 2016-03-08 13:46 UTC
I try to run method from org.junit.gen5.engine.junit4.samples.junit4.EnclosedJUnit4TestCase.

The first junit 4 test is added but then junit 5 engine proceed and I get an exception:
org.junit.gen5.commons.util.PreconditionViolationException: Method 'failingTest' is not a test method.
	at org.junit.gen5.engine.junit5.discovery.JUnit5TestableFactory.throwCannotResolveMethodException(JUnit5TestableFactory.java:171)
	at org.junit.gen5.engine.junit5.discovery.JUnit5TestableFactory.fromMethod(JUnit5TestableFactory.java:66)
	at org.junit.gen5.engine.junit5.discovery.JUnit5Testable.fromMethod(JUnit5Testable.java:28)
	at org.junit.gen5.engine.junit5.discovery.DiscoverySelectorResolver.resolveTestMethod(DiscoverySelectorResolver.java:79)
	at org.junit.gen5.engine.junit5.discovery.DiscoverySelectorResolver.lambda$resolveSelectors$3(DiscoverySelectorResolver.java:66)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.gen5.engine.junit5.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:65)
	at org.junit.gen5.engine.junit5.JUnit5TestEngine.resolveDiscoveryRequest(JUnit5TestEngine.java:47)
	at org.junit.gen5.engine.junit5.JUnit5TestEngine.discover(JUnit5TestEngine.java:40)
	at org.junit.gen5.launcher.main.DefaultLauncher.discoverRoot(DefaultLauncher.java:84)
	at org.junit.gen5.launcher.main.DefaultLauncher.discover(DefaultLauncher.java:54)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:)

It could be a bug in my code but actually I start tests by name and that's it:
``` builder.select(NameBasedSelector.forNames(mappedLines)).build() ```

If it's wrong to post my issues here, please notify me. 
Thanks,
Anna

**Comment by marcphilipp** [comment] 2016-03-08 13:49
Is the value of `mappedLines` just `"failingTest"`?

**Comment by akozlova** [comment] 2016-03-08 13:50
No, it's org.junit.gen5.engine.junit4.samples.junit4.EnclosedJUnit4TestCase.NestedClass#failingTest

**Comment by marcphilipp** [comment] 2016-03-08 13:53
Then this sounds like a bug. We will investigate and get back to you.

**Comment by marcphilipp** [comment] 2016-03-08 13:56
@junit-team/junit-lambda I think `JUnit5TestableFactory` should not throw exceptions when it cannot resolve selectors because other TestEngines might. What do you think?

**Comment by jlink** [comment] 2016-03-08 14:03
I think you're right. An unresolvable selector should just be ignored. An
unresolvable unique ID however should lead to an exception.


2016-03-08 14:56 GMT+01:00 Marc Philipp <notifications@github.com>:

**Comment by marcphilipp** [comment] 2016-03-08 14:07
In the current JUnit4 TestEngine unresolvable unique IDs (at least those we know are unresolvable) are just logged as a warning. I think this should be handled consistently by both engines.

**Comment by jlink** [comment] 2016-03-08 14:12
Sounds right. I could do that on Friday unless you want to go first.

2016-03-08 15:07 GMT+01:00 Marc Philipp <notifications@github.com>:

**Comment by marcphilipp** [comment] 2016-03-08 14:14
I don't think I will have time to do it before Friday. So, feel free to do it. :smiley:

**Comment by jlink** [comment] 2016-03-09 08:10
Trying to discover methods and classes that are not JUnit5 tests or containers are now being logged and ignored as in JUnit4.

I'm not sure we should do the same with:
- Unique IDs that do not follow the correct unique ID syntax
- Classes or methods from Unique IDs that do not exist

IMO, at least the first one should throw an exception since it means that the IDE (or any other client for that matter) is doing something wrong.

**Comment by akozlova** [comment] 2016-03-09 09:11
To the first one: I have problems with JUnit4TestCaseWithRunnerWithCustomUniqueIds. No tests are run and the warning is shown. Not sure that I understand how should IDE detect that it is special, especially when all tests from package are run

**Comment by jlink** [comment] 2016-03-09 15:20
@akozlova How exactly do you try to run JUnit4TestCaseWithRunnerWithCustomUniqueIds? 

When running
```
@RunWith(JUnit5.class)
@Classes(JUnit4TestCaseWithRunnerWithCustomUniqueIds.class)
public class TestCaseRunWithJUnit5 {
}
```
from IntelliJ it works here, i.e. the `test` is reported as failing.

**Comment by akozlova** [comment] 2016-03-09 15:35
I have support for junit 5 locally, so I run the test without @RunWith(JUnit5.class). Unfortunately I can't share the details now, will post the trace tomorrow.

**Comment by akozlova** [comment] 2016-03-10 10:47
I get logging from org.junit.gen5.engine.junit4.execution.TestRun#lookupTestDescriptor and test is not run:

WARNING: Runner org.junit.gen5.engine.junit4.samples.junit4.RunnerWithCustomUniqueIds on class org.junit.gen5.engine.junit4.samples.junit4.JUnit4TestCaseWithRunnerWithCustomUniqueIds reported event for unknown Description: test(org.junit.gen5.engine.junit4.samples.junit4.JUnit4TestCaseWithRunnerWithCustomUniqueIds). It will be ignored.
Mar 10, 2016 11:45:45 AM org.junit.gen5.engine.junit4.execution.TestRun lookupTestDescriptor
WARNING: Runner org.junit.gen5.engine.junit4.samples.junit4.RunnerWithCustomUniqueIds on class org.junit.gen5.engine.junit4.samples.junit4.JUnit4TestCaseWithRunnerWithCustomUniqueIds reported event for unknown Description: test(org.junit.gen5.engine.junit4.samples.junit4.JUnit4TestCaseWithRunnerWithCustomUniqueIds). It will be ignored.
Mar 10, 2016 11:45:45 AM org.junit.gen5.engine.junit4.execution.TestRun lookupTestDescriptor
WARNING: Runner org.junit.gen5.engine.junit4.samples.junit4.RunnerWithCustomUniqueIds on class org.junit.gen5.engine.junit4.samples.junit4.JUnit4TestCaseWithRunnerWithCustomUniqueIds reported event for unknown Description: test(org.junit.gen5.engine.junit4.samples.junit4.JUnit4TestCaseWithRunnerWithCustomUniqueIds). It will be ignored.

Should I start a new issue for that?

**Comment by jlink** [comment] 2016-03-10 12:07
I'll have look into it tomorrow.

**Comment by jlink** [comment] 2016-03-11 08:25
OK. I can reproduce the bug. It looks like JUnit4 test classes with runners
are not correctly resolved during event propagation.

@marcphilipp: Can we look into that together?

2016-03-10 13:06 GMT+01:00 Johannes Link <johannes.link@gmail.com>:

**Comment by marcphilipp** [comment] 2016-03-16 19:38
There was a bug in the runner used in `JUnit4TestCaseWithRunnerWithCustomUniqueIds`. It uses a custom serializable class for its unique IDs that did not adhere to the equals/hashCode contract. I fixed it in c10cdc2.

@akozlova Can you try the latest snapshot and confirm that the problem is solved now?

**Comment by akozlova** [comment] 2016-03-17 10:38
Marc, that's work now. Unfortunately the support is already broken with NoSuchMethodError due to change in String TestIdentifier.getUniqueId(). What should be the 'update strategy' for the time being?

**Comment by marcphilipp** [comment] 2016-03-17 10:43
Sorry for that. :-/

We are trying to keep changes like that to a minimum. However, at this stage, there still will be a few that affect Launcher and Engine APIs, e.g. the discussion regarding display name and name and the `TestSource` interface will probably lead to additional changes.

What would work for you? Do you want us to notify you before or after we make such a change in the current SNAPSHOT versions so you can adapt IntelliJ's support?

**Comment by akozlova** [comment] 2016-03-17 11:00
We just released a new version (or would release it this week) and I don't think that it's feasible to put my changes in the stable release, so the number of people who would try it is really not big - one need to unpack jars, pass VM args and so on. Unfortunately, it can't be just another plugin by internal reasons. 

When we would open new EAP (~ in a month), it would be easier. Anyway, what version do you expect me to support - ALPHA or SNAPSHOT? I hope to avoid writing reflection to support both. On the other hand I can prepend bundled jars (engine/launcher.jar - if I should not bundle them, please correct me!) so the only disadvantage is that people won't be able to see their changes in the junit-project itself.

What do you think?

**Comment by jlink** [comment] 2016-03-17 14:50
Update as for handling of errors during Unique-ID resolution: I will adapt the behaviour of JUnit5TestEngine to what JUnit4TestEngine is doing, namely just logging the problem.

**Comment by jlink** [comment] 2016-03-17 18:56
@akozlova I think you should only support a single version of launcher API. My hope is that Milestone 1 would be stable enough to provide backwards compatibility from then on.

Does prepending bundled jars mean that developers have to stick with a single version of JUnit?

**Comment by akozlova** [comment] 2016-03-17 19:27
Now users could add their jars explicitly to the classpath and 'bundled jars' would be ignored. 

Do you expect end-users to download launch-jars? Users 'must not' have them so tools should provide them if they are missed, no?

**Comment by jlink** [comment] 2016-03-17 19:38
Right. The launcher should not be loaded by users but come with the IDE.

2016-03-17 20:27 GMT+01:00 Anna Kozlova <notifications@github.com>:

**Comment by marcphilipp** [comment] 2016-04-20 19:36
I'm closing this issue for now because all bugs have been addressed.

@akozlova We will get in touch with you regarding our revised roadmap shortly.

**Closed by marcphilipp** 2016-04-20 19:36 UTC
Labels: bug

**Comment by marcphilipp** [comment] 2016-04-27 13:08
#210 is a follow-up on this issue.
