### ISSUE TITLE
Merge @Test and @DisplayName annotations

### ISSUE THREAD

**Issue by ViToni** [junit-team/junit5#1543] opened 2018-08-12 17:20 UTC
After reviewing some tests written with JUnit 5 I noticed that parameterized tests can be expressed in a more compact form than "regular" tests because the @ParameterizedTest annotation supports the name parameter whereas the regular tests need a @Test and @DisplayName annotation.

If the @Test annotation would accept a String value the same could be achieved by using just one annotation.

What do you think?

**Comment by smoyer64** [comment] 2018-08-12 18:45
Duplicate of #614 and #1504

**Closed as completed** 2018-08-13 11:06 UTC
Labels: status: duplicate, type: enhancement, theme: programming model, component: Jupiter

**Comment by sbrannen** [comment] 2018-08-13 11:08
related to #1440
