### ISSUE TITLE
Use custom method to resolve name of parameterized test invocation

### ISSUE THREAD

**Issue by Frontrider** [junit-team/junit5#1458] opened 2018-06-07 13:06 UTC
## Overview

Currently we can do this to set a name in parameterized tests:
`@ParameterizedTest(name="{index}->{0}")`

But, I have a test where I need a little more in terms of how I customize the name (if I want to make it easy to read). Preferably something like this: 

``` java
@ParameterizedTest(name =
    (index, arguments) -> index + " -> " + arguments[0].getDisplayName()
)
```

This allows us to dynamically generate the name of the test, based on something other than `toString()`.

## Workaround

Add an extra string parameter to the test, than use that in the name.

## Related Issues

- #1309

**Comment by sormuras** [comment] 2018-06-07 13:09
> Add an extra string parameter to the test, than use that in the name.

This.

**Comment by sbrannen** [comment] 2018-06-07 13:13
Lambda expressions and method references are not valid assignment values for annotation attributes in Java.

It is therefore impossible to implement the proposal "as is".

**Comment by sbrannen** [comment] 2018-06-07 13:15
See also #1309.

Would something like that meet your needs?

**Comment by Frontrider** [comment] 2018-06-07 18:37
And you're right. And yes, that could fit my needs.

**Comment by marcphilipp** [comment] 2018-06-08 04:53
Duplicate of #1309.

**Closed by marcphilipp** 2018-06-08 04:53 UTC
Labels: component: Jupiter, status: duplicate, theme: parameterized tests, theme: programming model, type: enhancement

**Comment by sbrannen** [comment] 2018-06-08 08:06
OK. In that case, I will close this issue as a _duplicate_ of #1309.

**Comment by sbrannen** [comment] 2018-06-08 08:07
Oh wait... @marcphilipp had already done that. 

I just hadn't refreshed the page in my browser. 😉
