### ISSUE TITLE
Generate multiple test instances (with names) from a TestInstanceFactory

### ISSUE THREAD

**Issue by t-8ch** [junit-team/junit5#2092] opened 2019-11-06 16:59 UTC
I am trying to find a nice way for testclasses to be executed multiple times based on an external configuration.
My test classes get configurations for multiple different systems to interact with via system properties.
The tests should then be executed for each of these systems without the programmer having to know about the mechanism.

```java
// interface to annotate tests with
@ExtendWith(ForEachSystemFactory.class)
@interface RunForEachSystem() {}
```
```java
// factory creating test instances
class ForEachSystemFactory implements TestInstanceFactory {
  // create instances displaynames
  @Override
  public Map<String, Object> createTestInstances(...) {
     buildMap(
       "systemFoo", ReflectionSupport.newInstance(factoryContent.getTestClass(), ...)
       "systemBar", ReflectionSupport.newInstance(factoryContent.getTestClass(), ...)
     )
  }
}
```

```java
// test used in examples
class SomeTest {
  @Test
  void testSomething() {}
}
```

The end result would be something like this

All tests
  * SomeTest
    * systemFoo  (as returned by `createTestInstances()`)
      * testSomething()
    * systemBar
      * testSomething()

In theory it would be even nicer to generate the whole suite for each system, but it seems to me this would be much harder to implement.

All tests
  * systemFoo
    * SomeTest
      * testSomething()
  * systemBar
    * SomeTest
      * testSomething()

Unfortunately I can neither change the execution engine nor the way these parameters are passed.

Alternatively it looks like a `@TestTemplate` for test classes would be a good fit.

**Comment by marcphilipp** [comment] 2019-11-06 17:07
Duplicate of #871

**Closed by marcphilipp** 2019-11-06 17:07 UTC

**Comment by marcphilipp** [comment] 2019-11-06 17:10
Thanks for reporting the feature request. I added this issue to the growing list on #871.

**Comment by t-8ch** [comment] 2019-11-06 17:20
Thanks for the fast response! This is indeed exactly my usecase, will follow there.
