### ISSUE TITLE
Introduce Before/AfterEachExceptionHandler

### ISSUE THREAD

**Issue by phoenix384** [junit-team/junit5#1508] opened 2018-07-25 16:01 UTC
To handle exceptions thrown by test methods there is the TestExecutionExceptionHandler interface an extension can implement.
But I did not find a possibility to handle exceptions thrown by any user defined BeforeEach or AfterEach method.
Would it be possible to introduce something like a BeforeEachExceptionHandler/AfterEachExceptionHandler as well?

**Comment by marcphilipp** [comment] 2018-07-25 18:32
Duplicate of #1454

**Closed by marcphilipp** 2018-07-25 18:32 UTC
