### ISSUE TITLE
`@ParameterizedTest` ignores additional arguments beyond formal parameter list

### ISSUE THREAD

**Issue by milliken99** [junit-team/junit5#3708] opened 2024-02-26 21:42 UTC
junit-jupiter-params-5.9.2

## Steps to reproduce

```java
    private static Stream<Arguments> fooData() {
        return Stream.of(
            Arguments.of("1",
            Arguments.of(""))
        );
    }

    @ParameterizedTest
    @MethodSource("fooData")
    void testFoo(final String fooString) {
        assertFalse(fooString.isEmpty());
    }
```

I would expect a runtime error as the stream of arguments return in `fooData()` aren't compatible with `testFoo(String s)`.  In this instance, only the first argument (i.e. `"1"`) is fed to `testFoo()`, all other arguments are unceremoniously dropped on the floor.  Note that the second argument (i.e., `""`) is not tested and would have led to a unit test failure.

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.9.2
 - Build Tool/IDE: IntelliJ

**Comment by milliken99** [comment] 2024-02-27 14:00
Hi Sam, thanks for your comment.  The incorrect stream of arguments was intentional.  Since there are no suitable arguments for the indicated test method, I expected an error message.  Instead I receive output that all tests pass.  This is at best misleading.

**Comment by sbrannen** [comment] 2024-02-28 15:21
> The incorrect stream of arguments was intentional.

Oh. Then I wouldn't use `Arguments.of()` for the second argument to convey your point, since nested `Arguments` are not supported.

Thus, if I understand you correctly, the following better illustrates your use case.

```java
	private static Stream<Arguments> fooData() {
		return Stream.of(Arguments.of("1", ""));
	}

	@ParameterizedTest
	@MethodSource("fooData")
	void testFoo(String fooString) {
		assertFalse(fooString.isEmpty());
	}
```

That still ignores the `""` argument, but that's by design.

Your `testFoo()` method only accepts a single argument, and JUnit therefore only provides a single argument, namely the first argument available from each `Arguments` instance in the stream.

For example, if you keep the above revised `fooData()` method and modify `testFoo()` to accept two `String` arguments as follows...

```java
	@ParameterizedTest
	@MethodSource("fooData")
	void testFoo(String str1, String str2) {
		assertFalse(str1.isEmpty(), "str1");
		assertFalse(str2.isEmpty(), "str2");
	}
```

That will then fail as follows.

```
org.opentest4j.AssertionFailedError: str2 ==> expected: <false> but was: <true>
```

In general, JUnit Jupiter's `@ParameterizedTest` infrastructure invokes a parameterized test method with as many arguments as can be consumed by the declared formal parameters of the method. This is in order to support use cases where the author of the test may only be interested in the first `n` elements of the argument set -- for example, when a test is parameterized by CSV data.

The code which implements this logic can be viewed here:

https://github.com/junit-team/junit5/blob/264df92c85285e65e5cb557d17c9b85557ad6fdc/junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTestExtension.java#L152-L158

----

> Since there are no suitable arguments for the indicated test method, I expected an error message. Instead I receive output that all tests pass. This is at best misleading.

Unfortunately, we cannot throw an exception in such cases since it's an existing feature that people depend on.

Though I suppose it would be possible to introduce a flag (`boolean` attribute) in `@ParameterizedTest` to fail the test if the method accepts fewer arguments than the number actually supplied.

Is that a feature that you would be interested in?

**Comment by milliken99** [comment] 2024-02-28 16:21
I think we would be interested in this feature.  Call it `strictParameterListSize` or something similar, defaulting it to `false` (or whatever gives the current behavior depending on the name).

If we go this route, would it also be possible to set this globally in `junit-platform.properties`?

**Comment by sbrannen** [comment] 2024-03-09 16:19
> I think we would be interested in this feature.

OK.

> Call it `strictParameterListSize` or something similar, 

As we all know, "naming is hard" in computer science. 😉 

> defaulting it to `false` (or whatever gives the current behavior depending on the name).
> 
> If we go this route, would it also be possible to set this globally in `junit-platform.properties`?

If we want users to be able to change the default globally, we will have to introduce an enum (3 states: default/global, true, false) instead of using a simple boolean flag (2 states: true, false), but that's certainly an option.

We'll discuss the topic it within the team during an upcoming team call.

**Comment by marcphilipp** [comment] 2024-03-13 11:37
**Team decision:** Add `argumentCountValidation` attribute to `@ParameterizedTest` that is backed by an `ArgumentCountValidationMode` enum (`DEFAULT`, `NONE`, `STRICT`) with default of `DEFAULT`. In addition, add a configuration parameter named `junit.jupiter.params.argumentCountValidation` with allowed values of `NONE` and `STRICT` which, when evaluated and not present, defaults to `NONE`.

**Comment by bottlerocketjonny** [comment] 2024-05-07 18:07
Hey @marcphilipp @sbrannen could I work on this issue? Cheers

**Comment by marcphilipp** [comment] 2024-05-08 06:27
@bottlerocketjonny Sure, go ahead! I've assigned the issue to you now. Please let us know if you need any help.

**Comment by JonasJebing** [comment] 2024-08-14 12:16
@bottlerocketjonny are you still working on this? If not, I'd like to work on a PR for this feature.

**Comment by bottlerocketjonny** [comment] 2024-08-14 18:07
> @bottlerocketjonny are you still working on this? If not, I'd like to work on a PR for this feature.

Hi! Life ended up getting in the way unfortunately so I didn't get far. Feel free to take the issue.

**Comment by JonasJebing** [comment] 2024-09-17 15:12
It doesn't seem too complicated so far. I  just happen to be taking some
vacation but I am hoping to have at least a draft PR within 2 - 3 weeks

**Comment by Kavisha4** [comment] 2024-10-17 17:16
Is this issue still open? I see a PR to close this issue?

**Comment by marcphilipp** [comment] 2024-10-17 19:16
Yes, it's still open because we haven't merged the PR, yet. 🙂

**Closed** 2024-11-17 16:06 UTC
Labels: up-for-grabs, status: in progress, component: Jupiter, theme: parameterized tests
