### ISSUE TITLE
Tight coupling in TestEngine

### ISSUE THREAD

**Issue by ps4os** [junit-team/junit5#1195] opened 2017-12-02 12:46 UTC
Currently there is no easy way to customize TestEngine.discover

For JUnit 4 we have our own approach very similar to JUnit 5 Tags.
We have different Test-Suites which define includes and excludes via Java-Code. Porting it to JUnit 5 (without the JUnit 4 adapters) is very hard, because there is no SPI like a TestClassResolver to "extend" only TestEngine.discover and keep the rest of JupiterTestEngine.

Esp. the fact that testEngineDescriptors in org.junit.platform.launcher.core.Root uses the TestEngine as a key makes it hard to provide a custom TestEngine which only implements TestEngine.discover.

Also implementing TestEngine.discover or an additional SPI should be easier. In JUnit 4 it's just about providing an array of classes and pass it to the constructor of org.junit.runners.Suite.

**Comment by marcphilipp** [comment] 2017-12-02 13:03
The JUnit Platform will eventually support declarative suites, see #744. To me it sounds like that should solve your problem, right?

**Comment by ps4os** [comment] 2017-12-02 13:35
That depends on the Suite-API, because we would like to mark our Suite-Class with Tags instead of Class-Patterns or explicit classes (black- as well as white-list approach).

**Comment by marcphilipp** [comment] 2017-12-02 13:37
It will most likely support everything a `LauncherDiscoveryRequest` supports, in particular tag filters. Thus, I'm closing this as a duplicate of #744. Feel free to chime in there and state your requirements. Thanks!

**Closed** 2017-12-02 13:37 UTC
Labels: status: duplicate
