### ISSUE TITLE
Support parallel execution of legacy Junit Tests

### ISSUE THREAD

**Issue by ravikulkarni** [junit-team/junit5#515] opened 2016-09-16 02:47 UTC
Requesting to add support for parallel execution of legacy JUnit tests.

**Use case:**
- Ability to execute legacy JUnit tests in parallel  - Legacy tests are implemented in older versions of JUnit. The tests and their helper classes have shared static and singleton  variables all over the place. The classes need not be modified before running (or could not be modified because there are lots of test cases to refactor)

[How it is implemented with JUnit 4 - Use custom test class loader & threads to implement this. I will later share my implementation with Junit4]

**Comment by marcphilipp** [comment] 2016-09-17 08:25
Parallel support is being discussed in #60. Sounds like you'd need to provide a custom class loader, too. Can you show us how you implemented this using JUnit 4?

**Comment by ravikulkarni** [comment] 2016-09-25 21:02
Here is an example of how I have implemented this. [Github Link](https://github.com/ravikulkarni/parallel_junit)

I was considering implementing this in JUnit 5 using Launcher APIs. Thoughts?

**Comment by marcphilipp** [comment] 2020-08-11 08:39
Duplicate of #2229

**Closed by marcphilipp** 2020-08-11 08:39 UTC
