### ISSUE TITLE
Influence invocation order for TestTemplate executions

### ISSUE THREAD

**Issue by sebersole** [junit-team/junit5#1141] opened 2017-11-03 15:47 UTC
When using TestTemplate, JUnit will perform executions grouped by the test method.  For example, if I have a test class that defines 2 test methods (m1, m2) as TestTemplate and provide 2 invocation contexts (c1, c2) - JUnit will perform this in the following order:

````
    * m1:c1
    * m1:c2
    * m2:c1
    * m2:c2
````
But what I really need is:

````
    * m1:c1
    * m2:c1
    * m1:c2
    * m2:c2
````

My use case is that the invocation context describes a particular database schema layout.  So c1 and c2 define the same schema, but slightly differently (one adds extra columns to a given table and defoines others).  Given that JUnit wants to group these invocations by method (iterating the context within that) we are forced to recreate that schema before each invocation.  Effectively this becomes:

````
    * create schema1 (c1) 
    * run m1
    * drop schema1
    * create schema2 (c2) 
    * run m2
    * drop schema2
    * create schema1 (c1)
    * run m1
    * drop schema1
    * create schema2 (c2) 
    * run m2
    * drop schema2
````

Obviously that works a lot better as:

````
    * create schema1 (c1) 
    * run m1
    * run m2
    * drop schema1
    * create schema2 (c2) 
    * run m1
    * run m2
    * drop schema2
````

**Comment by marcphilipp** [comment] 2017-11-03 15:52
Makes sense! Sounds like #871, right?

**Comment by sbrannen** [comment] 2017-11-03 15:54
Actually, yes... I think this is a duplicate of #871.

@sebersole, do you agree?

**Comment by sebersole** [comment] 2017-11-03 16:00
Maybe.  To be honest I am not following most of that discussion :)  But looking at his "expected order" of execution, that seems to match

**Comment by sbrannen** [comment] 2017-11-03 17:42
OK. Closing this in favor of #871.

**Closed by sbrannen** 2017-11-03 17:42 UTC
