### ISSUE TITLE
Disable test after executing @BeforeEach

### ISSUE THREAD

**Issue by farodin91** [junit-team/junit5#1985] opened 2019-08-17 21:25 UTC
Try implement a ConditionExtension which evaluate a condition after beforeeach. 

Any idea how to do this?

Some short example code 
```java
public class Tests {
  public string FooBar = null;
  
  @BeforeEach
   public void before(){
     FooBar = "test";
   }

   @Test
   @DisableIfFooIsSet
   public void test(){
     fail()
   }
}
```

**Comment by sbrannen** [comment] 2019-08-18 07:39
You cannot _disable_ a test after a `@BeforeEach` method is executed.

That is by design.

I am therefore closing this issue.

However, you can _abort_ a test within a `@BeforeEach` method via a failed assumption (or by explicitly throwing a `org.opentest4j.TestAbortedException`).

For example, the following will abort your test.

```java
import static org.junit.jupiter.api.Assertions.fail;
import static org.junit.jupiter.api.Assumptions.assumeFalse;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class Tests {

	String fooBar;

	@BeforeEach
	void before() {
		this.fooBar = "test";
		assumeFalse(this.fooBar != null, "fooBar has been set");
	}

	@Test
	void test() {
		fail();
	}
}
```

If you want to achieve the same goal via an extension, you can implement `BeforeTestExecutionCallback`.

**Closed by sbrannen** 2019-08-18 07:39 UTC

**Comment by farodin91** [comment] 2019-08-18 12:00
During the beforeEach step, our managers are initialized. These managers can have feature flags depending on the configuration, so I known a feature is supported after beforeEach step is executed. So, I want to prevent to execute tests which require a feature and the manger doesn't have the feature.

**Comment by sbrannen** [comment] 2019-08-19 13:31
> During the beforeEach step, our managers are initialized. These managers can have feature flags depending on the configuration, so I known a feature is supported after beforeEach step is executed. So, I want to prevent to execute tests which require a feature and the manger doesn't have the feature.

Then I recommend you check that via an assumption in an implementation of `BeforeTestExecutionCallback`.
