### ISSUE TITLE
How to use JUnit 5 and Java 10 in Maven with the confilcting maven-surefire-plugin and org.ow2.asm

### ISSUE THREAD

**Issue by CasterKKK** [junit-team/junit5#1409] opened 2018-05-06 07:21 UTC
In my project I try to use Java 10 with Junit 5, but something interesting occurs.

**Background**  
To make maven work well under Java 10, we need to change the asm library of `maven-compiler-plugin` to `org.ow2.asm`. And to make Junit 5 work well under Java 10, we need `maven-surefire-plugin`. Here is the `plugin` part of my `pom.xml`.

    <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.7.0</version>
                <configuration>
                    <source>10</source>
                    <release>10</release>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.ow2.asm</groupId>
                        <artifactId>asm</artifactId>
                        <version>6.1.1</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>21.1.0</version>
                <dependencies>
                    <dependency>
                        <groupId>org.junit.platform</groupId>
                        <artifactId>junit-platform-surefire-provider</artifactId>
                        <version>${junit.platform.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>

And when I run run maven's test command in Idea, everything is fine.
But when I run `mvn test -f pom.xml -e` on the root dir, it gives a error:

    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on project user-module: Execution default-test of goal
    org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test failed.: IllegalArgumentException -> [Help 1]
    org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test (default-test) on proj
    ect user-module: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
        at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
        at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke (Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
    Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.21.0:test failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
        at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
        at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke (Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
    Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init> (Unknown Source)
        at org.objectweb.asm.ClassReader.<init> (Unknown Source)
        at org.objectweb.asm.ClassReader.<init> (Unknown Source)
        at org.codehaus.plexus.languages.java.jpms.AsmModuleInfoParser.parse (AsmModuleInfoParser.java:89)
        at org.codehaus.plexus.languages.java.jpms.AsmModuleInfoParser.getModuleDescriptor (AsmModuleInfoParser.java:54)
        at org.codehaus.plexus.languages.java.jpms.LocationManager.resolvePaths (LocationManager.java:83)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.newStartupConfigForModularClasspath (AbstractSurefireMojo.java:1765)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.createStartupConfiguration (AbstractSurefireMojo.java:1708)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.createForkStarter (AbstractSurefireMojo.java:2043)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider (AbstractSurefireMojo.java:1146)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:978)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:854)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
        at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
        at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
        at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke (Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)

The `java.lang.IllegalArgumentException` at `org.objectweb.asm.ClassReader` is really weird, maybe `org.ow2.asm` is not compatible with `maven-surefire-plugin`?

Do you guys have any solution? I won't change Java 10 and Junit 5 for some reasons, so don't let me change to Java 8, THX!

**Comment by sormuras** [comment] 2018-05-06 07:33
If I traced the call stack correctly, Surefire/Plexus was compiled with `asm-6.0_BETA.jar`. If I remember correctly, there was a bug or two when it comes to parsing Java 10-compiled class files. There were fixed in ASM 6.1.1, correct @forax?

Somehow, you have to ensure Surefire/Plexus uses the new ASM version too. Which `${surefile.version}` do you use, actually?

**Comment by sormuras** [comment] 2018-05-06 07:42
@tibor17 Surefire (master, HEAD) refers to `org.codehaus.plexus:plexus-java:jar:0.9.3`. Upgrade to `0.9.7`? That version refers at least to ASM `6.1` ... better would be a new release referring to ASM `6.1.1`. Who can trigger such an update? @rfscholte?

**Comment by CasterKKK** [comment] 2018-05-06 08:58
@sormuras surefile.version = 2.21.0 and asm.version = 6.1.1, all latest...

**Comment by sormuras** [comment] 2018-05-06 09:41
Mh, perhaps repeat the `<!-- Use newer version of ASM -->` in the` maven-surefire-plugin` dependencies section?

**Comment by CasterKKK** [comment] 2018-05-06 09:46
@sormuras What's your point? I **AM USING** the latest version of `maven-surefire-plugin`(2.21.0) and `org.ow2.asm`(6.1.1), am not I? The key point is the depedency of `maven-surefire-plugin`, isn't it?

**Comment by Tibor17** [comment] 2018-05-06 09:47
@sormuras 
@rfscholte
We need to create or find same issue in SUREFIRE Jira. Fix it in master branch and hopefully we may have a chance to release surefire version 2.22.0 soon with new JUnit 5 provider under Surefire project.

**Comment by sormuras** [comment] 2018-05-06 09:48
...and like the `maven-compiler-plugin` the `maven-surefire-plugin` ships with a "default" ASM version.

You patched the `maven-compiler-plugin`.
You didn't patch the `maven-surefire-plugin`. So it refers to `ASM6_BETA` (via it's 'plexus-java' dep).

I'm not sure if it works, though.

**Comment by Tibor17** [comment] 2018-05-06 09:49
@CasterKKK 
Try this
        <plugin>
            <artifactId>maven-surefire-plugin</artifactId>
            <version>21.1.0</version>
            <dependencies>
                <dependency>
                    <groupId>org.junit.platform</groupId>
                    <artifactId>junit-platform-surefire-provider</artifactId>
                    <version>${junit.platform.version}</version>
                </dependency>
                <dependency>
                    <groupId>org.ow2.asm</groupId>
                    <artifactId>asm</artifactId>
                    <version>6.1.1</version>
                </dependency>
            </dependencies>
        </plugin>

**Comment by Tibor17** [comment] 2018-05-06 10:02
@CasterKKK 
What version of Maven use use?

**Comment by CasterKKK** [comment] 2018-05-06 10:35
@Tibor17 maven.version = 3.5.3  
In fact, your solution is work. But another problem occurs, and I don't know if I should ask you for help.  
In a short word, maven cannot find the test file.

```
[INFO] --- maven-surefire-plugin:2.21.0:test (default-test) @ user-module ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[WARNING] Corrupted STDOUT by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file D:\Workspaces\IdeaWorkspace\CasterMovieVertx\user-module\target\surefire-reports\2018-05-06T18-20-20_926-jvmRun1.dumpstream
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
```

But in fact, I have several tests in `test` dir. I doubt if `maven-surefire-plugin` can find the tests...

**Comment by Tibor17** [comment] 2018-05-06 10:43
@CasterKKK 
I think this is issue where Maven uses one version of ASM library and `plexus-java` another.
Now you should ask Robert Scholte on Maven Mailing List.
You should subscribe to Maven Developers List <dev@maven.apache.org> and ask directly there if this is workaround is really the way to do it. Not sure if this workaround would be generic solution. Robert knows about this issue but I do not know how far the community goes with generic solution for all plugins and Maven itself.

**Comment by Tibor17** [comment] 2018-05-06 10:50
@CasterKKK 
@sormuras 
Not sure about empty test set but it might be caused by corrupted stream as I see.
It can be the same issue of reordering two lines of code:
https://github.com/apache/maven-surefire/commit/5e073791f9bb06cae1ed6513c8a5bde24844cf73
The point is to call `System.setOut()` before registering listeners to JUnit which is the above fix.
@sormuras Would it be this issue?

**Comment by CasterKKK** [comment] 2018-05-06 10:56
@Tibor17 
I am afraid I have a different opinion. As you can see in the second report:  
`java.lang.NoSuchMethodError: org.junit.platform.commons.util.ReflectionUtils.isNotPrivate(Ljava/lang/reflect/Member;)Z`  
I think that is because of some methods' missing?

**Comment by sormuras** [comment] 2018-05-06 10:57
Which `platform` and which `jupiter` version are in play?

**Comment by sormuras** [comment] 2018-05-06 10:58
`${junit.platform.version}` should be `1.2.0`
`${junit.jupiter.version}` should be `5.2.0`

**Comment by sormuras** [comment] 2018-05-06 10:59
Like shown in the `junit5-jupiter-starter-maven`: https://github.com/junit-team/junit5-samples/blob/master/junit5-jupiter-starter-maven/pom.xml

**Comment by Tibor17** [comment] 2018-05-06 11:02
@sormuras 
I guess @CasterKKK uses some mix of incompatible version of libs or surefire provider, or?

**Comment by sormuras** [comment] 2018-05-06 11:04
> I guess @CasterKKK uses some mix of incompatible version of libs or surefire provider, or?

Looks like that, aye.

**Comment by CasterKKK** [comment] 2018-05-06 11:34
In fact, the problem is I didn't add:
```
<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-params</artifactId>
			<version>${junit.jupiter.version}</version>
			<scope>test</scope>
</dependency>
```
After adding that everything is fine, thank you guys!

**Closed** 2018-05-06 11:36 UTC
Labels: component: Surefire, status: waiting-for-feedback, status: works-as-designed

**Comment by sormuras** [comment] 2018-05-06 15:05
fyi, https://issues.apache.org/jira/browse/SUREFIRE-1518 was created to update `plexus-java` in `surefire`
