### ISSUE TITLE
How to mark a test as 'error'

### ISSUE THREAD

**Issue by Moriarty16** [junit-team/junit5#2279] opened 2020-04-29 09:44 UTC
I understand when to mark a test as 'pass', 'fail' or 'skip', but I'm wondering how to mark a test as 'error'.
Demo test result:
`testsuite name="MainTest" tests="5" failures="0" errors="0" skipped="0" time="102.631".`

Since there is a `errors="0"`, maybe it's possible to mark as 'error'?
There is a special scenario I need to mark a test as 'error', how am I supposed to do that?

**Comment by sbrannen** [comment] 2020-04-29 13:01
The `errors` attribute in that XML report is used to denote that a test failed due to an exception that was not an `AssertionError`. The assumption is that some unexpected "error" occurred during the test that was not the result of an invocation of an `assert...()` method.

It's up to the report generator to differentiate between `AssertionError` and other types of exceptions thrown by a test for the `failures` and `errors` attributes in that XML format, respectively. Note, however, that report generators are not required to differentiate between those two categories of exceptions.

For example, some IDEs differentiate between the two.

**Comment by Moriarty16** [comment] 2020-04-30 07:20
Hi sbrannen,
Thanks so much for your reply.
Normally I only need test results to be "pass" and "failure", that's enough already.
I wrote a demo in Java within IntelliJ IDEA, please have a look:
~~~
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class DemoTest {

    @Test
    void test01() {
        System.out.println("Test 01");
    }

    @Test
    void test02() throws Throwable {
        System.out.println("Test 02");
        throw new Throwable();
    }

    @Test
    void test03() throws ArithmeticException {
        System.out.println("Test 03");
        throw new ArithmeticException();
    }

    @Test
    void test04() {
        System.out.println("Test 04");
        throw new RuntimeException();
    }

    @Test
    void test05() {
        System.out.println("Test 05");
        Assertions.assertTrue(true);
    }

    @Test
    void test06() {
        System.out.println("Test 05");
        Assertions.fail("This demo test should fail");
    }

}
~~~

And I got the result as: **Test failed 4, passed: 2 of 6 tests**
I expected that some of the tests would get a result of "error", but I didn't, all were "failed", I was confused. Could you pls help to explain this? Thanks in advance!

**Comment by Moriarty16** [comment] 2020-04-30 07:24
I also met similar issue with android Instrumentation test(within test folder `androidTest`), I can run the tests with two ways, also I cannot get any test result as "error", only "failure" was found:
1. Directly run the tests within android studio "run" button
2. Run android tests with gradle command: `./gradlew connectedDebugAndroidTest`

**Comment by sormuras** [comment] 2020-04-30 07:25
> It's up to the report generator to differentiate...

...and it is up to IDEA how to present it.

![image](https://user-images.githubusercontent.com/2319838/80683424-789d0180-8ac4-11ea-9a25-127911120934.png)

**Comment by Moriarty16** [comment] 2020-04-30 07:29
Thanks for your reply.
Mainly I need to get a test result as "error" when I run the android Junit5 test with `./gradlew connectedDebugAndroidTest`, I will check how gradle  generates test report first.

**Comment by sbrannen** [comment] 2020-04-30 08:53
**Team Decision**: Closing this issue as "works as designed". See https://github.com/junit-team/junit5/issues/2279#issuecomment-621189026 for details.

**Closed by sbrannen** 2020-04-30 08:53 UTC
Labels: status: works-as-designed

**Comment by Moriarty16** [comment] 2020-05-09 02:53
Hi I need to verify one more thing regarding this issue.
Say I write the tests [like this](https://github.com/junit-team/junit5/issues/2279#issuecomment-621659798), I run this test.

And without the presentation by IntelliJ IDEA showing the "failures" of this test, I believe JUnit itself generates a test report or someway to record the test result, and there should be "error" in the test result. How am I able to locate the result generated by JUnit?

Thanks a lot.

**Comment by marcphilipp** [comment] 2020-05-09 11:53
JUnit only creates XML report if you use the Console Launcher, not when you run tests via IntelliJ.
