### ISSUE TITLE
Unexpected execution order of JUnit 4 and 5 test methods

### ISSUE THREAD

**Issue by IrisPallida** [junit-team/junit5#1453] opened 2018-06-06 13:18 UTC
With the following test class I wanted to show, that JUnit 4 and 5 tests can be run in parallel using the JUnit platform runner.

```java
@RunWith(JUnitPlatform.class)
public class SomeTest {

  @BeforeClass
  public static void beforeClassTest() {
    System.out.println("*** beforeClassTest ***");
  }

  @org.junit.Test
  public void jUnit4test() {
    System.out.println("*** jUnit4test***");
  }

  @org.junit.jupiter.api.Test
  public void jUnit5test() {
    System.out.println("*** jUnit5test***");
  }

}
```

Running this test class in Eclipse, I get the following output:

```
*** jUnit5test***
*** beforeClassTest ***
*** jUnit4test***
```

I expected the method annotated with @BeforeClass to be executed at first, but this wasn't the case. Is this a bug or intentional?

This are the dependencies resolved in my project:
```
junit: 4.12
junit-platform-runner: 1.1.0
```

**Comment by sormuras** [comment] 2018-06-06 13:23
What did you expect the output took look like?

### 5 (Jupiter)
```
*** jUnit5test***
```

### 4
```
*** beforeClassTest ***
*** jUnit4test***
```

**Comment by IrisPallida** [comment] 2018-06-06 13:31
I expected `beforeClassTest()` to be the first method being executed. So I thought the output would look like that (or the last two methods vice versa):

```
*** beforeClassTest ***
*** jUnit5test***
*** jUnit4test***
```

**Comment by sbrannen** [comment] 2018-06-06 14:58
I am closing this issue since this is the expected behavior.

**Closed by sbrannen** 2018-06-06 14:58 UTC

**Comment by smoyer64** [comment] 2018-06-06 17:02
@IrisPallida 

If the desired behavior is for the ``beforeClassTest`` method to perform the set-up for all tests in the class, there's nothing that keeps you from annotating that method with both JUnit 4 and JUnit 5 annotations as follows:

```
  @BeforeClass
  @BeforeAll
  public static void beforeClassTest() {
    System.out.println("*** beforeClassTest ***");
  }
```

It should be noted however that, since JUnit 4 and JUnit 5 tests are executed using different engines, this method will be executed twice:

```
*** beforeClassTest ***
*** jUnit5test***
*** beforeClassTest ***
*** jUnit4test***
```

Note that this doesn't mean it's executing once per test - that's a side effect of only having one of each test in your class.  If you had more tests you might see something more like:

```
*** beforeClassTest *** (executed by junit-jupiter-engine)
*** jUnit5test1***
*** jUnit5test2***
*** jUnit5test3***
*** jUnit5test4***
*** jUnit5test5***
*** beforeClassTest *** (executed by junit-vintage-engine)
*** jUnit4test1***
*** jUnit4test2***
*** jUnit4test3***
*** jUnit4test4***
*** jUnit4test5***
```

**Comment by sbrannen** [comment] 2018-06-06 17:04
@smoyer64 is of course correct.

You _could_ do that, but I personally would not recommend that anyone combine elements from two different testing frameworks in the same physical class. 😉

**Comment by smoyer64** [comment] 2018-06-06 17:09
@sbrannen of course ... anytime you have to in-line package names you should look for an architectural flaw!

**Comment by IrisPallida** [comment] 2018-06-07 05:58
Thank you all for you explanations!
I was experimenting with the behaviour of JUnit 4 and 5. After your clarification it seems pretty obvious why it works that way.
