### ISSUE TITLE
Java 10/JUnit 5/Spring Boot 2: Unit tests fail when Surefire forkCount > 0 or not specified

### ISSUE THREAD

**Issue by testphreak** [junit-team/junit5#1469] opened 2018-06-17 01:03 UTC
**Dependencies**
`JUnit`: 5.2.0
`Spring Boot`: 2.0.3-RELEASE
`Java`: 10 *(in module mode)*
`Surefire`: 2.22.0

**Error**
When I run the tests, I see the following error:

```
java.lang.NoClassDefFoundError: Could not initialize class org.springframework.test.context.TestContextManager
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$0(ExtensionValuesStore.java:78)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:183)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.getOrComputeIfAbsent(ExtensionValuesStore.java:85)
	at org.junit.jupiter.engine.execution.ExtensionValuesStore.getOrComputeIfAbsent(ExtensionValuesStore.java:89)
	at org.junit.jupiter.engine.execution.NamespaceAwareStore.getOrComputeIfAbsent(NamespaceAwareStore.java:61)
	at org.springframework.test.context.junit.jupiter.SpringExtension.getTestContextManager(SpringExtension.java:202)
	at org.springframework.test.context.junit.jupiter.SpringExtension.beforeAll(SpringExtension.java:76)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeBeforeAllCallbacks$5(ClassTestDescriptor.java:224)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeBeforeAllCallbacks(ClassTestDescriptor.java:224)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:161)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:111)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:121)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:121)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:132)
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class org.springframework.test.context.TestContextManager
		at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$getOrComputeIfAbsent$0(ExtensionValuesStore.java:78)
		at org.junit.jupiter.engine.execution.ExtensionValuesStore$MemoizingSupplier.get(ExtensionValuesStore.java:183)
		at org.junit.jupiter.engine.execution.ExtensionValuesStore.remove(ExtensionValuesStore.java:99)
		at org.junit.jupiter.engine.execution.NamespaceAwareStore.remove(NamespaceAwareStore.java:73)
		at org.springframework.test.context.junit.jupiter.SpringExtension.afterAll(SpringExtension.java:88)
		at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeAfterAllCallbacks$9(ClassTestDescriptor.java:262)
		at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
		at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeAfterAllCallbacks$10(ClassTestDescriptor.java:262)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
		at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeAfterAllCallbacks(ClassTestDescriptor.java:262)
		at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.after(ClassTestDescriptor.java:177)
		at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.after(ClassTestDescriptor.java:65)
		at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeAfter(HierarchicalTestExecutor.java:135)
		at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:128)
		... 29 more
```

**Test Case**
One of my tests:

```java
@ExtendWith(SpringExtension.class)
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ActiveProfiles("test")
public class UserRepositoryTest {

    @Autowired
    private TestEntityManager testEntityManager;

    @Autowired
    private UserRepository userRepository;

    @AfterEach
    public void tearDown() {
        userRepository.deleteAll();
    }

    @Test
    public void whenFindBySomeUserId_thenReturnUser() {
        // given
        User user1 = new User();
        user1.setSomeAccountId("274712734545");
        user1.setSomeUserId("ABC123TEST");
        user1.setSomeUserName("test-demo");

        testEntityManager.persistAndFlush(user1);

        // when
        User found = userRepository.findBySomeUserId(user1.getAwsUserId());

        // then
        assertEquals(user1.getSomeUserId(), found.getSomeUserId());
    }
}
```

**Expected behavior:**
Tests run successfully when `forkCount` != 0

**Actual behavior:**
All tests fail, unless I set `forkCount` to 0 in my `surefire` configuration

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.0</version>
		<configuration>
			<forkCount>1</forkCount>
		</configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.ow2.asm</groupId>
                        <artifactId>asm</artifactId>
                        <version>6.2</version>
                    </dependency>
		   <dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-surefire-provider</artifactId>
			<version>1.2.0</version>
		   </dependency>
                </dependencies>
            </plugin>
```

**Comment by sormuras** [comment] 2018-06-17 04:14
Please **remove** this provider from the configuration and run your tests again:

```xml
<dependency>
	<groupId>org.junit.platform</groupId>
	<artifactId>junit-platform-surefire-provider</artifactId>
	<version>1.2.0</version>
</dependency>
```

Surefire now ships with its own JUnit Platform provider.

**Comment by testphreak** [comment] 2018-06-17 06:30
Hi @sormuras, neither solution worked. Still seeing the same error. Does `SureFire` after it's latest update to `2.22` still have the fork issues?

Looks like the the author of this [post](https://medium.com/criciumadev/java-10-migration-5d853f5b5f7e) in point 5 states: 

```
Modify maven-surefire-plugin configuration to disable forked process:

<configuration>
    <forkCount>0</forkCount>
</configuration>

Notes: When module-info.java is present and fork process is enabled, surefire creates a mixed classpath with modules and unnamed modules causing module visibility issues and preventing the application to start.
```
It appears to me that SureFire still has issues when using modules.

**Comment by swaechter** [comment] 2018-07-02 13:16
Using `<forkCount>0</forkCount>``works for me, but I receive the following warning:

```
[INFO] --- maven-surefire-plugin:2.22.0:test (default-test) @ server-application ---
[WARNING] useSystemClassloader setting has no effect when not forking
```

@sormuras Do you need a reproducible & minimal example to reproduce the problem?

**Comment by atkawa7** [comment] 2018-07-17 12:30
@sormuras  @swaechter I have the same issue but it only happens when I am on windows and not on linux. @swaechter your solution works in my case

**Comment by marcphilipp** [comment] 2018-07-25 19:41
Closing because this issue won't be fixed in this repo since we've donated our implementation to the Maven Surefire project. Please open an issue in [Surefire's bug tracker](https://issues.apache.org/jira/browse/SUREFIRE) instead.

**Closed by marcphilipp** 2018-07-25 19:41 UTC
Labels: component: Surefire
