### ISSUE TITLE
Add TestSkippedException to black-listed exceptions

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#1816] opened 2019-03-15 20:10 UTC
In a DynamicTest it would be nice to be able to programmatically indicate that a test was skipped by throwing the ``TestSkippedException``.  This exception currently causes a test failure but in this case it should be caught and the test execution should be marked as skipped.

**Comment by sbrannen** [comment] 2019-03-15 20:57
What about simply throwing a `TestAbortedException` which is supported for such use cases, and IMO better suited for the actual semantics of what occurs?

**Comment by smoyer64** [comment] 2019-03-15 21:26
That's what he did in the end ... see gitter for the full transcript.
 After looking at the code I realize that blacklisted isn't really the
correct terminology either.  I would expect that either of those exceptions
were caught by the engine and tallied into the right test result category.
His remaining issue is that the stack trace is shown in intellij.

**Comment by sbrannen** [comment] 2019-03-17 17:36
JUnit Jupiter only supports `TestAbortedException` (and as of JUnit Jupiter 5.4, JUnit 4's `AssumptionViolatedException`) for aborting a test _mid-flight_.

Jupiter has conditions (i.e., implementations of `ExecutionCondition`) that handle "skipping" tests _before_ they are executed.

Thus, Jupiter does not have any explicit support for `TestSkippedException`. Consequently, throwing a `TestSkippedException` is like throwing any other kind of exception in that it will cause a failure.

I am therefore closing this issue as "works as designed".

**Closed by sbrannen** 2019-03-17 17:36 UTC

**Comment by smoyer64** [comment] 2019-03-17 20:59
Makes sense to me ... as noted in Gitter I'm assuming that the stack-trace is shown by choice by IntelliJ.  Should we copy the Gitter transcript in here for historical purposes?

**Comment by sbrannen** [comment] 2019-03-17 22:15
> Should we copy the Gitter transcript in here for historical purposes?

My comments above are copied (and modified) from Gitter. So feel free to copy yours to here as well.

**Comment by Naros** [comment] 2019-03-18 17:09
@sbrannen The ultimate goal is to be able to replicate the existing `@Disabled` behavior that happens for a Jupiter enabled `@Test` method but in my case, a `DynamicNode` I have constructed from a `@TestFactory`.  In those cases, the test is marked as Ignored/Skipped and the output simply states the reason in the `@Disabled` annotation's value attribute; nothing more.

**Comment by smoyer64** [comment] 2019-03-18 18:54
@sbrannen Re-reading your comments above, I think you've covered the gist of that conversation.
