### ISSUE TITLE
Is it possible to have test filters use full boolean semantics?

### ISSUE THREAD

**Issue by littleclay** [junit-team/junit5#581] opened 2016-12-02 20:49 UTC
I see in the User Guide that filters for tests use the same OR semantics as JUnit 4's categories. Unfortunately, we've run into multiple instances where the OR semantics were not powerful enough. Take the following setup:

```
public interface Foo { }
public interface Bar { }

public class SomeTest {

    @Test
    @Category({ Foo.class })
    public void testFoo() { }

    @Test
    @Category({ Bar.class })
    public void testBar() { }

    @Test
    @Category({ Foo.class, Bar.class })
    public void testBoth() { }
}
```

If you want to run all tests with just `Foo` or `Bar` that's easy. But what if you **only** want to run tests with **both** `Foo` and `Bar` (e.g. just the method `testBoth`)? This is only a simple example, but it would be really nice if the filters for tags in JUnit 5 allowed for the execution of tests that have full boolean expressions. Something like:

```
mvn test --groups=Foo&Bar
```

to denote that both `Foo` and `Bar` need to be present.

**Comment by smoyer64** [comment] 2016-12-02 21:33
@littleclay There have been other discussions about how complex the include/exclude logic should be.  Since I've just completed adding the filtering to the maven-surefire-plugin, I can tell you that the semantics of the filter specifications in the Maven configuration file (POM) will still be a limiting factor (groups and excludedGroups are synonyms for includeTags and excludeTags for JUnit 5):

-   http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#groups
-   http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#excludedGroups

**Comment by marcphilipp** [comment] 2017-09-11 18:12
I'm closing this as a duplicate of #454.

@signed is already working on an implementation that will allow to specify full boolean expressions like `Foo & Bar`.

**Closed by marcphilipp** 2017-09-11 18:12 UTC
