### ISSUE TITLE
Gradle plugin doesn't have any method to pass in test jvm arguments

### ISSUE THREAD

**Issue by Jezza** [junit-team/junit5#650] opened 2017-02-13 21:40 UTC
I seem to be having an issue with getting JUnit 5 to execute my tests with a given set of arguments.

```groovy
test {
	jvmArgs "-ea"
	jvmArgs "-javaagent:" + jar.archivePath
}
```

The `javaagent` isn't set, and then, naturally, none of my tests pass.

I assume that the task that `JUnit` declares doesn't refer to the test task the `java` plugin declares at all, which I would assume that JUnit 4 did, as this gradle file worked with 4.

If there's a configuration I'm just missing, I'd appreciate the help.
Otherwise, if there are no plans to introduce some bridge between the two, then I'd ask if we could get a similar field within the junitPlatform [extension](https://github.com/junit-team/junit5/blob/master/junit-platform-gradle-plugin/src/main/groovy/org/junit/platform/gradle/plugin/JUnitPlatformPlugin.groovy#L28) to configure the jvmArgs.

Thanks. :D

**Comment by sormuras** [comment] 2017-02-13 22:15
This is how I worked around some missing properties when executing Jupiter-only tests via Gradles' test task: https://discuss.gradle.org/t/junit-5-jupiter-platform-snapshot-console-launcher-task/19773/3

**Comment by Jezza** [comment] 2017-02-13 22:23
Oh, nice.

Took me a bit, but I got it working.
Had to change some things, but definitely set me on the right track.

Thanks!

I'll keep the issue open, because it's probably not the best idea to rely on this workaround.

**Comment by sormuras** [comment] 2017-02-13 22:33
You're welcome.

Regarding the Gradle plugin, here is the start of design spec for JUnit Platform aka JUnit 5 support in Gradle core: https://github.com/gradle/gradle/issues/1037

**Comment by sbrannen** [comment] 2017-02-17 09:02
This is a duplicate of #475.

**Closed by sbrannen** 2017-02-17 09:02 UTC
Labels: duplicate
