### ISSUE TITLE
Test class with name Junit 5 do not appear at Suite

### ISSUE THREAD

**Issue by alissontenorio** [junit-team/junit5#2481] opened 2020-11-25 21:34 UTC
Description:
If I name a test class ending with the name Junit5, Junit Suite ( @RunWith(JUnitPlatform.class) ) will ignore this class at results. Removing this suffix It will appear again.

Example:
If I name a test class public class StackTestJunit5 it will not appear,
 but if I rename the file and the class to public class StackTest it will work normally

Using:
Junit 5
Eclipse

/snap/eclipse/48/plugins/org.junit.jupiter.api_5.5.1.v20190826-0900.jar
/snap/eclipse/48/plugins/org.junit.jupiter.engine_5.5.1.v20190826-0900.jar
/snap/eclipse/48/plugins/org.junit.jupiter.migrationsupport_5.5.1.v20190826-0900.jar
/snap/eclipse/48/plugins/org.junit.jupiter.params_5.5.1.v20190826-0900.jar
/snap/eclipse/48/plugins/org.junit.platform.commons_1.5.1.v20190826-0900.jar
/snap/eclipse/48/plugins/org.junit.platform.engine_1.5.1.v20190826-0900.jar
/snap/eclipse/48/plugins/org.junit.platform.launcher_1.5.1.v20190826-0900.jar
/snap/eclipse/48/plugins/org.junit.platform.runner_1.5.1.v20190826-0900.jar
/snap/eclipse/48/plugins/org.junit.platform.suite.api_1.5.1.v20190826-0900.jar
/snap/eclipse/48/plugins/org.junit.vintage.engine_5.5.1.v20190826-0900.jar
/snap/eclipse/48/plugins/org.opentest4j_1.2.0.v20190826-0900.jar
/snap/eclipse/48/plugins/org.apiguardian_1.1.0.v20190826-0900.jar

## Steps to reproduce
- Name a test class called StackTestJunit5
Example code:
```
public class StackTestJunit5 {
        @Test
	public void testEmptyStack() {
		assertEquals(2, 1+1, "Example");
	}
}
```
```
@RunWith(JUnitPlatform.class)
@SelectPackages("com.path.to.package")
public class StackSuite {

}
```

**Comment by sbrannen** [comment] 2020-11-26 13:00
I'm closing this as a duplicate of #2412.

**Closed by sbrannen** 2020-11-26 13:00 UTC
