### ISSUE TITLE
Cannot use Type level and Method level DisabledIf** Annotations

### ISSUE THREAD

**Issue by st0ve** [junit-team/junit5#2337] opened 2020-06-23 00:08 UTC
Version: JUnit Jupiter 5.6.2

Issue: Unable to use both type level and method level versions of the `DisabledIfSystemProperty` annotation. I am able to stack them at the same level, but when annotations are at different targets then only the first target is evaluated (in my case this is `ElementType.TYPE`).

Sample code:

```java
@DisabledIfSystemProperty(named = "FOO", matches = "foo")
public class TestSometing{

    @Test
    @DisabledIfSystemProperty(named = "BAR", matches = "bar")
    public void test_something() {
        assert true;
    }
}
```

**Comment by sbrannen** [comment] 2020-06-23 13:22
In the example you have provided, I verified that both conditions are evaluated if there is no system property `FOO=foo`.

As stated in the Javadoc:

> When declared at the class level, the result will apply to all test methods within that class as well.

Thus, if the test class is disabled at the class level, the conditions at the method level are never evaluated, and that is by design.

Similarly, if the test class is not disabled, the method-level conditions are evaluated.

In light of that, I am closing this issue.

However, if you discover that you are experiencing behavior contrary to the above, feel free to comment with additional information.

**Closed by sbrannen** 2020-06-23 13:22 UTC
Labels: component: Jupiter, theme: programming model

**Comment by st0ve** [comment] 2020-06-23 15:32
After further testing. Seems to work when run through maven command line, but does not work when run through the Intellij IDE. Must be an issue with the built in runner.

**Comment by marcphilipp** [comment] 2020-06-24 06:00
AFAIK IntelliJ explicitly disables all execution conditions when you run a class/method explicitly.
