### ISSUE TITLE
Parameterized Extension support

### ISSUE THREAD

**Issue by tasomaniac** [junit-team/junit5#2187] opened 2020-02-15 21:39 UTC
In JUnit4, since parameterized tests are at class level, parameters can be used for `TestRule`s. Here are some examples where this is useful:
- Using `TempDir` Extension with a custom path provided by parameters.
- Setting up a MockWebServer with different network ports based on parameters. This needs to be an extension since server needs to be shutdown after tests.

With JUnit 5, it is not possible to do this. Parameterized tests are only at method level. And programmatic Extension support is only at class level (needs to be a field).

**Comment by sormuras** [comment] 2020-02-15 21:49
Hi @tasomaniac -- your feature requests duplicates #871, right?

**Comment by tasomaniac** [comment] 2020-02-15 23:28
The description of that issue seems really abstract. I couldn't grasp what it meant easily.

If that's going to be released soon, then this can be closed afterwards since it might give what I need. If not, there might be multiple ways to approach the issue I mention here.

**Comment by marcphilipp** [comment] 2020-02-16 08:33
> Extension support is only at class level (needs to be a field).

I don't know what you mean by that. `@TempDir` can be a method parameter, even in a parameterized test method. Even as a field, it's scope is with the test instance (by default one per test execution). A `MockWebServer` could behave similarly.

**Comment by marcphilipp** [comment] 2020-02-16 08:33
Duplicate of #878

**Comment by marcphilipp** [comment] 2020-02-16 08:34
@tasomaniac Feel free to add comments here even though I've now closed the issue.

**Closed by marcphilipp** 2020-02-16 08:33 UTC
Labels: component: Jupiter, status: waiting-for-feedback, theme: parameterized tests

**Comment by tasomaniac** [comment] 2020-02-16 14:57
@marcphilipp your quote was not my full sentence 🤦‍♂ 

`@TempDir` or any other annotation usage are supported at method level. As far as I understand, "Programmatic" instantiation of Extensions (with parameters) only possible as a (static or non-static) field.

**Comment by marcphilipp** [comment] 2020-02-16 17:15
Ok, now I get it. My apologies for not reading carefully enough. As a workaround, if all your test methods share the same parameters, you can inject them into an `@BeforeEach` method and do your common initialization there.
