### ISSUE TITLE
AssertThrows curiousity when supplier should return a Stream (in Eclipse)

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#1563] opened 2018-08-28 20:45 UTC
## Overview

This may belong in the Eclipse bug tracker (assuming it's using its own JIT compiler), but it might also be based on how the runner is instantiated.  When a ``ThrowingSupplier<?>`` passed to the ``assertThrows()`` method returns a ``Stream``, the assertion passes if the lambda method is enclosed in a block but fails if it's a single statement.

Note that Surefire 2.22.0 runs both assertions successfully.  I don't see anything in the ``AssertThrows`` class that would produce this behavior.  In addition, if the return type of the method throwing the NPE is not a ``Stream``, then both will pass (well ... for the few types that I tested anyway).

```java
    @Test
    void assertThrowsCuriousity() {
        assertThrows(NullPointerException.class, () -> { generateNpe(); });
        assertThrows(NullPointerException.class, () -> generateNpe());
    }

    Stream<String> generateNpe() {
        throw new NullPointerException();
    }
```

## Deliverables

- [ ] perhaps none

**Comment by sbrannen** [comment] 2018-08-29 12:31
I cannot reproduce this behavior in Eclipse Oxygen.3a Release (4.7.3a).

I am therefore closing this issue as "works as designed".

If you continue to encounter problems, I would recommend that you open an issue in the Eclipse bug tracker as you hinted at.

**Closed by sbrannen** 2018-08-29 12:31 UTC
Labels: component: Jupiter, type: bug
