### ISSUE TITLE
Third-party ParameterResolvers may potentially conflict with ParameterizedTestParameterResolver

### ISSUE THREAD

**Issue by smoyer64** [junit-team/junit5#1184] opened 2017-11-24 17:04 UTC
## Overview

In the following code snippet, the Weld CDI system provides a `ParameterResolver` for the third parameter in the `parametersTakePriorityOverInjection()` method.  Since the```@TestTemplate``` "knows" that it's producing parameters for the first two parameters via its ```ArgumentSource```, it shouldn't call either the `supportsParameter()` or `resolvesParameter()` methods of Weld's `ParameterResolver`.  Other registered ```ParameterResolver```s should only be called for parameters with indexes greater than one.

```java
@ExtendWith(WeldJunit5Extension.class)
public class ParameterizedTestCompatibilityTest {

	static final String SENTENCE = " is a greek letter.";

	@ParameterizedTest
	@CsvSource({
			"Alpha, 0",
			"Beta, 1",
			"Gamma, 2"
	})
	void parametersTakePriorityOverInjection(String letter, int ordinal, String sentence) {
		assertTrue(letter.length() >= 4);
		assertTrue(ordinal >= 0 && ordinal <= 2);
		assertEquals(SENTENCE, sentence);
	}

	@Produces
	@ApplicationScoped
	String produceSentence() {
		return " is a greek letter.";
	}

}
```

When run, this code currently throws a ```ParameterResolutionException``` with the message:

```
Discovered multiple competing ParameterResolvers for parameter [java.lang.String arg0] in executable [void org.jboss.weld.junit5.compatibility.ParameterizedTestCompatibilityTest.parametersTakePriorityOverInjection(java.lang.String,int,java.lang.String)]: org.jboss.weld.junit5.WeldJunit5Extension, org.junit.jupiter.params.ParameterizedTestParameterResolver
```

This issue is somewhat related to #935 but occurs when additional parameters are correctly placed after those injected by the ```TestTemplate```.

## Versions

- `junit-jupiter-api`: 5.0.1, 5.0.2, 5.1 M1
- `junit-jupiter-params`: 5.0.1, 5.0.2, 5.1 M1

## Related Issues

- #935
- https://github.com/weld/weld-junit/issues/3
- https://github.com/weld/weld-junit/issues/13

## Deliverables

- [ ] Parameterized tests should ignore other registered parameter resolvers for parameters that will be satisfied by an ```ArgumentSource```.

**Comment by sbrannen** [comment] 2017-11-25 17:23
@smoyer64 It appears to me that this may have been fixed in 5.0.2 in this commit: https://github.com/junit-team/junit5/commit/41c76d6a703e0b8b287fb5bbc36b98660ed29875.

Can you please give it a try with 5.0.2?

**Comment by sbrannen** [comment] 2017-11-25 17:33
FWIW, even if this scenario is not _fixed_ in 5.0.2., I would argue that the `WeldJunit5Extension` is flawed.

**Any `ParameterResolver` implementation (other than `ParameterizedTestParameterResolver`) which claims that it _supports_ `java.lang.String` (or any other common Java type) without requiring the presence of a custom annotation for disambiguation is broken by design.**

In other words, no extension should claim that it *owns String*.

Based on that principle, I therefore require users to annotate such parameters with `@Autowired`, `@Qualifier`, or `@Value` in the `SpringExtension`. 😉

**Comment by sbrannen** [comment] 2017-11-25 17:43
@smoyer64, no need to try with 5.0.2.

I just confirmed the behavior against `master` with the following.

```java
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.ExtensionContext;
import org.junit.jupiter.api.extension.ParameterContext;
import org.junit.jupiter.api.extension.ParameterResolver;
import org.junit.jupiter.params.provider.CsvSource;

/**
 * Tests that reproduce claims in GitHub issue #1184.
 */
@ExtendWith(EagerBeaverStringParameterResolver.class)
class Gh1184Tests {

	@ParameterizedTest
	@CsvSource("dogbert, 42")
	void test(String animal, int number, String text) {
		assertEquals("dogbert", animal);
		assertEquals(42, number);
		assertEquals("foo bar", text);
	}

}

class EagerBeaverStringParameterResolver implements ParameterResolver {

	@Override
	public boolean supportsParameter(ParameterContext parameterContext, ExtensionContext extensionContext) {
		return parameterContext.getParameter().getType() == String.class;
	}

	@Override
	public Object resolveParameter(ParameterContext parameterContext, ExtensionContext extensionContext) {
		return "foo bar";
	}

}
```

**Comment by sbrannen** [comment] 2017-11-25 17:47
**Decision**

We will see if we can avoid such _collisions_ between such parameter resolvers for parameterized tests.

However... my previous claim that the `WeldJunit5Extension` is fundamentally broken still stands.

For example, even if we do address this issue for parameterized tests, the `WeldJunit5Extension` would still cause problems if used in conjunction with any other `ParameterResolver` that claims that it supports basic parameter types.

**Comment by sbrannen** [comment] 2017-11-25 17:56
@smoyer64, is this the [WeldJunit5Extension](https://github.com/weld/weld-junit/blob/master/junit5/src/main/java/org/jboss/weld/junit5/WeldJunit5Extension.java) implementation you're talking about?

**Comment by smoyer64** [comment] 2017-11-26 12:22
@sbrannen Yes, that's the class that I'm talking about.  There's a whole discussion about whether that extension is "too greedy" in https://github.com/weld/weld-junit/issues/3.  Since Weld is a CDI implementation, it should behave much like Spring's CDI.  You can control the context (which beans are managed) at a class level but I suspect I'm going to find a concrete example pretty quickly.  Claiming ```String``` is a bold move!

**Comment by sbrannen** [comment] 2017-11-26 15:44
Thanks for the link to the Weld issue.

I agree that the current implementation of the Weld extension is too greedy with regard to parameter resolution, and I even consider that behavior a **worst practice**.

**Comment by sbrannen** [comment] 2017-11-26 15:44
When you say "Spring's CDI", I assume you mean "Spring's DI". 😉

**Comment by sbrannen** [comment] 2017-11-26 15:45
> but I suspect I'm going to find a concrete example pretty quickly.

example of what?

**Comment by sbrannen** [comment] 2017-11-26 16:02
Based on the discussions here and my comments in https://github.com/weld/weld-junit/issues/3#issuecomment-347018429, I am tempted to simply close this issue as _works as designed_.

@junit-team/junit-lambda, Thoughts?

**Comment by sbrannen** [comment] 2017-11-26 16:03
I have also removed the _bug_ label, since I no longer consider this a bug but rather a request for _enhancement_.

**Comment by sbrannen** [comment] 2017-11-26 16:04
FYI: I have updated the title of this issue accordingly.

**Comment by sormuras** [comment] 2017-11-26 16:34
> [...] close this issue as works as designed.

+1

**Comment by sbrannen** [comment] 2017-11-28 16:54
FYI: I created https://github.com/junit-team/junit5/issues/1190

**Comment by sbrannen** [comment] 2017-11-29 16:26
Also related to: https://github.com/weld/weld-junit/issues/13

**Comment by marcphilipp** [comment] 2018-01-13 19:22
Team decision: Closing this issue as "works as designed".

**Closed by marcphilipp** 2018-01-13 19:22 UTC
Labels: component: Jupiter, status: team discussion, theme: extensions, type: enhancement
