### ISSUE TITLE
add support for tags in JUnit XML reports

### ISSUE THREAD

**Issue by bitcoder** [junit-team/junit5#1630] opened 2018-10-09 14:54 UTC
## Overview

 **Feature request.** 
As mentioned in #1182,wee're a Test Management vendor for Jira and our addon (Xray) (https://marketplace.atlassian.com/apps/1211769/xray-test-management-for-jira?hosting=server&tab=overview) provides already handling of JUnit XML reports. However, our users have the need of allowing to tag Tests with certain labels / Jira issue keys, so that their results can be mapped to the proper issues in Jira.
The problem that we're facing with JUnit is that the XML report does not provide visibility of this, so our users cannot take advantage of this information in our reports because we simply are unable to process them.
With TestNG this works fine though, so some users are using it instead. Of course we want to promote also JUnit as many users use it.
Maybe they could be added as nested elements under the <testcase> element and that wouldn't break anything.
Thanks for your help.

**Comment by marcphilipp** [comment] 2018-12-01 12:52
Duplicate of #373

**Closed by marcphilipp** 2018-12-01 12:52 UTC
