### ISSUE TITLE
Assertion invoked via reflection works abnormally in dynamic test

### ISSUE THREAD

**Issue by evanchaoli** [junit-team/junit5#1322] opened 2018-03-06 01:51 UTC
## Bug Report

Version: JUnit 5.1.0.

I want to implement a dynamic test where test cases are defined in a YAML file. Now I'm hitting a problem as the title.

Looking at my sample code:

```java
    @Test
    public void t1() throws Exception {
        java.lang.reflect.Method method = org.junit.jupiter.api.Assertions.class.getMethod("assertEquals", int.class, int.class);
        method.invoke(null, 1, 5);
    }
    
    @TestFactory
    Collection<DynamicTest> dynamicTests() {
        DynamicTest[] list = new DynamicTest[1];
        list[0] = DynamicTest.dynamicTest("dt1", new Executable() {
            @Override
            public void execute() throws Throwable {
                java.lang.reflect.Method method = org.junit.jupiter.api.Assertions.class.getMethod("assertEquals", int.class, int.class);
                method.invoke(null, 1, 50);
            }
        });
        return Arrays.asList(list);
    }
```

In the sample code, I defined a static test case t1 and a dynamic test caes dt1. In both tests, I just do a dynamic assert.

Looking at the test result, for the static test case t1, assert result is as expected:

```
  JUnit Jupiter:TestRunner:t1()
    MethodSource [className = 'com.mycompany.test.TestRunner', methodName = 't1', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <1> but was: <5>
       org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:52)
       org.junit.jupiter.api.AssertEquals.failNotEqual (AssertEquals.java:197)
       org.junit.jupiter.api.AssertEquals.assertEquals (AssertEquals.java:154)
       org.junit.jupiter.api.AssertEquals.assertEquals (AssertEquals.java:149)
       org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:305)
       sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
       sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
       java.lang.reflect.Method.invoke(Method.java:498)
       com.mycompany.test.TestRunner.t1(TestRunner.java:82)
       [...]
```

But for the dynamic test case dt1, assert result shows InvocationTargetException: 

```
  JUnit Jupiter:TestRunner:dynamicTests():dt1
    MethodSource [className = 'com.mycompany.test.TestRunner', methodName = 'dynamicTests', methodParameterTypes = '']
    => java.lang.reflect.InvocationTargetException
       sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
       sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
       java.lang.reflect.Method.invoke(Method.java:498)
       com.mycompany.test.TestRunner$1.execute(TestRunner.java:96)
       org.junit.jupiter.engine.descriptor.JupiterTestDescriptor. executeAndMaskThrowable (JupiterTestDescriptor.java:141)
       org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor. execute(DynamicTestTestDescriptor.java:41)
       org.junit.jupiter.engine.descriptor.DynamicTestTestDescriptor. execute(DynamicTestTestDescriptor.java:24)
       org.junit.platform.engine.support.hierarchical. HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3 (HierarchicalTestExecutor.java:112)
       org.junit.platform.engine.support.hierarchical.SingleTestExecutor. executeSafely(SingleTestExecutor.java:66)
       [...]
```

**Comment by sormuras** [comment] 2018-03-06 08:57
Thanks for opening the issue, @evanchaoli 

Related SO question: https://stackoverflow.com/questions/49113936/junit5-dynamic-assert-works-abnormally-in-dynamic-test

As demonstrated in commit https://github.com/junit-team/junit5/commit/b65487d1ac53097b67d176a435a7dd75fc79ffc8 you may catch instances of `InvocationTargetException` an rethrow the associated target exception. I'm not sure if we can achieve the expected behaviour without a breaking change to the (dynamic) execution model.

@junit-team/junit-lambda Method `getUnderlyingCause` in `ReflectionUtils` needs to be adopted in a backward-compatible way. Thoughts?

**Comment by sbrannen** [comment] 2018-03-06 15:49
@evanchaoli, the reason that it _works_ for your `t1()` method is purely by coincidence due to the fact that JUnit has to use reflection to invoke any test method. Note that the same holds for any testing framework using reflection to invoke test methods (e.g., JUnit 4, JUnit Jupiter, TestNG, etc.).

So, although you may consider that to be a feature, it is in fact an unavoidable behavior of any such testing framework.

In other words, this is not actually supported by design.

@sormuras, I don't think we need to make any changes to `ReflectionUtils` or to how dynamic tests are executed.

In general, whenever one uses reflection to invoke a method, the onus is on that person to properly handle any exceptions thrown during the reflective call, and that includes unwrapping of any `InvocationTargetException`.

Thus, the actual solution to this issue is not to write your own reflective code for invoking methods in `Assertions` but rather to simply delegate to `ReflectionSupport` to ensure that the `InvocationTargetException` is properly unwrapped.

For example, the following should work for you in both cases.

```java
ReflectionSupport.invokeMethod(method, null, 1, 5);
```

**Comment by sbrannen** [comment] 2018-03-06 15:52
As a side note, since we're on Java 8+, there is no need to implement `Executable` as an anonymous inner class.

Just implement it as a lambda expression. 😉

**Comment by sbrannen** [comment] 2018-03-06 16:07
Closing this issue as "works as designed".

Please use `ReflectionSupport.invokeMethod()` to resolve your issue.

Thanks

**Closed by sbrannen** 2018-03-06 16:07 UTC
Labels: component: Jupiter, status: team discussion, theme: dynamic tests
