### ISSUE TITLE
Could not set test case name with '@ParameterizedTest' as expected

### ISSUE THREAD

**Issue by Moriarty16** [junit-team/junit5#2397] opened 2020-09-03 06:07 UTC
There is a scenario, where I will run multiple tests with 'parameterizedTest', all work well except for the test case naming.
Consider the following code snippet:
~~~
    static List<Arguments> parse() {
        String url = "https://xxx.tears.mpd";
        Arguments a = Arguments.of(url, "testTunnelModePlayback");
        List<Arguments> res = new ArrayList<>();
        res.add(a);
        return res;
    }
~~~
~~~
    @ParameterizedTest(name = "{1}")
    @MethodSource("xxx.yyy#parse")
    void testPlayback(String url, String caseName) {
        // Some test logic
       // Play stream with this url, in real tests, it's more complicated than this.
    }
~~~

The issue is, when I run this test, the test case will be naming as `testPlayback(String, String): testTunnelModePlayback`.
This is not what I've been expecting, I wish the test case name to be **EXACT** `testTunnelModePlayback`.

Could you help with this issue, or am I missing other methods  to achieve my goal?

**Comment by Moriarty16** [comment] 2020-09-03 06:26
I'm using `org.junit.jupiter:junit-jupiter-params:5.6.2`.

**Comment by Moriarty16** [comment] 2020-09-04 09:14
Actual test case name: 
**testPlayback(String, String): testTunnelModePlayback**

Expected test case name:
**testTunnelModePlayback**

**Comment by Moriarty16** [comment] 2020-09-07 05:56
Hi, it has been a few days, could someone have a look?
Thanks a lot.

**Comment by sormuras** [comment] 2020-09-07 06:17
Which build tool do you use? Gradle or Maven or something else?

In IDEA everything's working as expected:

![image](https://user-images.githubusercontent.com/2319838/92354355-6ff7b000-f0e2-11ea-9764-d13c8bfa7495.png)

Yields:

![image](https://user-images.githubusercontent.com/2319838/92354387-7d149f00-f0e2-11ea-881b-a7aa3e5af7b2.png)

**Comment by Moriarty16** [comment] 2020-09-07 06:35
I'm using gradle.
I saw you have run the test, but could you take a look at the generated test result, it may not look like what we're expecting..

**Comment by sormuras** [comment] 2020-09-07 06:57
Either https://github.com/junit-team/junit5/issues/2041 or https://github.com/gradle/gradle/issues/5975 or related issues may help here. Also interesting: https://github.com/ota4j-team/opentest4j/issues/9

Closing this issue as there's no problem with JUnit Platform and/or Jupiter's handling of display names.

**Closed by sormuras** 2020-09-07 06:57 UTC
Labels: 3rd-party: Gradle, theme: reporting

**Comment by Moriarty16** [comment] 2020-09-07 07:12
This time I directly run this test without 'grale', right click on the test 'testPlayback' and select 'run', the test result shows:
<img width="365" alt="TestResult" src="https://user-images.githubusercontent.com/21101856/92358605-4eb3b580-f11c-11ea-8704-2c54362ccc81.png">


The test name is shown as: 
testPlayback(String, String): testTunnelModePlayback

My expected test name is:
testTunnelModePlayback

How could I achieve this, could you please help?

**Comment by sormuras** [comment] 2020-09-07 07:20
I can't reproduce it using **IntelliJ IDEA 2020.2.2 Preview** and pure Java -- seems you're using an Android-based test runner. Perhaps that's where Gradle (or another test runner) kicks in?

**Comment by Moriarty16** [comment] 2020-09-07 07:28
That is possible, I'm writing the test in android studio '4.0', and there is another runner:
~~~
defaultConfig {
        // XXX
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        testInstrumentationRunnerArgument "runnerBuilder", "de.mannodermaus.junit5.AndroidJUnit5Builder"
    }
~~~
~~~
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    androidTestImplementation 'androidx.annotation:annotation:1.1.0'
    androidTestImplementation 'androidx.test:runner:1.3.0'
    androidTestImplementation 'androidx.test:rules:1.3.0'
    androidTestImplementation 'androidx.test:monitor:1.3.0'
    androidTestImplementation 'androidx.test.uiautomator:uiautomator-v18:2.2.0-alpha1'
    androidTestImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.2'
    androidTestImplementation 'org.junit.jupiter:junit-jupiter-engine:5.6.2'
    androidTestImplementation 'org.junit.jupiter:junit-jupiter-params:5.6.2'
    androidTestImplementation 'org.junit.platform:junit-platform-runner:1.6.2'
    androidTestImplementation 'org.json:json:20200518'
    androidTestRuntimeOnly "de.mannodermaus.junit5:android-test-runner:1.2.0"
}
~~~

**Comment by sormuras** [comment] 2020-09-07 07:32
Any idea, Marcel? @mannodermaus

**Comment by mannodermaus** [comment] 2020-09-07 18:52
Thanks for tagging me, @sormuras. This is indeed expected for Android instrumentation tests, since test containers cannot be nested correctly with the JUnit4-based Android test runtime, and this was the next best thing I could think of.

If OP requires the actual test name for assertions, I'm afraid that a check using `String.endsWith()` must be used to resolve this. Going forward, we'll consider adding a helper method to the Android test API which'll reverse the parameterized test names back to their original form.

**Comment by Moriarty16** [comment] 2020-09-08 06:09
Could you please demonstrate how to use the `String.endsWith()` method to generate the test names as I'm expecting?  

Earlier I was thinking to write a custom gradle task, which will run after instrumentation test is completed, and update test names with a `XmlSlurper()`  which will parse and update result xml file, but that was not ideal.

If there will be a built-in method which will set the test names as I'm expecting, that will be great.

**Comment by mannodermaus** [comment] 2020-09-08 07:38
From your initial issue description, I was assuming that you wanted to inspect the test's metadata at runtime (e.g. through the `TestDescriptor` API). It sounds like you want the test names to change in the generated reports, though? In that case, my proposed approach wouldn't be applicable, sadly.

For completeness' sake, you can try annotating the test method or class with `@UseTechnicalNames`. Not sure if it'll be picked up by the current bridge to the Android runtime, but at this time this would be the only chance of changing how the test names are reported.

**Comment by Moriarty16** [comment] 2020-09-08 08:10
The best approach for me will be: both runtime test names & test names within generated report will be shown as expected.

The lesser good but still working approach will be: test names within generated report will be shown as expected.

After all, my test report will be analyzed and shown in a CI page.

**Comment by mannodermaus** [comment] 2020-09-08 20:57
@Moriarty16 Feature parity with JUnit 5's custom naming for `@ParameterizedTest` methods is currently not achievable within the constrained Android instrumentation environment, which has to map everything to JUnit 4-style reporting. The new naming scheme was introduced to _somehow_ work around these limitations and create bearable output in the first place. For more insight on the motivations behind it, please refer to [the original ticket on the android-junit5 repository](https://github.com/mannodermaus/android-junit5/issues/185) to learn how the old names being mangled by the Android tooling under the hood. Sorry if the more verbose naming doesn't work for your particular reports. We'll see how we can gradually re-introduce the custom names over time.

**Comment by Moriarty16** [comment] 2020-09-10 10:49
Currently I'll just write a customized gradle to update test case names in the test result xml.
~~~
xml.testcase.each { testCase ->
            String originalName = testCase.@name
            String updatedName = originalName.split(":")[1].trim()
            testCase.@name = updatedName
}
~~~
This is not elegant, but works for now.

Thank you guys so much for the patient replies @sormuras and @mannodermaus .
