### ISSUE TITLE
Not able to create multiple @TempDir in a testcase

### ISSUE THREAD

**Issue by joh-ku** [junit-team/junit5#2029] opened 2019-09-26 07:40 UTC
JUnit annotation @TempDir does not create multiple temporary directories. After initialization of two or more variables annotated with @TempDir all of them hold one and the same reference to a temporary path in the filesystem – actually only one temporary diectory has been created.

## Steps to reproduce

Just implement a sample code snippet as follwing (no difference between non-private field in a test class or a parameter in a lifecycle method):

Example 1:
public class MyTest {
@TempDir
Path one;

@TempDir
Path two;
...
}

Example 2:
@Test
public void myTest(@TempDir Path one, @TempDir Path two) {...}

## Context
- Used versions (Jupiter/Vintage/Platform):
<dependency>
	<groupId>org.junit.jupiter</groupId>
	<artifactId>junit-jupiter-api</artifactId>
	<version>5.5.2</version>
	<scope>test</scope>
</dependency>
<dependency>
	<groupId>org.junit.jupiter</groupId>
	<artifactId>junit-jupiter-engine</artifactId>
	<version>5.5.2</version>
	<scope>test</scope>
</dependency>
 - Used versions (Jupiter/Vintage/Platform):

 - Build Tool/IDE:
Apache Maven 3.6.0
Spring Tool Suite 4.4.0.RELEASE (Eclipse)

## Deliverables

- [ ] ...

**Comment by sormuras** [comment] 2019-09-26 07:43
That's working as expected.

What about modifying your code as follows:

```java
@Test
void myTest(@TempDir Path temp) throws Exception {
  var one = Files.createDirectories(temp.resolve("one"));
  var two = Files.createDirectories(temp.resolve("two"));
  // ...
}
```

**Comment by BlueIce** [comment] 2019-09-26 07:53
Seems like a duplicate of #1967.

**Comment by sormuras** [comment] 2019-09-26 07:58
> Seems like a duplicate of #1967.

True. Closing this issue in favor of the older one, which already mentions the work-around I posted above.

**Closed by sormuras** 2019-09-26 07:58 UTC
Labels: status: duplicate
