### ISSUE TITLE
Receiving a lot of warning messages because guardian-api is not brought in by junit

### ISSUE THREAD

**Issue by gigaSproule** [junit-team/junit5#1210] opened 2017-12-18 10:24 UTC
## Overview
I am using junit-jupiter-api version 5.0.2 in my tests (using JDK 8) and I am getting `warning: unknown enum constant Status.STABLE   reason: class file for org.apiguardian.api.API$Status not found` printed out a lot. I have noticed that JUnit is using apiguardian-api and so I have brought this in as a dependency to get rid of the warnings. But as we want to have warnings appear as errors, and as far as I'm aware, that is a common thing to do, why isn't it included as a transitive dependency instead of making the users try and figure out what is going on?

## Deliverables

- [ ] include apiguradian-api as a transitive dependency

**Comment by sormuras** [comment] 2017-12-18 10:31
Duplicate of #1105

**Closed by sormuras** 2017-12-18 10:31 UTC
