### ISSUE TITLE
Add non-null return type to assertNotNull method

### ISSUE THREAD

**Issue by adil-hussain-84** [junit-team/junit5#2477] opened 2020-11-20 15:51 UTC
It would be sweet if the `assertNotNull(actual:)` method returned the object that is passed into it back out as a non-null type.

This would help with writing JUnit 5 tests in Kotlin big time and avoid the need to force unwrap properties like this:

```
assertNotNull(myObject?.myProperty)
val myProperty = myObject!!.myProperty
assertEquals("Foo", myProperty.someOtherProperty)
```

Instead, tests like the above code snippet could be simplified to the following:

```
val myProperty = assertNotNull(myObject?.myProperty)
assertEquals("Foo", myProperty.someOtherProperty)
```

Note that the [kotlin-test](https://kotlinlang.org/api/latest/kotlin.test/) library already offers this mechanism in its [assertNotNull](https://kotlinlang.org/api/latest/kotlin.test/kotlin.test/assert-not-null.html) method, and Apple offers a similar [XCTUnwrap](https://developer.apple.com/documentation/xctest/3380195-xctunwrap) method in their [XCTest](https://developer.apple.com/documentation/xctest) framework.

**Comment by marcphilipp** [comment] 2020-11-20 16:09
I think that's a good idea but we'd have to investigate whether the return type can be changed without breaking backward compatibility.

**Comment by marcphilipp** [comment] 2020-11-20 16:09
Tentatively slated for 5.8 M1 solely for the purpose of _team discussion_.

**Comment by sormuras** [comment] 2020-11-20 16:20
If such a refactoring breaks the existing API, we could introduce new methods that a) delegate to the existing ones for the null-check and b) return the given values. Similar to [`Objects.requireNonNull`](https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#requireNonNull-T-) from the `java.util` package.

**Comment by sbrannen** [comment] 2020-11-20 16:43
The proposal is analogous to the signature for `org.junit.platform.commons.util.Preconditions.notNull(T, String)`.

**Comment by ephemient** [comment] 2022-08-18 19:52
Please reconsider.

**Comment by marcphilipp** [comment] 2023-04-28 07:21
@awelless see #1866

**Comment by awelless** [comment] 2023-04-28 12:47
@marcphilipp
I noticed this issue first. I think, it can be closed as a duplicate of #1866

**Comment by marcphilipp** [comment] 2023-04-29 13:11
Since the original report is also specific to Kotlin I think you're right. 👍

**Comment by marcphilipp** [comment] 2023-04-29 13:11
Duplicate of #1866

**Closed by marcphilipp** 2023-04-29 13:11 UTC
Labels: theme: programming model, status: team discussion, component: Jupiter
