### ISSUE TITLE
Document semantics for a disabled test regarding class-level callbacks

### ISSUE THREAD

**Issue by siddhsql** [junit-team/junit5#3649] opened 2024-01-19 20:34 UTC
## Steps to reproduce

This is my test case:

```java
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class RestApiApplicationTests {
  // @Disabled does not work:
  // https://stackoverflow.com/questions/52054577/disabled-is-not-working-in-junit5
  // https://stackoverflow.com/questions/52602351/junit-5-disabled-is-ignored
  @Test
  @Disabled("")
  void contextLoads() {}
}
```

## Expected

Test should NOT run with `mvn test` (using maven surefire plugin 3.2.5).

## Observed

Test is executed even though it is marked as disabled.

## Additional Info

In another project the `@Disabled` annotation does work, but not in this one.

## Context

 - Used versions (Jupiter/Vintage/Platform):

```
[INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.9.3:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-api:jar:5.9.3:test
[INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] +- org.junit.jupiter:junit-jupiter-params:jar:5.9.3:test
[INFO] +- org.junit.platform:junit-platform-launcher:jar:1.9.3:test
[INFO] +- org.junit.platform:junit-platform-console-standalone:jar:1.10.1:test
[INFO] +- org.junit.platform:junit-platform-commons:jar:1.9.3:test
[INFO] +- org.junit.platform:junit-platform-engine:jar:1.9.3:test
[INFO] |  \- org.opentest4j:opentest4j:jar:1.2.0:test
```

 - Build Tool/IDE:

Maven

**Comment by sbrannen** [comment] 2024-01-21 13:38
For starters, you should not have a dependency on `org.junit.platform:junit-platform-console-standalone:jar:1.10.1` in your build, especially not alongside JUnit 5.9.3/1.9.3 artifacts.

What makes you think the test is executed? Does Maven log that the test method was actually run? Or does it merely show that the test class was run? Perhaps the test method is marked as skipped?

If removing the dependency on the `junit-platform-console-standalone` artifact does not resolve the issue for you, please provide a minimal sample application that demonstrates the problem -- for example, something that we can download and run such as a JAR attached to this issue or a public Git repository that we can clone.

In light of the above, I am closing this issue; however, please do report back here if you think you have found a bug and provide us a sample that reproduces it.

Thanks

**Comment by siddhsql** [comment] 2024-01-21 20:40
On Sun, Jan 21, 2024 at 5:38 AM Sam Brannen ***@***.***>
wrote:

> For starters, you should not have a dependency on
> org.junit.platform:junit-platform-console-standalone:jar:1.10.1 in your
> build, especially not alongside JUnit 5.9.3/1.9.3 artifacts.
>

i removed it.

> What makes you think the test is executed? Does Maven log that the test
> method was actually run?
>

Yes. other people have also reported the same. refer SO links.

> Or does it merely show that the test class was run? Perhaps the test
> method is marked as skipped?
>
> If removing the dependency on the junit-platform-console-standalone
> artifact does not resolve the issue for you, please provide a minimal
> sample application that demonstrates the problem -- for example, something
> that we can download and run such as a JAR attached to this issue or a
> public Git repository that we can clone.
>
MRE provided in the ticket.

**Comment by sbrannen** [comment] 2024-01-22 09:09
> MRE provided in the ticket. 

As I mentioned above, we need something that we can download and run such as a ZIP attached to this issue or a public Git repository that we can clone.

Pasting snippets in comments is not sufficient since the entire build configuration affects the outcome.

**Comment by siddhsql** [comment] 2024-01-22 17:43
You can close the ticket. it works. in my case the issue is that there is some code that is related to Spring which still executes (even though the test is "skipped") but I think that qualifies to be debugged as a separate issue.

**Comment by sbrannen** [comment] 2024-01-24 15:41
Thanks for providing that feedback, @siddhsql.

> in my case the issue is that there is some code that is related to Spring which still executes (even though the test is "skipped") but I think that qualifies to be debugged as a separate issue.

This is what I was asking about in https://github.com/junit-team/junit5/issues/3649#issuecomment-1902632530.

If you want to ensure that Spring and other extensions do not perform any setup for a test class, you need to disable the entire test class. Disabling only a test method will not prevent class-level extension callbacks from being invoked.

This is alluded to in the class-level [Javadoc for `@Disabled`](https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/Disabled.html):

> When applied at the method level, the presence of this annotation does not prevent the test class from being instantiated. Rather, it prevents the execution of the test method and method-level lifecycle callbacks such as `@BeforeEach` methods, `@AfterEach` methods, and corresponding extension APIs.

**Closed** 2024-01-25 13:57 UTC
Labels: theme: extensions, theme: programming model, theme: documentation, component: Jupiter
