### ISSUE TITLE
Add a parameter to allow @TestMethodOrder to enforce unique order

### ISSUE THREAD

**Issue by fll02020** [junit-team/junit5#2930] opened 2022-05-28 21:13 UTC
I encountered the same problem as #2757 , in some scenarios I hope that the order I fill in is different, but in fact when faced with a large number of tests, sometimes I can't guarantee this, so I hope to get a boolean switch to detect all of this. At the same time I don't want to do it by adding a class as described in the previous issue, because it actually means that if I have other sorting methods in the future that I also want to have this functionality, I have to add an extra for this sorting method A class for the enforce state. So I tried adding a boolean enforceUniqueOrder switch to do it, I guess it's easier to manage and use

**Comment by marcphilipp** [comment] 2024-10-14 14:36
Duplicate of #2757

**Closed by marcphilipp** 2024-10-14 14:36 UTC
Labels: status: duplicate, theme: ordering, component: Jupiter, theme: discovery
