### ISSUE TITLE
Cannot execute nested suites

### ISSUE THREAD

**Issue by phoenix384** [junit-team/junit5#1520] opened 2018-08-03 11:51 UTC
When I create a suite like this:

```java
@RunWith(JUnitPlatform.class)
@SelectClasses(SimpleTest.class)
public class Suite1 {
}
```

I can execute this suite e.g. with Eclipse.

But if I nest this suite inside another, like this:

```java
@RunWith(JUnitPlatform.class)
@SelectClasses(Suite1.class)
public class Suite2 {
}
```

nothing is executed.

Using the console launcher I can't even execute `Suite1`:

```
[java] '-- JUnit Jupiter [OK]
[java]
[java] Test run finished after 31 ms
[java] [         1 containers found      ]
[java] [         0 containers skipped    ]
[java] [         1 containers started    ]
[java] [         0 containers aborted    ]
[java] [         1 containers successful ]
[java] [         0 containers failed     ]
[java] [         0 tests found           ]
[java] [         0 tests skipped         ]
[java] [         0 tests started         ]
[java] [         0 tests aborted         ]
[java] [         0 tests successful      ]
[java] [         0 tests failed          ]
```

(Versions: JUnit Jupiter 5.2.0, Platform 1.2.0)

With JUnit 4 this was possible.

**Comment by nicolaiparlog** [comment] 2018-08-03 12:22
Just to clarify, you are running this test [as part of JUnit 4](https://junit.org/junit5/docs/current/user-guide/#running-tests-junit-platform-runner), right? Do you have to do that or could you switch to running tests with JUnit 5 - with regards to Jupiter tests, that would make your life easier.

**Comment by sbrannen** [comment] 2018-08-03 13:07
Execution of nested suites using the `JUnitPlatform` runner is not supported by design, in order to avoid infinite recursion:

https://github.com/junit-team/junit5/blob/87bed874647c9425bc825b3eff4629fda82a993a/junit-vintage-engine/src/main/java/org/junit/vintage/engine/discovery/DefensiveAllDefaultPossibilitiesBuilder.java#L96-L115

Given the above, I still would have expected a warning to be logged.

When running a suite that selects a nested suite on the JUnit Platform, there is in fact a log message; however, when running the same suite that selects a nested suite on JUnit 4, I do not see a log message.

So perhaps we should see if we can improve diagnostics there.

**Comment by sbrannen** [comment] 2018-08-03 13:16
FWIW, if you select non-suite test classes alongside the suite class as follows, you will see that the non-suite classes do get executed.

```java
@RunWith(JUnitPlatform.class)
@SelectClasses({ Suite1.class, SimpleTest.class })
public class Suite3 {
}
```

So it's not the case that "nothing is executed", but I can confirm that the _nested suited_ does in fact get silently ignored.

**Comment by sbrannen** [comment] 2018-08-03 13:18
Tentatively slated for 5.3 RC1, but only for _team discussion_ and triaging.

**Comment by phoenix384** [comment] 2018-08-05 15:37
I have to annotate the suites with @RunWith(JUnitPlatform.class) to be able to execute them with Eclipse.
But I also need to be able to execute nested suites or I will never be able to switch to JUnit 5.

Also I want to repeat from my first comment that I wasn't able to execute Suite1 using the Console Launcher.

**Comment by marcphilipp** [comment] 2018-08-06 13:05
> So it's not the case that "nothing is executed", but I can confirm that the _nested suites_ does in fact get silently ignored (when launching the top-level suite via JUnit 4 in Eclipse).

@sbrannen What do you mean by nested? Your example `Suite3` includes `Suite1`. Did you mean to reference `Suite2` instead?

**Comment by sbrannen** [comment] 2018-08-06 13:08
Yes, I was referring to the fact that `Suite3` _asks_ for `Suite1` to be executed as well.

So in a sense, `Suite` is _nested_ under `Suite3`.

That's the term used by the OP as well, but we can come up with better terminology if you think "nested" does not describe the scenario well. 😉

**Comment by sbrannen** [comment] 2018-08-06 13:10
I think somebody else referred to this construct as "suites with arbitrary levels".

**Comment by marcphilipp** [comment] 2018-08-06 13:18
Now I'm confused. 🤔 

Given the following (slightly modified) classes, when executing `Suite3` via JUnit 4 we warn for `Suite2`, but not for `Suite1` which is fine IMHO.

```java
@RunWith(JUnitPlatform.class)
@SelectClasses(SimpleTest.class)
public class Suite1 {
}
```

```java
@RunWith(JUnitPlatform.class)
@SelectClasses(Suite1.class)
public class Suite2 {
}
```

```java
@RunWith(JUnitPlatform.class)
@SelectClasses(Suite2.class)
public class Suite3 {
}
```

**Comment by sbrannen** [comment] 2018-08-06 13:30
Ummm.... so you're saying that the execution of `Suite3` _ignores_ everything from `Suite2` and `Suite1`?

And that you get a warning about `Suite2` being ignored but not about `Suite1` being ignored?

If so, then that would appear to be different from what I observed.

Maybe I need to test it again. 😉

**Comment by sbrannen** [comment] 2018-08-06 13:33
I'm about to check in these examples in an "issue" branch so that we know we're talking about the same thing...

**Comment by sbrannen** [comment] 2018-08-06 13:49
> Given the following (slightly modified) classes, when executing `Suite3` via JUnit 4 we warn for `Suite2` but not for `Suite1` which is fine IMHO.

@marcphilipp, how are you executing the tests? Did you configure anything special regarding logging (log level, log manager, etc.)?

**Comment by sbrannen** [comment] 2018-08-06 13:55
OK, here's the "issue" branch:

https://github.com/junit-team/junit5/compare/issues/1520-nested-suites

**Comment by sbrannen** [comment] 2018-08-06 13:58
So... when I execute `TestSuite3` from that branch in Eclipse 4.7.3 (with `-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager` set), no tests are executed, and the only log output I see is the following.

```
15:56:54.046 [main] CONFIG org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry - Discovered TestEngines with IDs: [junit-jupiter (group ID: org.junit.jupiter, artifact ID: junit-jupiter-engine, version: DEVELOPMENT, location: file:/Users/sbrannen/source/junit5/junit-jupiter-engine/bin/main/org/junit/jupiter/engine/JupiterTestEngine.class), junit-vintage (group ID: org.junit.vintage, artifact ID: junit-vintage-engine, version: DEVELOPMENT, location: file:/Users/sbrannen/source/junit5/junit-vintage-engine/bin/main/org/junit/vintage/engine/VintageTestEngine.class)]
15:56:54.060 [main] CONFIG org.junit.platform.launcher.core.ServiceLoaderTestExecutionListenerRegistry - Loaded TestExecutionListener instances: [org.junit.platform.launcher.listeners.NoopTestExecutionListener@28d18df5]
```

**Comment by phoenix384** [comment] 2018-08-06 14:02
I am using a modern version of Eclipse (Photon). But without `@RunWith(JUnitPlatform.class)` "Run as JUnit Test" is not selectable from the context menu. Running the class via "Run configurations" explicitly with the JUnit5 test runner leads to "No tests found".
So I thought the RunWith annotation is still necessary.

**Comment by sbrannen** [comment] 2018-08-06 14:17
Hi @phoenix384,

> I am using a modern version of Eclipse (Photon). But without `@RunWith(JUnitPlatform.class)` "Run as JUnit Test" is not selectable from the context menu. 

If the _class_ you're attempting to run as a test class does not contain any methods such as `@Test`, `@TestFactory`, `@RepeatedTest`, `@ParameterizedTest`, or `@TestTemplate`, then that is the expected behavior. All of those annotations are meta-annotated with `@Testable`, and Eclipse looks for `@Testable` methods to determine if the test class can be executed as a "JUnit 5 Test".

> Running the class via "Run configurations" explicitly with the JUnit5 test runner leads to "No tests found".

If the _class_ you are referring to is one of your `Suite` classes that does not contain any `@Testable` methods, then that is to be expected.

As I mentioned before, a class annotated with `@RunWith(JUnitPlatform.class)` cannot be run on the JUnit Platform (a.k.a., JUnit 5).

> So I thought the RunWith annotation is still necessary.

It's unfortunately a bit tricky.

1. If you want to run JUnit Jupiter tests in Eclipse Photon, you do **not** need `@RunWith(JUnitPlatform.class)`, and it is in fact not supported.
2. If you want to run a _suite_ on the JUnit Platform, the only option currently is to use `@RunWith(JUnitPlatform.class)`, but you **must** run that class as a JUnit 4 Test class.

Again, first-class support for suites on the JUnit Platform will come with #744.

**Comment by phoenix384** [comment] 2018-08-06 14:44
I am not talking about executing test classes. That works.
This issue is only about executing suites.

>> I have to annotate the suites with @RunWith(JUnitPlatform.class) to be able to execute them with Eclipse.
>
> That only applies to old versions of Eclipse.
>
> Since Eclipse 4.7.1a, JUnit Platform support is built in. Thus, you should not be using
> @RunWith(JUnitPlatform.class) in a modern version of Eclipse.

vs.

> If you want to run a suite on the JUnit Platform, the only option currently is to use
> @RunWith(JUnitPlatform.class), but you must run that class as a JUnit 4 Test class.

I'm confused, that is a contradiction.
In fact it is not possible for me to execute suites right now since Eclipse needs `@RunWith(JUnitPlatform.class)` but does not execute nested suites and the Console Launcher (just tested it again) does not execute the suite at all (with or without `@RunWith(JUnitPlatform.class)`).
Is that correct?

**Comment by marcphilipp** [comment] 2018-08-07 17:57
I added a [`JUnit4Executor`](https://github.com/junit-team/junit5/blob/issues/1520-nested-suites/platform-tests/src/test/java/org/example/JUnit4Executor.java) class to Sam's branch that prints the following when executing the main method, regardless of the used IDE:

```
Running org.example.TestSuite1
> Test started: test1()(Test1)
> Test started: JUnit Vintage
Tests run: 2

Running org.example.TestSuite2
Aug 07, 2018 7:50:53 PM org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder$DefensiveAnnotatedBuilder buildRunner
WARNING: Ignoring test class using JUnitPlatform runner: org.example.TestSuite1
Aug 07, 2018 7:50:53 PM org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder$DefensiveAnnotatedBuilder buildRunner
WARNING: Ignoring test class using JUnitPlatform runner: org.example.TestSuite1
> Test started: JUnit Jupiter
> Test started: JUnit Vintage
Tests run: 2

Running org.example.TestSuite3
Aug 07, 2018 7:50:53 PM org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder$DefensiveAnnotatedBuilder buildRunner
WARNING: Ignoring test class using JUnitPlatform runner: org.example.TestSuite2
Aug 07, 2018 7:50:53 PM org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder$DefensiveAnnotatedBuilder buildRunner
WARNING: Ignoring test class using JUnitPlatform runner: org.example.TestSuite2
> Test started: JUnit Jupiter
> Test started: JUnit Vintage
Tests run: 2

Running org.example.TestSuite4
Aug 07, 2018 7:50:53 PM org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder$DefensiveAnnotatedBuilder buildRunner
WARNING: Ignoring test class using JUnitPlatform runner: org.example.TestSuite1
Aug 07, 2018 7:50:53 PM org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder$DefensiveAnnotatedBuilder buildRunner
WARNING: Ignoring test class using JUnitPlatform runner: org.example.TestSuite1
> Test started: test2()(Test2)
> Test started: JUnit Vintage
Tests run: 2
```

So, the Vintage engine actually warns twice about the ignored classes (because we call `Launcher.discover()` when creating the `Runner`, and `Launcher.execute()` when executing it. The duplicate message is slightly annoying but ok for an interim solution IMHO.

@sbrannen I'm inclined to close this issue as "works-as-designed". WDYT?

**Comment by sbrannen** [comment] 2018-08-08 13:35
> So... when I execute `TestSuite3` from that branch in Eclipse 4.7.3a (with `-Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager` set), no tests are executed, and the only log output I see is the following.

I apologize: I must have misconfigured the logging when I ran that.

When I run that now within Eclipse with `<Logger name="org.junit.vintage.engine" level="warn" />`, I actually see the following:

```
15:33:12.088 [main] WARN  org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder - Ignoring test class using JUnitPlatform runner: org.example.TestSuite2
15:33:12.134 [main] WARN  org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder - Ignoring test class using JUnitPlatform runner: org.example.TestSuite2
```

So that is the warning I was expecting to see.

**Comment by sbrannen** [comment] 2018-08-08 13:35
> I'm inclined to close this issue as "works-as-designed". WDYT?

@marcphilipp, I think that's fine.

**Comment by sbrannen** [comment] 2018-08-08 13:38
@phoenix384,

> I'm confused, that is a contradiction.

You're totally right: that was a contradiction. 😱 

I apologize.

>> I have to annotate the suites with `@RunWith(JUnitPlatform.class)` to be able to execute them with Eclipse.
>
> That only applies to old versions of Eclipse.
>
> Since Eclipse 4.7.1a, JUnit Platform support is built in. Thus, you should not be using
> @RunWith(JUnitPlatform.class) in a modern version of Eclipse.

I somehow thought you wrote "tests" instead "suites" there.

**Comment by sbrannen** [comment] 2018-08-08 13:42
> In fact it is not possible for me to execute suites right now since Eclipse needs `@RunWith(JUnitPlatform.class)` but does not execute nested suites and the Console Launcher (just tested it again) does not execute the suite at all (with or without `@RunWith(JUnitPlatform.class)`).
Is that correct?

Yes, that is correct.

1. Nested suites are not supported.
2. `@RunWith(JUnitPlatform.class)` is not supported when launching the JUnit Platform via the Console Launcher since the `VintageTestEngine` does not support `@RunWith(JUnitPlatform.class)`.

The latter is also true when executing tests on the JUnit Platform via Maven Surefire, Maven Failsafe, Gradle, Eclipse, or IntelliJ.

**Comment by marcphilipp** [comment] 2018-08-08 13:48
Alright, closing this issue as "works-as-designed". We really should introduce first-class support in the Platform soon, though.

**Closed by marcphilipp** 2018-08-08 13:48 UTC
Labels: component: Platform, component: Vintage, status: team discussion, theme: diagnostics, theme: suites, type: enhancement
