### ISSUE TITLE
DisplayName with Test feature idea

### ISSUE THREAD

**Issue by rshmiraf** [junit-team/junit5#1577] opened 2018-09-05 16:10 UTC
## Overview

Hi, junit5 is a great piece of software. Today I realized while testing that a lot of time doing unit testing the `@DisplayName` is almost the same as a name of method. I mean there are many schools how the name of method should look like, but for example, let's take a look at this one below:

`methodName_StateUnderTest_ExpectedBehavior`

And here is my idea - create a flag, for example `Test(xxx=true)` or `Test(xxx="_")` or `DisplayName(xxx="_") `which will use the name of method. The final result may look like this:

`parse_WithEmptyString_ThrowIllegalArgumentException`
will be converted to
`parse with empty string throw illegal argument exception`

Let me know what you think.

**Comment by mkobit** [comment] 2018-09-05 16:30
Does https://github.com/junit-team/junit5/issues/162 address this use case?

**Comment by rshmiraf** [comment] 2018-09-05 16:35
@mkobit it is different problem but #162 would be also really useful.

His case is Nested without DisplayName (using class names).
My case is Test without DisplayName (using method names).

**Comment by sbrannen** [comment] 2018-09-05 17:14
I am closing this issue as a duplicate of #162.

#162 would introduce support for achieving this in the form of an extension, likely with a _default_ implementation that "prettifies" based on either camel-casing or underscores (or potentially both).

If you would specifically like support for splitting on underscores, please voice your opinion in #162.

Thanks

**Closed by sbrannen** 2018-09-05 17:14 UTC
Labels: component: Jupiter, theme: programming model, type: enhancement

**Comment by sbrannen** [comment] 2018-09-05 17:15
Also, just FYI... the `@Test` annotation will likely _never_ support any attributes.
