### ISSUE TITLE
SuiteTestEngine and JUnitPlatform Runner ignore tests without "Test" in class name

### ISSUE THREAD

**Issue by PashaTurok** [junit-team/junit5#2412] opened 2020-09-18 13:22 UTC
I use org.junit.platform 1.6.2 with org.junit.jupiter 5.6.2 and have two classes with integration tests `FooIT` and `TestBarIT`.

This is my configuration:

```java
    @RunWith(JUnitPlatform.class)
    @SelectClasses({ FooIT.class, TestBarIT.class })
    public class SuiteIT { }
```

However, tests in `FooIT` will be ignored if I don't add word `Test` (for example `TestFooIT`). But I don't want to add word `Test` as we have a strict naming convention for tests. 

I think this is the wrong behavior because Test classes are set explicitly - a developer sets list of classes but JUnit filters it. So, who knows better what classes to use - the developer or JUnit?

Can anyone suggest a workaround for a now to make JUnit suite accept classes without `Test` in their names or to configure it use `IT` for class checking?

**Comment by sbrannen** [comment] 2020-09-18 13:39
> Can anyone suggest a workaround for a now to make JUnit suite accept classes without `Test` in their names or to configure it use `IT` for class checking?

The [`@IncludeClassNamePatterns`](https://junit.org/junit5/docs/current/api/org.junit.platform.suite.api/org/junit/platform/suite/api/IncludeClassNamePatterns.html) and [`@ExcludeClassNamePatterns`](https://junit.org/junit5/docs/current/api/org.junit.platform.suite.api/org/junit/platform/suite/api/ExcludeClassNamePatterns.html) annotations are designed explicitly for that purpose.

For your use case, you just need to declare `@IncludeClassNamePatterns` with a pattern that supports your naming convention for test classes.

**Comment by sbrannen** [comment] 2020-09-18 13:44
JUnit Platform 1.7.0 introduced support for _executing explicitly selected classes regardless of class name filters_ (see #2270).

Thus, we could consider implementing the same behavior for the `JUnitPlatform` `Runner`.

@junit-team/junit-lambda, Thoughts?

**Comment by sbrannen** [comment] 2020-09-18 13:44
Tentatively slated for 5.8 M1 for _team discussion_

**Comment by marcphilipp** [comment] 2020-10-23 10:46
**Team decision:** Always execute explicitly selected test classes regardless of class name filters for the `JUnitPlatform` runner.

**Comment by sbrannen** [comment] 2021-08-10 10:15
This is closely related to (and potentially a duplicate of):

- #2683

**Closed** 2021-08-11 14:17 UTC
Labels: type: bug, status: in progress, component: Platform, theme: suites
