### ISSUE TITLE
Run code before all / after all tests

### ISSUE THREAD

**Issue by arturmkr** [junit-team/junit5#2415] opened 2020-09-21 14:11 UTC
Add ability to run a code before all tests and after all tests.
For example, it could be needed to prepare data before test run or clean data after the whole test run.
Annotation BeforeAll is executed only before a class, but it's needed to run code before all test run.
Similar to TestNG - BeforeSuite annotation.

As you can it's really popular issue:
https://stackoverflow.com/questions/43282798/in-junit-5-how-to-run-code-before-all-tests/51556718#51556718

People try to solve this issue by introducing variable boolean started = false;
But it's not useful, when it's needed to clean the whole db, after all tests.

**Comment by sormuras** [comment] 2020-09-21 14:21
Duplicate of #456

**Closed by sormuras** 2020-09-21 14:21 UTC
