### ISSUE TITLE
Vintage filtering is not compatible with JUnitParamsRunner

### ISSUE THREAD

**Issue by blindpirate** [junit-team/junit5#1336] opened 2018-03-20 02:23 UTC
## Overview

Seems like Vintage filtering is not compatible with the [JUnitParamsRunner](https://github.com/Pragmatists/JUnitParams). 

Step to reproduce:

- Add dependency `compile 'pl.pragmatists:JUnitParams:1.1.1'`

```java
import junitparams.*;
import org.junit.platform.engine.*;
import org.junit.platform.engine.discovery.*;
import org.junit.platform.launcher.*;
import org.junit.platform.launcher.core.*;
import org.junit.runner.RunWith;
import org.junit.Test;

public class VintageJUnitParams {
    public static void main(String[] args) {
        Launcher launcher = LauncherFactory.create();

        LauncherDiscoveryRequestBuilder requestBuilder = LauncherDiscoveryRequestBuilder.request()
                .selectors(DiscoverySelectors.selectClass(PersonTest.class))
                .filters((PostDiscoveryFilter) descriptor -> {
                    System.out.println("Exclude: " + descriptor.getUniqueId());
                    return FilterResult.excluded("excluded");
                });
        launcher.execute(requestBuilder.build());
    }

    @RunWith(JUnitParamsRunner.class)
    public static class PersonTest {
        @Test
        @Parameters({"17, false", "22, true"})
        public void personIsAdult(int age, boolean valid) throws Exception {
            System.out.println("This shouldn't be run!");
        }
    }
}
```

The tests are still executed even I exclude them in the filter. I do observe the warning `WARNING: Runner junitparams.JUnitParamsRunner (used on class VintageJUnitParams$PersonTest) was not able to satisfy all filter requests.` so I'm not sure if this is expected behavior.

Vintage version: `5.1.0`

**Comment by marcphilipp** [comment] 2018-03-20 14:01
@blindpirate Thanks for creating the issue! I've started looking into it. However, I might need a bit more time to wrap my head around it.

**Comment by blindpirate** [comment] 2018-03-20 22:56
Thanks @marcphilipp , no hurry at all :-)

**Comment by marcphilipp** [comment] 2018-03-30 09:28
After some research, I've discovered that this is actually caused by an inconsistency in the JUnitParams runner. I've opened https://github.com/Pragmatists/JUnitParams/issues/153.

**Comment by blindpirate** [comment] 2018-03-30 09:30
Cool, if you decide there's nothing to do on JUnit's side, please close this.

**Comment by Th4n** [comment] 2019-01-08 14:42
Could this be the reason why I got `TestEngine with ID 'junit-vintage' failed to discover tests` while using JUnitParamsRunner when trying to run one test only from a class?

**Comment by marcphilipp** [comment] 2019-01-13 19:43
@Th4n No, that sounds like a different issue. Could you please open a new issue with more details? 🙂

**Comment by mmorrisontx** [comment] 2020-07-21 20:12
If anyone else hits this problem in the future, I can confirm that the patch in https://github.com/Pragmatists/JUnitParams/pull/123 does actually solve the problem, but probably won't ever be merged because junitparams seems to be EOL.

**Comment by marcphilipp** [comment] 2020-07-25 11:22
@mmorrisontx Thanks for the pointer! I'm closing this issue since there's nothing we can do in the Vintage engine to fix it.

**Closed by marcphilipp** 2020-07-25 11:22 UTC
Labels: component: Vintage, status: blocked
