### ISSUE TITLE
Introduce communication link between test engine and platform extensions

### ISSUE THREAD

**Issue by baev** [junit-team/junit5#2411] opened 2020-09-18 12:56 UTC
We have a TestExecutionListener implementation that collects base information about tests, and for some of the engines, we have additional extensions that enrich that information with engine-specific data, for example for Jupiter we catch fixtures execution using InvocationInterceptor. 

Our TestExecutionListener holds the state and we need to send data from InvocationInterceptor to our TestExecutionListener. The only option available so far is to publish report entries using ExtensionContext#publishReportEntry method and process these entries in TestExecutionListener#reportingEntryPublished method. And all that smell bad

The current issues:

1) In some cases report entries are published to system out
1) Users may use report entries on it's general-purpose -- to enrich tests with some data. 

So users got spammed by our internal communication.

Jupiter API exposes ExtensionContext.Store that can be used to share data between Jupiter extensions. The solution I have in mind is to add a similar API to the platform level and expose this API for the engines. In that way the engines can support such API in their extensions to build a communication link between platform and engine extensions

**Comment by sbrannen** [comment] 2020-09-18 12:59
Tentatively slated for 5.8 M1 solely for the purpose of _team discussion_

**Comment by baev** [comment] 2020-09-18 13:21
Our current implementation for additional context:

1) [Jupiter extension](https://github.com/allure-framework/allure-java/blob/master/allure-junit5/src/main/java/io/qameta/allure/junit5/AllureJunit5.java)
2) [Platform extension](https://github.com/allure-framework/allure-java/blob/master/allure-junit-platform/src/main/java/io/qameta/allure/junitplatform/AllureJunitPlatform.java#L189)

related issues https://github.com/allure-framework/allure-java/issues/473

**Comment by marcphilipp** [comment] 2020-10-23 10:38
Duplicate of #2296

**Closed by marcphilipp** 2020-10-23 10:38 UTC
Labels: component: Jupiter, component: Platform, status: team discussion, theme: extensions, theme: reporting, type: new feature
