### ISSUE TITLE
Test doesn't fails at the first test failure

### ISSUE THREAD

**Issue by johnysv** [junit-team/junit5#3545] opened 2023-11-06 10:05 UTC
I am using SerenityBDD with Junit 5. I need my whole test to fail when one of my @Test method fails. My test looks like

package com.xxx;

import com.xxx.frp.steps.*;
import com.xxx.frp.steps.configuration.TestConfiguration;
import lombok.extern.slf4j.Slf4j;
import net.serenitybdd.annotations.*;
import net.serenitybdd.junit.spring.integration.SpringIntegrationMethodRule;
import net.serenitybdd.junit5.SerenityJUnit5Extension;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.rules.TestWatcher;
import org.junit.runner.Description;
import org.openqa.selenium.WebDriver;
import org.springframework.retry.annotation.EnableRetry;
import org.springframework.test.context.ContextConfiguration;

import static com.xxx.xx.utils.Utils.waitForNSeconds;

@Slf4j
@ExtendWith(SerenityJUnit5Extension.class)
@ContextConfiguration(classes = TestConfiguration.class)
@EnableRetry
@TestMethodOrder(MethodOrderer.MethodName.class)

public class UJTest {

    @Rule
    public SpringIntegrationMethodRule springIntegrationMethodRule = new SpringIntegrationMethodRule();
    public static Boolean previousTestPassed = true;
    @Rule
    public TestWatcher watchman = new TestWatcher() {
        @Override
        protected void failed(Throwable e, Description description) {
            LOG.info(description.toString());
            previousTestPassed = false;
        }
    };

    @Managed(clearCookies = ClearCookiesPolicy.Never)
    public WebDriver webdriver;

    @Steps
    public LoginSteps loginSteps;

    @Test
    @Tags({@Tag("newe2eLargea"), @Tag("b"), @Tag("c")})
    @Title("HierarchyUploadAndLogin:")
    public void UserJourneyPart1_HierarchyUploadAndLogin() throws Exception {
        loginSteps.loginAsGroupManager();
    }

    @Test
    @Tags({@Tag("newe2eLargea"), @Tag("b"), @Tag("c")})
    @Title("two")
    public void UserJourneyPart2_secondPart() throws Exception {
        Assumptions.assumeTrue(previousTestPassed, "Previous test failed, hence ignored");
        loginSteps.loginAsGroupManager();
        Assert.assertTrue(false);

    }

    @Test
    @Tags({@Tag("newe2eLargea"), @Tag("b"), @Tag("c")})
    @Title("three")
    public void UserJourneyPart3_thirdPart() throws Exception {
        Assumptions.assumeTrue(previousTestPassed, "Previous test failed, hence ignored");
        loginSteps.loginAsGroupManager();

    }

But even though my test fails at second test , it executes the third one. Is there anyway I could achieve that in junit 5
}

**Comment by marcphilipp** [comment] 2023-11-06 10:57
Duplicate of #48

**Closed by marcphilipp** 2023-11-06 10:57 UTC
Labels: status: new

**Comment by johnysv** [comment] 2023-11-06 11:53
> Partially, yes. We call the feature "scenario tests", and there's an open issue with some existing extension that gets you there, most of the way: #48

@marcphilipp Whenever I use any extension class with @ExtendWith(StopOnFirstFailureExtension.class), I get nullpointer exception at @Steps
    public LoginSteps loginSteps;. Is this not supported?

![image](https://github.com/junit-team/junit5/assets/41629868/f530cba9-c695-4df0-95b7-f5df74bb05f6)
