### ISSUE TITLE
Show parameter in Maven's report of failed parameterized tests

### ISSUE THREAD

**Issue by ogregoire** [junit-team/junit5#1111] opened 2017-10-16 11:50 UTC
## Overview

- ( ) **Feature request.** When I'm writing parameterized tests, I'd expect Junit to tell me which parameterized test failed. 

For instance, the following code should tell me that it's `"def"` that's failing.

      @ParameterizedTest
      @ValueSource(strings = {"abc", "def"})
      void doSomeTest(String str) {
        assertTrue("abc".equals(str));
      }

Here's its output:

	Running hello.MyTest
	Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.123 sec <<< FAILURE! - in hello.MyTest
	doSomeTest(String)  Time elapsed: 0.013 sec  <<< FAILURE!
	org.opentest4j.AssertionFailedError: 
		at hello.MyTest.doSomeTest(MyTest.java:54)

	Results :

	Failed tests: 
	doSomeTest(String).doSomeTest(String)
	  Run 1: PASS
	  Run 2: MyTest.doSomeTest:54

I would expect the failed tests to show which parameters were given to the failing test.

Additionally, the "failed tests" list mentions `doSomeTest(String).doSomeTest(String)`, shouldn't it be `hello.MyTest.doSomeTest(String)`?

The final output should be:

	Results :

	Failed tests: 
	hello.MyTest.doSomeTest(String)
	  Run 1 ("abc"): PASS
	  Run 2 ("def"): MyTest.doSomeTest:54

Here's a repository showcasing the issue: [junit5-issue1111](https://github.com/ogregoire/junit5-issue1111)

**Comment by sormuras** [comment] 2017-10-16 17:44
Which tool do you use to execute your tests?

If you execute them via the [console launcher](http://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher) or within an IDE, you get what you expect.

**Comment by ogregoire** [comment] 2017-10-16 19:03
I'm using Maven. Good ol' plain Maven.

**Comment by luolong** [comment] 2017-10-20 08:38
Yeah. Maven reporter needs some love ...

**Comment by marcphilipp** [comment] 2017-10-29 16:13
The root cause is that Surefire does not support non-technical display names. I'm therefore closing this issue as duplicate of #990.

**Closed by marcphilipp** 2017-10-29 16:13 UTC
Labels: component: Platform, component: Surefire, status: duplicate
