### ISSUE TITLE
Introduce support for zero invocations in test templates and parameterized tests

### ISSUE THREAD

**Issue by johnchurchill** [junit-team/junit5#1477] opened 2018-06-23 19:28 UTC
## Overview

Using: JUnit: 5.2.0

Great job on the new `ParameterizedTest` support in v.5. The replacement of the static, one-per-class Parameters annotation with more flexible `MethodSource`, etc. has been like a breath of fresh air and allowed me to remove thousands (!!) of lines of supporting code from my system. I'm really loving it.
However, someone decided to disallow zero parameters with this precondition check in `ParameterizedTestExtension`.

```java
.onClose(() ->
    Preconditions.condition(invocationCount.get() > 0,
    "Configuration error: You must provide at least one argument for this @ParameterizedTest"));
```

The problem with this is that we have some testing situations where parameterized tests with zero parameters are not exceptional. For example, we run tests against thousands of a certain type of class generically against a database of past production failures, and many of these classes have never experienced a production failure. When the tests are run, we now get failures due the above precondition check. JUnit 4 handled this cleanly: it would simply not run any tests on those classes.

## Workaround

I can get around this by adding a `null` to the method creating the collection of parameters if it is empty, and then return from the beginning of the `@ParameterizedTest` method code if the passed parameter is `null`. That lets us continue to run the parameterized tests against all of the classes, but comes with some disadvantages:

- We must add specific code to the front and back of every parameterized pair just to avoid a failure that doesn't matter to the tests.
- The handling of the `null` causes the test count inflation for these "phantom" tests.
- `null` is now reserved as a signal for no parameters, rather than something wrong in the parameter creation.

## Proposal

If nobody has any strong feelings about disallowing the no-parameter case, can we just have this precondition removed from a future version?

Thanks.

**Comment by marcphilipp** [comment] 2018-06-24 11:28
@johnchurchill Could you please provide a few more details about your use case, particularly how you've written your tests? I assume it involves base classes that inherit `@ParameterizedTest` methods?

**Comment by gaganis** [comment] 2018-06-24 11:56
I have also been trying to envision what you are trying to do and was not able. 

My best guess is that you have some sort of `ArgumentsProvider` that returns no elements, but still I am not sure. If my guess is valid, this behaviour was explicitly added as a solution for #923.

It would be great if you could provide a skeleton test that exhibits your issue.

**Comment by johnchurchill** [comment] 2018-06-24 20:39
Yes, there is a superclass of all tests which does the parameter loading and execution. There are thousands of subclasses that implement all kinds of functionality. Each (non-test) class is the logic behind an interactive web page in the system. Here is a boiled-down version of that superclass:

		@ExtendWith(SpringExtension.class)
		@SpringBootTest(classes = SpringDevTestServerConfiguration.class)
		@TestExecutionListeners(listeners = { DependencyInjectionTestExecutionListener.class })
		@ComponentScan(lazyInit = true)
		@TestInstance(PER_CLASS)
		public abstract class AbstractConfigTestClass implements ApplicationContextAware {
		
			protected List<SingleConfigTestDescriptor> configTests() {
				String testClassName = this.getClass().getName();
				// remove "Test" on the end to obtain the config class
				String clzName = testClassName.substring(0, testClassName.length() - 4);
				try {
					Class configClz = Class.forName(clzName);
					List<SingleConfigTestDescriptor> params = ConfigToTestParams.getTestParameters(configClz);
					if (params.size() == 0) {
						params.add(null); // need to add null here to avoid junit 5 failing
					}
					return params;
				}
				catch (ClassNotFoundException e1) {
					throw new RuntimeException("Could not find expected class: " + clzName, e1);
				}
			}
		
			@ParameterizedTest
			@MethodSource("configTests")
			public void runTest(SingleConfigTestDescriptor test) {
				if (test == null) {
					return; // nothing to do; this is the null to avoid the junit 5 failure
				}
				// use the test data to run the test against the class
			}
		
		}

By the time we know that there are no available tests to run, it's too late.. JUnit 5 will throw an exception. There are 6 lines in there whose only purpose is to make it run successfully like it did under JUnit 4. I just started working with JUnit 5 a couple of days ago, so I haven't had the chance to look into using ArgumentsProvider. Would using ArgumentsProvider avoid the failure?

**Comment by sbrannen** [comment] 2018-06-24 21:53
In any case, we should improve the error message.

`"Configuration error: You must provide at least one argument for this @ParameterizedTest"` --> `"Configuration error: You must provide at least one invocation context for this @ParameterizedTest"`.

The difference being "argument" vs. "invocation context".

And the invocation context can still supply zero "arguments" to the method, though that's not the topic of _this_ issue.

**Comment by sbrannen** [comment] 2018-06-24 21:55
FYI: I reworded the title of this issue accordingly.

**Comment by sbrannen** [comment] 2018-06-24 22:03
Keep in mind that a `@TestTemplate` method in general cannot currently have zero invocations.

**Comment by sbrannen** [comment] 2018-06-24 22:03
In other words, see `org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.validateWasAtLeastInvokedOnce(int)`. 😉

**Comment by johnchurchill** [comment] 2018-06-24 23:07
I took a look at `TestTemplateTestDescriptor`, and yes the zero invocations would be stopped there too. I tried taking both of those preconditions out (`TestTemplateTestDescriptor` and `ParameterizedTestExtension`) and making a simple class with one `@Test` and one `@ParameterizedTest` which refers to a `@MethodSource` which returns an empty list. The result is that 1/1 tests pass (just `bar2()`), which is the same behavior we had in JUnit 4. There is no side-effect of allowing the `@ParameterizedTest` to run with no invocations.

```java
public class FooTest {

	@ParameterizedTest
	@MethodSource("data")
	void bar1(String s) {
	}

	@Test
	public void bar2() {
		// pass
	}

	public static List<String> data() {
		// pretend we have no test cases in the QA database
		return new ArrayList<>();
	}
}
```

**Comment by sbrannen** [comment] 2018-06-25 08:29
> The result is that 1/1 tests pass

In such cases, I don't think the parameterized test container should be marked as "successful".

Rather, I think we should mark the parameterized test container as "skipped" and provide a "reason" why it was skipped.

@junit-team/junit-lambda, thoughts?

**Comment by sbrannen** [comment] 2018-06-25 09:36
As a side note, since I'm the author of the _Spring TestContext Framework_...

@johnchurchill, out of curiosity, why do you disable **all** Spring test listeners except `DependencyInjectionTestExecutionListener`?

That's enabled by default.

Were other listeners somehow causing problems?

**Comment by gaganis** [comment] 2018-06-25 11:37
This case reminds me of the similar case #1298 which was handled by the `--fail-if-no-tests` cl option.

The similarity is that they both exhibit the same core dilemma:
_If I have zero elements to process, is that because the user has done some error __or__ is this lack of items actually valid and intentional?_ The error could be in configuration as in both cases or programmatic in the case of providing arguments_(invocation contexts)_.

The difference between the two is the default is reversed. 

 - In the case of the Console Launcher. In cl the default was not to fail and we added an option to change this behavior.
 - For the parameterized case we fail if zero invocation contexts.

Maybe we could take a similar approach also in the case- with some sort of flag or parameter eg on the annotation.

For me personally I think the current default to fail if no elements are present and in esense guarding against error is important. I seen many case where something was silently turned off due to error and the error was missed. 
_*Also adding a skipped note in the execution plan could be in many cases be effectively silent if it does not actually fail a test run_

**Comment by gaganis** [comment] 2018-06-25 14:37
> n any case, we should improve the error message.
> 
> "Configuration error: You must provide at least one argument for this @ParameterizedTest" --> "Configuration error: You must provide at least one invocation context for this @ParameterizedTest".
> 
> The difference being "argument" vs. "invocation context".

I don't think _invocation context_ would be more meaningful for the normal user. Though indeed it is more meaningful for someone who understands the internal of the platform. 

If you consult the relevant section in the User Guide about `ParameterizedTests` there is no mention, let alone an explanation, of "Invocation Context".

**Comment by sbrannen** [comment] 2018-06-25 14:48
Sure.... "invocation context" is very technical.

How about the following instead?

`"Configuration error: You must configure at least one set of arguments for this @ParameterizedTest"`

**Comment by sbrannen** [comment] 2018-06-25 14:53
Good points, @gaganis.

> Maybe we could take a similar approach also in the case- with some sort of flag or parameter eg on the annotation.

I tend to agree that adding an opt-in flag as a annotation attribute in `@ParameterizedTest` would be a better, more robust, and more user friendly solution.

How about the following?

```java
@ParameterizedTest(failIfNoArgumentSets = false)
```

... with the `default` being `true`.

Though, `failIfNoArgumentSets` is a bit verbose. Perhaps we can come up with something more succinct.

**Comment by sbrannen** [comment] 2018-06-25 14:55
Maybe the following is better:

```java
@ParameterizedTest(requireArguments = false)
```

**Comment by gaganis** [comment] 2018-06-25 19:14
> How about the following instead?
> 
> "Configuration error: You must configure at least one set of arguments for this @ParameterizedTest"

That is exactly was I was thinking now too :)

**Comment by sbrannen** [comment] 2018-06-26 16:01
@johnchurchill, would the following proposal suit your needs?

```java
@ParameterizedTest(requireArguments = false)
```

**Comment by sbrannen** [comment] 2018-06-26 16:07
FYI: I improved the error message in b1e533cf64bedb7ebbb8c80e9141fbb4cd515d0d.

**Comment by johnchurchill** [comment] 2018-06-26 16:30
Yes, requireArguments = false would suit my needs perfectly. I hate to see more corner-case parameters being introduced though. The simple API is what makes JUnit so approachable.

**Comment by sbrannen** [comment] 2018-06-26 19:06
> Yes, `requireArguments = false` would suit my needs perfectly.

Thanks for the feedback.

> I hate to see more corner-case parameters being introduced though. The simple API is what makes JUnit so approachable.

Well, therein lies the rub: _We can't have our cake and eat it, too._

As already pointed out, switching the behavior would no longer be user friendly regarding user configuration errors. So, IMHO, the only viable option is to make it an _opt-in_ feature while retaining backwards compatibility and upholding UX.

Of course, if anyone has any better ideas, I'm all ears.

**Comment by sbrannen** [comment] 2018-06-30 13:22
Indeed, a failed assumption in the factory method is an easy way to achieve this _without_ changes to existing APIs.

Nice idea, @marcphilipp! 👍

**Comment by marcphilipp** [comment] 2018-06-30 13:31
Actually, it was @sormuras who had the idea during yesterday’s team call. 😉

**Comment by sbrannen** [comment] 2018-06-30 13:33
Aha... well then... in case that.... @sormuras 👏

**Comment by sbrannen** [comment] 2018-07-08 11:50
> TestAbortedException is thrown, which causes an error.

Can you be more explicit about what error you see (i.e., reported for what)?

**Comment by sbrannen** [comment] 2018-07-08 11:57
Never mind. I simplified the test case as follows in order to reproduce the error locally.

```java
import java.util.List;

import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

class TestCase {

	static List<String> strings() {
		Assumptions.assumeFalse(true, "nothing to test");
		return null;
	}

	@ParameterizedTest
	@MethodSource
	void strings(String test) {
	}

}
```

**Comment by sbrannen** [comment] 2018-07-08 12:01
For the above `TestCase`, I can confirm that a failed assumption results in a failure as follows when executing against the current `master`.

Note the _suppressed_ `PreconditionViolationException: Configuration error: You must configure at least one set of arguments for this @ParameterizedTest`.

```
org.opentest4j.TestAbortedException: Assumption failed: nothing to test
	at org.junit.jupiter.api.Assumptions.throwTestAbortedException(Assumptions.java:255)
	at org.junit.jupiter.api.Assumptions.assumeFalse(Assumptions.java:191)
	at TestCase.strings(TestCase.java:10)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:515)
	at org.junit.jupiter.params.provider.MethodArgumentsProvider.lambda$1(MethodArgumentsProvider.java:46)

// omitted

	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:101)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:1)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$4(NodeTestTask.java:131)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:107)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$4(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:107)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$4(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:107)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:52)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:184)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$6(DefaultLauncher.java:152)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:166)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:145)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:92)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
	Suppressed: org.junit.platform.commons.util.PreconditionViolationException: Configuration error: You must configure at least one set of arguments for this @ParameterizedTest
		at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:280)
		at org.junit.jupiter.params.ParameterizedTestExtension.lambda$9(ParameterizedTestExtension.java:87)
		at java.base/java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323)
		at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:281)
		... 39 more

```

**Comment by marcphilipp** [comment] 2018-07-08 17:37
Works for me:

```
> Task :documentation:consoleLauncherTest
╷
├─ JUnit Jupiter ✔
│  └─ AssumptionFailureInMethodSourceTests ✔
│     └─ strings(String) ■ Assumption failed: nothing to test
└─ JUnit Vintage ✔
```

I added a test to `master` that documents the current behavior: d5df07c5992440f2c93a68ebd642b036247c406b

@johnchurchill @sbrannen Where did you see the failing test? Was it in an IDE?

**Comment by sbrannen** [comment] 2018-07-09 11:32
> Where did you see the failing test? Was it in an IDE?

That was in Eclipse Oxygen (4.7.3a).

**Comment by sbrannen** [comment] 2018-07-09 11:33
> I added a test to master that documents the current behavior

Thanks, @marcphilipp

**Comment by johnchurchill** [comment] 2018-07-09 20:44
A couple of things.

First, I am running Photon 4.8 when I got the error. But if I run the test in Gradle, the assumption (within the method source) causes the test to be **ignored**, no error. So, it seems like the issue is more a problem for the way Eclipse is running tests, not JUnit itself. But only because of the `TestAbortedException` which is thrown from within the assumption.

Second, I stumbled upon the `@TestFactory` feature in the docs and realized that it is a better paradigm for what I was doing back in JUnit 4. Instead of creating a collection of data-driven parameter objects, I should create a collection of data-driven tests. I did a quick test and returned an empty `Collection<DynamicTest>`. In both Eclipse and Gradle, no tests were executed. This really seems to be a better approach and causes no issue. It will take some time for me to get around to rewriting the test framework to use it, but right now it looks like `@TestFactory` is a real winner of a feature.

```java
	@TestFactory
	Collection<DynamicTest> testdyn() {
		return new ArrayList<>();
	}
```

**Comment by nicolaiparlog** [comment] 2018-07-29 17:33
Accidentally stumbled into this very interesting issue and discussion... @johnchurchill Are you happy with dynamic tests? If they solve your problem, can this issue be closed? Is the JUnit team still considering implementing the option on `@ParameterizedTest`?

**Comment by sbrannen** [comment] 2018-07-30 12:21
> Is the JUnit team still considering implementing the option on `@ParameterizedTest`?

This issue was assigned to the General Backlog to see if there is (eventually) significant interest from the community before outright closing it.

**Comment by johnchurchill** [comment] 2018-07-31 20:57
Yes, I am happy with the dynamic tests, although Eclipse doesn't really display them properly (it undercounts the total, so I get something like `Runs: 392/23`, and the tests themselves are unrooted), but that is just cosmetic).

I don't think the `@ParameterizedTest` should be cluttered with another parameter. It doesn't make sense to have it when the parameter data will ordinarily be static.

Thanks for the great library. It makes testing even more addictive than it was before.

**Comment by sbrannen** [comment] 2018-08-01 08:57
> Yes, I am happy with the dynamic tests, although Eclipse doesn't really display them properly (it undercounts the total, so I get something like `Runs: 392/23`, and the tests themselves are unrooted), but that is just cosmetic).

@johnchurchill, that just means you're using an old version of Eclipse. Eclipse has first-class support for JUnit 5 since Eclipse Oxygen 4.7.1a. The latest version of Eclipse (Eclipse Photon 4.8) naturally also supports JUnit 5.

Long story, short: just upgrade to the latest Eclipse release. 😉

**Comment by sbrannen** [comment] 2018-08-01 09:00
Hmmm... I just noticed that you sated:

> First, I am running Eclipse Photon 4.8

Are you certain you saw unrooted entries for dynamic tests in Eclipse Photon, b/c if so that would be a regression in Eclipse.

**Comment by johnchurchill** [comment] 2018-08-19 23:40
Sorry for the delay, I didn't notice the replies. Here is a screenshot of the JUnit tab in Eclipse Photon. Something I forgot to mention is that I am using a test suite and `@SelectPackages` with two package names. Each of the 37 test classes from those packages return 14 dynamic tests, for a total of 518. There are 37 entries under "JUnit Jupiter", and I think the 518 individual tests are all under "unrooted". Like I said, this is just cosmetic.

![image](https://user-images.githubusercontent.com/2926598/44314378-209c9500-a3de-11e8-8bf3-708e14ce7ab5.png)

**Comment by sbrannen** [comment] 2018-08-20 11:40
> I assume this has something to do with using the JUnit 4 suite support.

Yes, exactly!

That behavior is to be expected since JUnit 4's reporting infrastructure is not 100% compatible with the JUnit Platform.

As a side note, if you annotate your test suite class with `@UseTechnicalNames` you should no longer have unrooted tests; however, `@DisplayName` will then be ignored.

**Comment by pedrolamarao** [comment] 2019-02-19 21:26
I've just come to this issue after a web search.
I am using parameterized tests with Lifecycle.PER_CLASS and abstract instance source methods.
I use this technique in a TCK library meant to be specialized by providers of a certain API.
There are cases in which a particular provider supports no parameters for a certain test.
We built TCK instances with empty parameter sources as required by the Java compiler -- because source methods are abstract.
Is this a supported use case?
If so, I believe empty sources should cause no errors.

**Comment by Adrodoc** [comment] 2019-02-20 11:32
We use Paramterized Tests defined in a super interface that test certain aspects of fields in the class unter test via reflection. Unfortunately we have to use `@TestInstance(Lifecycle.PER_CLASS)` in order to get a reference to the class under test. I was really surprised to see that method sources need to be static otherwise.
We too have the issue that sometimes there is no field that is interesting for the test. This causes the test to fail.
**Something like `@ParameterizedTest(requireArguments = false)` would be great!**
Using `assumeFalse(result.isEmpty())` in the method source is a sufficient workaround, but the code is a bit ugly, because i have to convert my streams into collections, because i cant ask my stream whether it is empty and then give it to JUnit.

Here is a simplified version of what i am doing:

```java
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeFalse;
import java.lang.reflect.Field;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import org.junit.jupiter.api.MethodOrderer.Alphanumeric;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;
import com.google.common.reflect.TypeToken;

@TestMethodOrder(Alphanumeric.class)
@TestInstance(Lifecycle.PER_CLASS)
public interface FieldsHaveNullabilityAnnotationTest<U> {
  default Class<U> getClassUnderTest() {
    @SuppressWarnings("serial")
    TypeToken<U> typeToken = new TypeToken<U>(getClass()) {};
    @SuppressWarnings("unchecked")
    Class<U> classUnderTest = (Class<U>) typeToken.getRawType();
    return classUnderTest;
  }

  default Field[] allFields() {
    Field[] result = getClassUnderTest().getDeclaredFields();
    assumeFalse(result.length == 0, "No fields found"); // Workaround for https://github.com/junit-team/junit5/issues/1477
    return result;
  }

  @ParameterizedTest
  @MethodSource("allFields")
  default void test(Field field) {
    assertTrue(field.isAnnotationPresent(Nullable.class) || field.isAnnotationPresent(Nonnull.class));
  }
}
```

I can then use this interface in all my unit tests:
```java
public class Pojo {
  String string;
}

public class PojoTest implements FieldsHaveNullabilityAnnotationTest<Pojo> {
  // ...
}
```

**Comment by sormuras** [comment] 2019-02-21 09:35
I'd resort to https://junit.org/junit5/docs/current/user-guide/#writing-tests-dynamic-tests here. Something like this:

```java
class PojoTest implements FieldsHaveNullabilityAnnotationTest<Pojo> {
  @Override
  public Class<Pojo> getClassUnderTest() {
    return Pojo.class;
  }
}

class Pojo {
  String string;
}

@Retention(RetentionPolicy.RUNTIME)
@interface X {}

interface FieldsHaveNullabilityAnnotationTest<U> {
  Class<U> getClassUnderTest();

  @TestFactory
  default Stream<DynamicTest> testAllFields() {
    return Arrays.stream(getClassUnderTest().getDeclaredFields()).map( field ->
            DynamicTest.dynamicTest(field.getName(), () -> field.isAnnotationPresent(X.class))
    );
  }
}
```

**Comment by quiram** [comment] 2020-04-21 17:59
> > Is the JUnit team still considering implementing the option on `@ParameterizedTest`?
> 
> This issue was assigned to the General Backlog to see if there is (eventually) significant interest from the community before outright closing it.

I'd like to express my interest on this. I just found this thread after having experienced the issue myself. My use case, in case it helps, is as follows:

- We have a class with a number of subclasses that do certain operations (akin to a Command Pattern).
- All the child classes have certain mandatory options and certain optional options.
- We have an abstract base class for testing where one test goes over the mandatory options and the other over the optional options. This is done, like others have shown, using non-static `@MethodSource` and a `PER_CLASS` lifecycle.
- For each of the child classes (the "commands"), there is a test class that extend the abstract base class, providing an implementation for the `@MethodSource` references.
- For the first time today, we have a command that has no optional options, all of them are mandatory. This means the relevant method source is to return an empty set of arguments, which JUnit is not allowing.

Being able to use `@ParameterizedTest(requireArguments = false)` would be fantastic.

**Comment by marcphilipp** [comment] 2020-04-21 18:05
@quiram In the meantime, how about implementing a custom `ExecutionCondition` or using `@EnabledIf` (introduced in 5.7 M1)?

**Comment by quiram** [comment] 2020-04-22 09:57
Thanks @marcphilipp. Those are good suggestions, but maybe slightly heavy-handed for my case (or at least I cannot think of a simple way to leverage them). For now I'll use the `assumeFalse()` workaround mentioned above and I'll keep an eye on the evolution of this thread.

Thanks for your effort guys 🙂

**Comment by stellingsimon** [comment] 2021-05-13 19:32
@stalebot, this is still an issue I'd like to see a solution for.

**Comment by jbduncan** [comment] 2022-07-13 10:36
This sounds useful to me, so I'm wondering if this issue should be re-opened?

**Comment by mauromol** [comment] 2024-01-26 08:03
I've also stumbled upon this. I would really like to have a `requireArguments = false` attribute on the `@ParameterizedTest` annotation.

**Comment by sbrannen** [comment] 2024-01-26 09:22
Thanks for all of the comments, everyone!

We will discuss this topic again within the team.

**Comment by mischa-n** [comment] 2024-01-30 06:50
Regarding [the comment](#issuecomment-399873053)
> It's a breaking change in the sense that configuration errors previously caused the parameterized test container to fail; whereas, now such configuration errors would be silently ignored.

I can hardly imagine such a configuration error, can you name one?

**Comment by sbrannen** [comment] 2024-01-31 15:50
> I can hardly imagine such a configuration error, can you name one?

Yes.

```java
@ParameterizedTest
@ValueSource(strings = {})
void test(String str) {
}
```

That's an obvious user/configuration error.

**Comment by sbrannen** [comment] 2024-01-31 16:04
**Team Decision**

- Allow a `TestTemplateInvocationContextProvider` to signal that it may return an empty `Stream` from `provideTestTemplateInvocationContexts()` -- likely via a new `default` method which returns `false` and can be overridden in concrete implementations.
- Provide an attribute in `@ParameterizedTest` which allows the user to signal that zero invocations are permissible -- for example, `requireArguments = false` (where `requireArguments` defaults to `true`) as mentioned previously in the discussions in this issue.

**Comment by nskvortsov** [comment] 2024-07-12 13:12
We would also benefit from this fix. Is any help required here?

**Comment by marcphilipp** [comment] 2024-07-15 05:56
@nskvortsov A PR implementing the above team decision would be welcome!

**Comment by nskvortsov** [comment] 2024-07-17 18:56
Here it is 🙂,
Hope it helps.

**Comment by nskvortsov** [comment] 2024-07-26 12:22
Can I help in any way to proceed with code review of the pull request?

**Comment by marcphilipp** [comment] 2024-07-26 15:42
No, I don't think so. It's just a matter of someone from the core team taking a proper look.

**Comment by nskvortsov** [comment] 2024-08-21 15:51
Dear team, I would be happy to improve my pull request. Please give me some feedback on it )

**Comment by marcphilipp** [comment] 2024-09-23 07:24
@nskvortsov Sorry for the delay! I have reviewed the PR just now.

**Closed** 2024-10-15 09:14 UTC
Labels: type: enhancement, component: Jupiter, theme: parameterized tests

**Comment by JonasJebing** [comment] 2024-11-18 12:48
With #3708 (#4045) adding `argumentCountValidation` to `@ParameterizedTest`, I feel like there is a bit lack of clarity for users about what `requireArguments` does compared to `argumentCountValidation`. Specifically, I think it's not very clear which of these applies to arguments within an argument set and which applies to argument sets, if that is even the right wording.

@marcphilipp since you worked on both PRs, what's your opinion on this?
Maybe, it'd make sense to rename `requireArguments` to `requireArgumentSets` and improve the docs? Or it's not that big of a deal. I'm not sure.

For context these are the two fields in  `@ParameterizedTest`: https://github.com/junit-team/junit5/blob/490e663244d506223d9e7b2aa1864576e44446cd/junit-jupiter-params/src/main/java/org/junit/jupiter/params/ParameterizedTest.java#L295-L325

**Comment by marcphilipp** [comment] 2024-11-19 10:03
@JonasJebing Thanks for pointing this out! Seeing them next to each other, I get your point. I've created #4137 to address this.
