### ISSUE TITLE
Add @FieldSource for @ParameterizedTest

### ISSUE THREAD

**Issue by PashaTurok** [junit-team/junit5#2456] opened 2020-10-21 17:48 UTC
For @ParameterizedTest we can use @MethodSource. Consider the following example:
```

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class Test {
     
    private List<String> sources;
    
    @BeforeAll
    public void prepareSources() {
        //adding values to sources
    }
   
    @ParameterizedTest
    @MethodSource("provideSources")
    public void testIt(String str) {
        //....
    }
    
    public List<String> provideSources() {
        return sources;
    }
}
```

So, maybe we should add @FieldSource that will allow to have a reference to field?

```
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class Test {
     
    private List<String> sources;
    
    @BeforeAll
    public void prepareSources() {
        //adding values to sources
    }
   
    @ParameterizedTest
    @FieldSource("sources")
    public void testIt(String str) {
        //....
    }
}
```

**Comment by sbrannen** [comment] 2020-10-21 17:54
Closing as duplicate of #2014.

Feel free to participate in the discussion there or up-vote the issue.

**Closed by sbrannen** 2020-10-21 17:54 UTC
