### ISSUE TITLE
Gradle test runner does not display names for parameterized tests

### ISSUE THREAD

**Issue by vlsi** [junit-team/junit5#2041] opened 2019-10-04 21:21 UTC
The full name of `@ParameterizedTest` is never printed in Gradle output.

Reproducer: https://github.com/junit-team/junit5-samples/pull/116

That really hurts.
I can add relevant information to the `Assertions.assert...(..., message=...)`, however, it won't be printed in case the test fails with NPE in the middle :-/

**Comment by marcphilipp** [comment] 2019-10-05 08:59
Duplicate of https://github.com/gradle/gradle/issues/5975

**Closed by marcphilipp** 2019-10-05 08:59 UTC

**Comment by marcphilipp** [comment] 2019-10-05 09:05
I know this isn't great and by all means should be improved in Gradle. For now, I can only say please vote for gradle/gradle#5975 to be resolved. FWIW the display names are shown in the HTML report.

<img width="694" alt="Screenshot 2019-10-05 at 11 02 52" src="https://user-images.githubusercontent.com/214207/66252795-0186d100-e760-11e9-99b2-fba77d85af8b.png">

**Comment by vlsi** [comment] 2019-10-05 09:09
I see, thank you.

However the key problem for me is analyzing CI failures, and html is not always available there

**Comment by marcphilipp** [comment] 2019-10-05 09:29
As a temporary workaround you could do this:

```gradle
test {
	useJUnitPlatform()
	afterTest { descriptor, result ->
		println "\n$descriptor.className [$descriptor.classDisplayName] > $descriptor.name [$descriptor.displayName]: $result.resultType"
	}
}
```

**Comment by vlsi** [comment] 2019-10-05 11:19
Just in case, it is a bit harder in Kotlin DSL: https://github.com/gradle/gradle/issues/5431

**Comment by marcphilipp** [comment] 2019-10-05 12:41
Yes, for Kotlin you'll have to do it like this or use a `TestListener`:

```kotlin
tasks.test {
	useJUnitPlatform()
	afterTest(KotlinClosure2<TestDescriptor, TestResult, Any>({ descriptor, result ->
		val test = descriptor as TestDescriptorInternal
		println("\n${test.className} [${test.classDisplayName}] > ${test.name} [${test.displayName}]: ${result.resultType}")
	}))
}
```

**Comment by vlsi** [comment] 2019-10-05 12:52
What should be the imports then?

I guess jupiter's TestDescriptor is not on the classpath(need to
doublecheck), and Gradle's one does not have getDisplayName()

Vladimir

>

**Comment by checketts** [comment] 2019-10-08 21:28
@vlsi The only import that was required for me was `import org.gradle.api.internal.tasks.testing.TestDescriptorInternal`

**Comment by vlsi** [comment] 2019-10-09 09:16
@checketts , it is often the case that `test.className` is full class name (package + class), while  `test.classDisplayName` is just simple class name.

So I used just full class name when `test.classDisplayName` adds nothing:

```kotlin
val classDisplayName = test.className?.let {
    if (it.endsWith(test.classDisplayName)) it else "${test.className} [${test.classDisplayName}]"
} ?: test.classDisplayName
```

**Comment by christophsturm** [comment] 2019-10-23 09:50
if the workaround can do it that shows that the data is actually there. why can't the gradle test plugin do the same?

**Comment by vlsi** [comment] 2019-10-23 10:34
The fix has already been merged: https://github.com/gradle/gradle/pull/11026
