### ISSUE TITLE
Disabled @TestTemplate and @TestFactory methods not marked as skipped in IDEs

### ISSUE THREAD

**Issue by HelgeStenstrom** [junit-team/junit5#1706] opened 2018-12-19 14:53 UTC
## Overview

**Expected:** The test with annotations `@ParameterizedTest`, `@CsvSource`, and `@Disabled` should be ignored by the test suite. 

**Actual behavior:** The test is marked as Pass by IntelliJ.

## Steps to reproduce

Using the following `IgnoreBugDemo` test class in IntelliJ with JUnit 5.3, run the test, and observe how the first test is ignored, but the second test is marked as Pass.

```java

package demo;

import static org.junit.jupiter.api.Assertions.fail;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

public class IgnoreBugDemo {

	@Test
	@Disabled
	void shouldBeMarkedAsIgnored_1() {
		fail("This should fail when run.");
	}

	@ParameterizedTest
	@CsvSource({ "1" })
	@Disabled
	void shouldBeMarkedAsIgnored_2(int i) {
		fail("This should fail when run, but it succeeds according to IntelliJ + JUnit 5");
	}

}
```

## Context

 - Used versions (Jupiter/Vintage/Platform): JUnit 5.3.1 (via Maven)

 - Build Tool/IDE:

```
IntelliJ IDEA 2018.3.1 (Community Edition)
Build #IC-183.4588.61, built on December 4, 2018
JRE: 1.8.0_152-release-1343-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by sbrannen** [comment] 2018-12-19 15:00
Thanks for raising the issue!

I can confirm that Eclipse IDE also does _not_ display the `@ParameterizedTest` as _disabled_.

So, this is either an issue with JUnit 5 (i.e., Jupiter or Platform) _or_ with IntelliJ and Eclipse.

**Comment by sbrannen** [comment] 2018-12-19 15:01
Tentatively slated for 5.4 M1 for _team discussion_ and further investigation.

**Comment by sbrannen** [comment] 2018-12-19 15:06
Actually, this behavior can be observed for any `@TestTemplate` (e.g., `@ParameterizedTest`, `@RepeatedTest`, etc.).

**Comment by sbrannen** [comment] 2018-12-19 15:13
Further analysis reveals that the same behavior can be observed for any _testable_ method that is a _container_.

The following updated test class demonstrates this for `@TestFactory` methods as well (at least in Eclipse).

```java

package demo;

import static org.junit.jupiter.api.Assertions.fail;

import java.util.stream.Stream;

import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestFactory;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

public class DisabledTestableMethodsTests {

	@Disabled
	@Test
	void test() {
		fail("should have been disabled");
	}

	@Disabled
	@ParameterizedTest
	@ValueSource(ints = 1)
	void parameterizedTest(int i) {
		fail("should have been disabled, but succeeds according to IntelliJ and Eclipse");
	}

	@Disabled
	@RepeatedTest(2)
	void repeatedTest(int i) {
		fail("should have been disabled, but succeeds according to IntelliJ and Eclipse");
	}

	@Disabled
	@TestFactory
	Stream<DynamicTest> testFactory() {
		fail("should have been disabled, but succeeds according to IntelliJ and Eclipse");
		return Stream.empty();
	}

}
```

**Comment by marcphilipp** [comment] 2018-12-19 15:17
There's a test for that:

https://github.com/junit-team/junit5/blob/8f2579087902dcbbc6931707312d798a6843a079/junit-jupiter-engine/src/test/java/org/junit/jupiter/engine/TestTemplateInvocationTests.java#L223-L233

Thus, I'm afraid that's a bug in IntelliJ and Eclipse.

@noopur2507 @akozlova Could you please have a look?

**Comment by akozlova** [comment] 2018-12-19 18:41
IDEA shows the suite as ignored if it has at least one child. When suite is empty, IDEA treats it as passed. To me it's not clear if disabled parameterized test should skip discover phase as well... If the children would be discovered, then the suite would get the correct status.In other words there is no status SKIPPED for suites, suite gets the status if any of it's children was skipped

**Comment by noopur2507** [comment] 2018-12-21 11:10
Note that running the given test class in Eclipse does _not_ show the disabled container methods as _passed_ which was the originally reported issue here. Instead, Eclipse shows the disabled container methods as not started (with no status). This is because Eclipse sets the status of a container as the combined result of its children. In this case, the container method did not get any status notification from a child test case and hence it is not shown as skipped.

**Comment by sbrannen** [comment] 2019-01-04 11:49
**Team Decision**: JUnit correctly reports disabled `@TestTemplate` and `@TestFactory` methods as _skipped_. Consequently, IDEs, build tools, and reporting frameworks are responsible for displaying the _skipped_ status accordingly. 

We are therefore closing this issue.

If you find that IDEs, build tool, or reporting framework does not display such scenarios correctly, please contact the authors of the tool.

**Closed by sbrannen** 2019-01-04 11:49 UTC
Labels: component: Jupiter, component: Platform, status: team discussion, theme: reporting, type: bug
