### ISSUE TITLE
[FR] Mark tests preconditions / dependencies

### ISSUE THREAD

**Issue by Hu1buerger** [junit-team/junit5#2774] opened 2021-11-07 18:15 UTC
Assume you are testing a FIFO-Queue. 

In that case you can  imagine writing these two abstract test cases:

```java
 testPush:
  q = Queue()

  q.push(1)
  // do some testing, assertions

 testPull:
  q = Queue()
  q.push(1)
  // finished the setup
  
  e = q.pull()
  // test the desired behavior
```

Lets assume that push is faulty. The test results would indicate that both testcases are faulty. The report is not conclusive about what tested behavior is faulty. Without reading and inspecting the tests no real conclusions could be made.

### Proposal:

Therefore I propose the following behavior.

```java
 @DependsOn("testPush")
 testPull:
  [...]
```

The annotation I propose kinda behaves like the conditional execution already implemented. And the resolution of the test should also be implemented as `MethodSource` uses the same behavior.

### The desired behavior

A test annotated with this annotation should only run if the tests it depends on are successful. If that's not the case this one shouldn't be executed and should be marked as "skipped due to its dependencies aren't meet". 

### Advantages:

Reading the test report is clear. A test marked as failed indicates that the tested behavior is faulty. A test marked as "skipped due to [...]" is precise. 
Finding and fixing the root cause of the failing tests is also easier. Look  at the test, fix all the failing ones, rerun.

This is advantageous to the current state, because as of now, you need to look through all the failing tests, figure out which ones is truly faulty and fix those.

**Comment by sbrannen** [comment] 2021-11-08 09:26
- Closing as a duplicate of #1767

**Closed by sbrannen** 2021-11-08 09:26 UTC
Labels: status: new

**Comment by Hu1buerger** [comment] 2021-11-08 15:02
@sbrannen It seems as if that never made it to production. And I firmly believe this is a feature to reduce ambiguity
