### ISSUE TITLE
Support for fail-fast in Ordered tests

### ISSUE THREAD

**Issue by abelsromero** [junit-team/junit5#3099] opened 2022-12-01 10:10 UTC
We use `@Order` to define user stories so that each test in a class accomplishes a validation and strictly depends on previous ones and is required by the following ones.
Currently `@Order` in case of error continues executing the following tests in the class which causes other tests to fail consuming resources and polluting test reports.

I'd be useful to have a fail-fast configuration so that on a failure no more tests are executed.
This would be specially helpful in convination of [Test Retry Gradle plugin](https://github.com/gradle/test-retry-gradle-plugin) with new `classRetry` feature.

*Example:*
Currently:
  on a class with tests 1, 2 and 3. If two fails we see 1, 2 and 3 run, with 2 and 3 failing.

We'd expect that:
  on a class with tests 1, 2 and 3. If two fails we see 1, 2, with 2 failing. 3 should be ignored or marked as skipped.

**Comment by marcphilipp** [comment] 2022-12-01 10:25
It's possible to implement this behavior using a custom extension:
```java
@SkipRemainingOnFailure
class SkipRemainingOnFailureDemo {

	@Test
	@Order(1)
	void a() {
	}

	@Test
	@Order(2)
	void b() {
		fail();
	}

	@Test
	@Order(3)
	void c() {
	}
}

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
@TestMethodOrder(OrderAnnotation.class)
@ExtendWith(SkipRemainingOnFailure.Extension.class)
@interface SkipRemainingOnFailure {

	class Extension implements TestWatcher, ExecutionCondition {

		static final Namespace NAMESPACE = Namespace.create(Extension.class);

		@Override
		public void testFailed(ExtensionContext context, Throwable cause) {
			// Store in extension context of parent (i.e. test class) so that subsequent test can see failure
			context.getParent()
					.orElseThrow(() -> new RuntimeException("test without parent"))
					.getStore(NAMESPACE)
					.put("failed", true);
		}

		@Override
		public ConditionEvaluationResult evaluateExecutionCondition(ExtensionContext context) {
			return context.getStore(NAMESPACE).getOrDefault("failed", Boolean.class, false)
					? ConditionEvaluationResult.disabled("Skipping due to prior failure")
					: ConditionEvaluationResult.enabled("No prior failure");
		}
	}
}
```

**Comment by marcphilipp** [comment] 2022-12-01 10:32
Duplicate of #48

**Closed by marcphilipp** 2022-12-01 10:32 UTC
Labels: theme: extensions, theme: execution, component: Jupiter, status: new
