### ISSUE TITLE
Scopes + Dependency Injection discussion 

### ISSUE THREAD

**Issue by paul-hammant** [junit-team/junit5#926] opened 2017-07-09 20:49 UTC
**Feature request.** 

Note: this is a continuation of one part of the conversation of https://github.com/junit-team/junit5-samples/issues/29

Can we have a new callback `BeforeTestInstantiationCallback` please? 

I want to be able to compose a container that is scoped for the test invocation like this https://github.com/paul-hammant/junit5-maven-picocontainer/blob/master/src/test/java/com/example/project/Composition.java#L48 on a just in time basis.

After each test, I'd expect the JUnit5 to discard the scoped store, and the way PicoContainer is coded, that'll just make the scoped container eligible for GC too.  It isn't necessary to know, but the child container has a reference to the parent, but the parent does not have a reference to any children, in this configuration.

**Comment by marcphilipp** [comment] 2017-07-10 10:44
Duplicate of #839.

**Closed by marcphilipp** 2017-07-10 10:44 UTC
