### ISSUE TITLE
Running tests from directory not in class path

### ISSUE THREAD

**Issue by MarioKusek** [junit-team/junit5#553] opened 2016-11-01 01:28 UTC
I am trying to run tests that are in directory `src/main/resources/Calculator-1.0-SNAPSHOT-tests`, which is **not in classpath**. The launcher does not find any test. If I put tests in code in IntelliJ project it works fine, so there is no problem in actual tests. The name of the test class is CalulatorAdditionTest.

Here is code that I run:

```
LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request()
        .selectors(
                selectClasspathRoots(new HashSet<>(Arrays.asList(
                        Paths.get("src/main/resources/Calculator-1.0-SNAPSHOT"),
                        Paths.get("src/main/resources/Calculator-1.0-SNAPSHOT-tests")
                )))
        )
        .filters(includeClassNamePatterns(".*Test"))
        .build();
Launcher launcher = LauncherFactory.create();

SummaryGeneratingListener listener = new SummaryGeneratingListener();//new TestListener();
launcher.registerTestExecutionListeners(listener);
launcher.execute(request);

TestExecutionSummary summary = listener.getSummary();
summary.printTo(new PrintWriter(System.out));
summary.printFailuresTo(new PrintWriter(System.out));
```

The result of running is:

```
Test run finished after 26 ms
[         1 containers found      ]
[         0 containers skipped    ]
[         1 containers started    ]
[         0 containers aborted    ]
[         1 containers successful ]
[         0 containers failed     ]
[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]
```

In this project I use github version with commit 0818031804f77213d04285d4b3c5d3c4039f6fef. In pom.xml I have following:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>testing</groupId>
    <artifactId>JUnitTester</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>1.8</java.version>
        <junit.jupiter.version>5.0.0-SNAPSHOT</junit.jupiter.version>
        <junit.vintage.version>4.12.0-SNAPSHOT</junit.vintage.version>
        <junit.platform.version>1.0.0-SNAPSHOT</junit.platform.version>
    </properties>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.jupiter.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <version>${junit.platform.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-engine</artifactId>
            <version>${junit.platform.version}</version>
        </dependency>
    </dependencies>
</project>
```

**Comment by smoyer64** [comment] 2016-11-01 01:53
Without overriding Maven conventions, .java files placed in src/main/resources won't be compiled into .class files.  Is there some reason you're not putting your tests into src/test/java?

**Comment by sbrannen** [comment] 2016-11-01 03:49
Classpath roots must contain compiled code (i.e., `.class` files). 

JUnit does **not** compile your code for you.

So unless "src/main/resources/Calculator-1.0-SNAPSHOT" or "src/main/resources/Calculator-1.0-SNAPSHOT-tests" contains `CalulatorAdditionTest.class`, what you are attempting will never work, and that's by design.

I am therefore closing this issue as _invalid_.

However, if you determine that compiled classes in the classpath are not getting picked up appropriately, please add additional comments here with further information.

**Closed by sbrannen** 2016-11-01 03:49 UTC

**Comment by MarioKusek** [comment] 2016-11-01 07:06
I have not been clear. I have compiled classes in src/main/resources and they are not picked up by engine. Here is structure of those directories:

```
$ tree Calculator-1.0-SNAPSHOT
Calculator-1.0-SNAPSHOT
├── META-INF
│   ├── MANIFEST.MF
│   └── maven
│       └── hr.fer.oop
│           └── Calculator
│               ├── pom.properties
│               └── pom.xml
└── hr
    └── fer
        └── oop
            └── Calculator.class

7 directories, 4 files
$ tree Calculator-1.0-SNAPSHOT-tests 
Calculator-1.0-SNAPSHOT-tests
├── META-INF
│   ├── MANIFEST.MF
│   └── maven
│       └── hr.fer.oop
│           └── Calculator
│               ├── pom.properties
│               └── pom.xml
└── hr
    └── fer
        └── oop
            ├── CalculatorDivisionTest.class
            └── CalulatorAdditionTest.class
```

**Comment by marcphilipp** [comment] 2016-11-01 08:25
It will only work if the class files are _on_ the classpath. In order to achieve that you can create a custom ClassLoader (see [ExecuteTestsTask](https://github.com/junit-team/junit5/blob/master/junit-platform-console/src/main/java/org/junit/platform/console/tasks/ExecuteTestsTask.java#L70-L79)) and replace the current thread's context class loader (see [CustomContextClassLoaderExecutor](https://github.com/junit-team/junit5/blob/master/junit-platform-console/src/main/java/org/junit/platform/console/tasks/CustomContextClassLoaderExecutor.java)).

**Comment by MarioKusek** [comment] 2016-11-01 09:00
OK, thanks for clarification. I will try that way. 

To get back to ClasspathRootSelector. So, setting ClasspathRootSelector in LauncherDiscoveryRequest is not intended for external use. Am I correct?

**Comment by marcphilipp** [comment] 2016-11-01 09:01
What do you mean by external use?

**Comment by MarioKusek** [comment] 2016-11-01 09:15
I mean setting ClasspathRootSelector to find classes outside of classpath of current thread's context class loader, like in this example:

 ```
LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request()
        .selectors(
                selectClasspathRoots(new HashSet<>(Arrays.asList(
                        Paths.get("src/main/resources/Calculator-1.0-SNAPSHOT"),
                        Paths.get("src/main/resources/Calculator-1.0-SNAPSHOT-tests")
                )))
        )
        .build();
```

**Comment by marcphilipp** [comment] 2016-11-01 09:16
By "classpath root" we're referring to a directory or JAR file that's on the classpath. So, yes, if it's not on the classpath it will get silently ignored.

**Comment by MarioKusek** [comment] 2016-11-01 10:12
Thanks
