### ISSUE TITLE
Selecting a test method with a type parameter argument fails

### ISSUE THREAD

**Issue by no2chem** [junit-team/junit5#966] opened 2017-07-19 17:05 UTC
Version: Junit 5.0.0-M6

In an exploration of using type arguments in a parameter resolver, it seems that selecting a generic type parameter fails. For example, I have code like this:

```java
public interface MapContract<M extends Map<K,V>, K, V> extends TestableMap<M, K, V> {
    @InterfaceTest
    default void canPut(M map, K k1, V v1) {
        map.put(k1, v1);

        assertThat(map)
                .containsExactly(MapEntry.entry(k1, v1));
    }
```

If I run the entire test class, it seems to work okay. If I try to select canPut(M,K,V)() in IntelliJ, I get:
```java
WARNING: TestEngine with ID 'junit-jupiter' failed to discover tests
org.junit.platform.commons.JUnitException: Failed to load parameter type [M]
	at org.junit.platform.commons.util.ReflectionUtils.lambda$loadRequiredParameterType$10(ReflectionUtils.java:694)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.junit.platform.commons.util.ReflectionUtils.loadRequiredParameterType(ReflectionUtils.java:693)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at org.junit.platform.commons.util.ReflectionUtils.resolveParameterTypes(ReflectionUtils.java:688)
	at org.junit.platform.commons.util.ReflectionUtils.findMethod(ReflectionUtils.java:701)
	at org.junit.platform.engine.discovery.MethodSelector.lazyLoadJavaMethod(MethodSelector.java:169)
	at org.junit.platform.engine.discovery.MethodSelector.getJavaMethod(MethodSelector.java:142)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.lambda$resolveSelectors$3(DiscoverySelectorResolver.java:62)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.jupiter.engine.discovery.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:61)
	at org.junit.jupiter.engine.JupiterTestEngine.resolveDiscoveryRequest(JupiterTestEngine.java:68)
	at org.junit.jupiter.engine.JupiterTestEngine.discover(JupiterTestEngine.java:61)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:130)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:117)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:82)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Expected behavior:
Should be able to select test class with type arguments.

**Comment by sbrannen** [comment] 2017-07-19 18:28
Closing this issue since it is a duplicate of #965.

**Closed by sbrannen** 2017-07-19 18:28 UTC
