### ISSUE TITLE
@Ignore'd Parameterized JUnit 4 test class with VintageTestEngine

### ISSUE THREAD

**Issue by gabalawi** [junit-team/junit5#2145] opened 2020-01-08 12:20 UTC
Trying to migrate our Tests from JUnit4 to Jupiter I thought I could as a first step simply eliminate the explicit JUnit4-dependency by substituting it with the junit-jupiter-migrationsupport library (version 5.5.2). This would allow us to rewrite the tests little by little. Unfortunately we have some rather ill performing parameterized tests, which we ignore every now and then, as it comes. And here I observed the following behaviour:

When executing a parameterized JUnit4 test with maven (version 3.6.3, surefire plugin version 3.0.0-M4), the static "parameters" method is executed twice. The "test" method itself ist then executed once.
Moreover, when ignoring the test either at class or at method level, the "parameters"-method is still executed (only the test method iteself is skipped)

## Steps to reproduce
I have put some simple unit tests here:
https://github.com/gabalawi/junit5-migration

## Context

 - Used versions (Jupiter/Vintage/Platform): 5.5.2
 - Build Tool/IDE: Maven 3.6.3

## Deliverables
see github link above

**Comment by sbrannen** [comment] 2020-01-08 14:51
> I thought I could as a first step simply eliminate the explicit JUnit4-dependency by substituting it with the junit-jupiter-migrationsupport library (version 5.5.2).

Just to be clear, `junit-jupiter-migrationsupport` does not replace or implement JUnit 4. Rather, it provides migration support for a limited set of JUnit 4 features when writing tests using JUnit Jupiter.

----

Thanks for providing the examples. When I execute them within Eclipse, I see the following behavior.

JUnit 4

```
execute JUnit4IgnoredParameterizedTestMethod#parameters
execute JUnit4ParameterizedTest#parameters
execute JUnit4ParameterizedTest#test
```

JUnit Platform / VintageTestEngine

```
execute JUnit4IgnoredParameterizedTestMethod#parameters
execute JUnit4IgnoredParameterizedTest#parameters
execute JUnit4ParameterizedTest#parameters
execute JUnit4ParameterizedTest#test
```

The only difference is the presence of the `execute JUnit4IgnoredParameterizedTest#parameters` line when executing the tests via the `VintageTestEngine`.

> When executing a parameterized JUnit4 test with maven (version 3.6.3, surefire plugin version 3.0.0-M4), the static "parameters" method is executed twice.

If the `parameters()` method in a single test class is executed twice, that sounds to me like an issue with Maven Surefire.

> Moreover, when ignoring the test either at class or at method level, the "parameters"-method is still executed (only the test method iteself is skipped)

When the test is ignored at the method level, I see the same behavior with JUnit 4 and the `VintageTestEngine` (see example output above): the `parameters()` method is always invoked.

However, when the test class is ignored I also see that the `parameters()` method is invoked only with the `VintageTestEngine`.

It turns out that the latter behavior is by design. The Javadoc for `org.junit.vintage.engine.discovery.IgnoringRunnerDecorator` states the following.

> Decorator for Runners that will be ignored completely.
> 
> Contrary to `org.junit.internal.builders.IgnoredClassRunner`, this runner returns a complete description including all children.

Thus, the `VintageTestEngine` intentionally allows the children to be _discovered_ in order to make that information available in reports, even though the children are not _executed_. For a `Parameterized` runner, this means that the static `@Parameters` method will be invoked even if the test class is annotated with `@Ignore`.

@marcphilipp, would you like to provide any further information on this topic?

**Comment by gabalawi** [comment] 2020-01-14 13:07
@sbrannen Thank you very much for clarifying my questions.

**Comment by marcphilipp** [comment] 2020-01-18 17:56
Surefire calls `Launcher.discover()` once per test class to check whether it yields any tests. The result, however, is discarded. Later, it calls `Launcher.execute()` with an request that includes all classes that passed the previous check. In the case of JUnit 4 that leads to Runners being instantiated twice which in the case of `Parameterized` causes `@Parameters` method to be executed. I'm afraid there's nothing we can do on our end. Other build tools, such as Gradle, don't discover before they execute. Instead they pass the list of all potential test classes to `Launcher.execute()` and just handle the resulting events. I can't tell whether that's a strategy that Surefire could also employ. Please report an issue for Surefire to make them aware of the issue.

**Closed by marcphilipp** 2020-01-18 17:56 UTC
Labels: component: Vintage
