### ISSUE TITLE
Running tests in certain order

### ISSUE THREAD

**Issue by noopur2507** [junit-team/junit5#884] opened 2017-06-12 10:18 UTC
I do not see any equivalent of the JUnit 4 method `org.junit.runner.Request.sortWith(Comparator<Description> comparator)` in JUnit 5 M4, which can be used to run the tests in a certain order, defined by the comparator.

Is it planned to provide such support or can it be done in some other way?

Eclipse uses this to rerun a test with failures first, which has been disabled for JUnit 5: [bug 518052](https://bugs.eclipse.org/bugs/show_bug.cgi?id=518052).

**Comment by sormuras** [comment] 2017-06-13 05:59
Related issue: #111 (and #90)

**Comment by sbrannen** [comment] 2017-06-14 15:11
Hi @noopur2507,

At the moment there is currently no mechanism for ordering the execution of tests.

Once #48 is addressed this will likely change since _ordering_ is a requirement of scenario tests. Having said that, however, that support may only exist within JUnit Jupiter instead of the Platform proper.

I am therefore going to reopen #13 and am closing this issue as a duplicate of #13.

**Closed by sbrannen** 2017-06-14 15:11 UTC
Labels: component: Jupiter, component: Platform, status: team discussion, theme: execution, theme: ordering, type: enhancement
