### ISSUE TITLE
Test class with all test methods @Disabled shouldn't run @BeforeAll / @AfterAll methods

### ISSUE THREAD

**Issue by thomasdarimont** [junit-team/junit5#415] opened 2016-07-19 17:25 UTC
Currently the 5.0.0-M1 test class Methods annotated with `@BeforeAll` and `@AfterAll` are executed even if the Test class only contains @Disabled methods.

I would expect that those `@BeforeAll` and `@AfterAll` are only executed if there is work to do e.g. prepare an environment for tests and clean-up afterwards.

```java
package demo;


import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Created by tom on 19.07.16.
 */
public class Junit5TestLifeCycleMethods {

    @BeforeAll
    static void beforeAll() {
        System.out.println("Before all");
    }

    @BeforeEach
    void beforeEach() {
        System.out.println("Before each");
    }

    @AfterEach
    void afterEach() {
        System.out.println("After each");
    }

    @AfterAll
    static void afterAll() {
        System.out.println("After all");
    }

    @Test
    @Disabled
    void someTest() {
        System.out.println("run someTest");
        assertTrue(true);
    }

    @Test
    @Disabled
    void anotherTest() {
        System.out.println("run anotherTest");
        assertTrue(true);
    }
}
``` 

Outputs in idea:
```
INFO: Discovered TestEngines with IDs: [junit-vintage, junit-jupiter]
Empty test suite.
Before all

Optional[void demo.Junit5TestLifeCycleMethods.anotherTest()] is @Disabled
After all
Process finished with exit code 0
```

Maven Dependencies used:
```xml
<dependencies>
        <!-- JUnit 5-->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.0.0-M1</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.vintage</groupId>
            <artifactId>junit-vintage-engine</artifactId>
            <version>4.12.0-M1</version>
        </dependency>
    </dependencies>
```

**Comment by mmichaelis** [comment] 2016-07-20 05:15
I agree with you that this would be nice. But aren't the ways a test can be skipped just too varied? For example we don't use an annotation `@Ignored` (`@Disabled`) nowadays but *custom annotations* like:

* `@Label("known-issue-XYZ")` to ignore tests with a given label unless a system property is set (`labelCondition=skip`) or
* `@Browser(include='firefox', exclude={'chrome','internet explorer'})`

Other tests are ignored by assumption failures raised just within the test.

So I think with these various ways to skip a test there is no obvious solution at hand how to deal with this problem but tell the one who disabled all tests to possibly already do this on class level (oh, of course this should work: If a test class is marked as disabled BeforeAll, AfterAll should not run).

And even if we had a solution for this: There are also various ways (at least two, I think) to have code executed before and after all test like implementing the appropriate callbacks (`BeforeAllCallback`, `AfterAllCallback`).

So while I think your idea is nice and desirable I don't see an easy solution to that. You possibly could make the implementation of `@BeforeAll` lazy and trigger it in `@BeforeEach` and it contains code to execute only once. And in addition to that of course `@AfterAll` only executes the clean-up code if the `@BeforeAll` had actually been triggered.

**Comment by marcphilipp** [comment] 2016-07-24 12:43
It should be possible for a container to check if all of its children are to be skipped. Since containers can be nested this will require recursion in some cases. To prevent asking nodes multiple times we would have to cache their results, though. We will discuss this in the team.

**Comment by sbrannen** [comment] 2016-07-24 13:13
> It should be possible for a container to check if all of its children are to be skipped.

I don't think this is feasible. 

A condition for a test within a container may only be able to decide if it's _enabled_ if the container-level _before callback_ properly sets up the required infrastructure for the test.

For example, consider a container-level _before_ method or callback that sets up an in-memory database. If that code is not executed, then the database won't be available, and a method-level condition that checks for the existence of the database will _never_ return _enabled_.

So, unless I'm missing something, it does not make sense to query conditions for tests before executing the _before_ methods and callbacks for the enclosing container.

With that in mind, I am inclined to close this issue as "works as designed".

**Comment by marcphilipp** [comment] 2016-07-24 13:18
Point taken -- you're absolutely right!

**Comment by sbrannen** [comment] 2016-07-24 13:18
Furthermore, I agree with the rationale presented by @mmichaelis.

FYI: you may not be aware of it, but `@Disabled` is not handled specially in JUnit Jupiter. On the contrary, it is evaluated by a `DisabledCondition` that is internal to JUnit Jupiter.

`@Ignored` from JUnit 4 is _static_ in nature, and although `@Disabled` from JUnit Jupiter may appear to be _static_ in nature... it is in fact _dynamic_ in nature, since all conditions in JUnit Jupiter are dynamically evaluated.

Thus, the only correct way to disable an entire container is to physically disable the container itself. In the case of JUnit Jupiter, @mmichaelis is 100% correct: the developer should just annotated the test class with `@Disabled`.

**Closed by marcphilipp** 2016-07-24 13:18 UTC

**Comment by sbrannen** [comment] 2016-07-24 13:37
@thomasdarimont,

> Currently the 5.0.0-M1 test class Methods annotated with `@BeforeAll` and `@AfterAll` are executed even if the Test class only contains `@Disabled` methods.

FWIW, you're right: this behavior does not align with that of JUnit 4. Specifically, The JUnit 4 `ParentRunner` has an `areAllChildrenIgnored()` method which it uses to determine if class-level callbacks should be invoked.

So, I understand why you raised this issue; however, as I mentioned previously, _conditions_ in JUnit Jupiter are quite different from the _one-size-fits-all_ `@Ignore` annotation in JUnit 4.

One of our major goals with JUnit Jupiter is to avoid special handling for features provided by the framework itself. In other words, we aim to eat our own dog food, and in light of that, `@Disabled` should not receive any special treatment above and beyond the support provided to third-party extension (e.g., condition) implementers.

Does that make things clear? 😉

**Comment by thomasdarimont** [comment] 2016-07-25 09:19
Thanks @sbrannen for the explanation - makes sense to me now - but I still think it is a bit unintuitive.

> @Ignored from JUnit 4 is static in nature, and although @Disabled from JUnit Jupiter may appear to be static in nature... it is in fact dynamic in nature, since all conditions in JUnit Jupiter are dynamically evaluated.

Just because the implementation of `@Disabled` makes it a dynamic condition it doesn't change that the perceived intent for the developer - (that the annotated test is disabled, and if all tests are disabled no before.*/after.* should run) at least not at the first glance.

> One of our major goals with JUnit Jupiter is to avoid special handling for features provided by the framework itself. In other words, we aim to eat our own dog food, and in light of that, @Disabled should not receive any special treatment above and beyond the support provided to third-party extension (e.g., condition) implementers.

In the light of this design goals it all makes sense, but I wonder whether there is some kind of abstraction missing. E.g. what if I wanted to implement exactly that functionality: `run expensive operations in before.* / after.* only if any test well be executed at all`

I understand that adding special handling for `@Disabled` doesn't comply with your design goals - but perhaps there is room for an abstraction that allows to register "veto" statements
for tests / setup / teardown logic.

Btw. whilst looking at the [javadoc](https://github.com/junit-team/junit5/blob/43b33fa09236110eae742e152f78b726052b18aa/junit-jupiter-api/src/main/java/org/junit/jupiter/api/Disabled.java#L24) of `@Disabled` states that 
```...is used to signal that the annotated test class or test method is currently 
<em>disabled</em> and should not be executed...
```
I noticed that the `should` at the end of the sentence implies that there could be scearious where `@Disabled` is be ignored - is this intended?

**Comment by marcphilipp** [comment] 2016-07-25 13:48
> I noticed that the `should` at the end of the sentence implies that there could be scearious where `@Disabled` is be ignored - is this intended?

Yes, you can optionally deactivate the evaluation of conditions, see http://junit.org/junit5/docs/current/user-guide/#extensions-conditions.
