### ISSUE TITLE
JUnit Jupiter Assumptions do not work in @BeforeAll methods

### ISSUE THREAD

**Issue by jkarshin** [junit-team/junit5#1592] opened 2018-09-20 19:15 UTC
* JUnit version: 5.1.0
* JUnit platform version: 1.1.0

The following test will fail with a `TestAbortedException`:

```java
public class AssumptionTestJUnit5 {

    @BeforeAll
    static void setup() {
        Assumptions.assumeTrue(false);
    }

    @Test
    void someTest() throws Exception {
        // Never reached
    }
}
```

I would expect that a failed assumption in the setup method would simply skip the tests instead of triggering a test failure.

The following JUnit4 test (run against the JUnit4 test runner) matches my expectations; it skips the tests instead of reporting a failure:

```java
public class AssumptionTestJUnit4 {

    @BeforeClass
    public static void setup() {
        Assume.assumeTrue(false);
    }

    @Test
    public void someTest() throws Exception {
        // Never reached
    }
}
```

**Comment by sbrannen** [comment] 2018-09-22 11:29
Thanks for bringing this to our attention!

I have confirmed that this is in fact a _bug_.

Specifically, it's a bug in the internals of the `HierarchicalTestEngine`, and the bug exists currently on the `master` branch.

Note that executing the example `AssumptionTestJUnit4` test class on the JUnit Platform via the `VintageTestEngine` also results in a failure instead of the test class being skipped.

**Comment by sbrannen** [comment] 2018-09-22 11:32
I believe the _fix_ for this bug must go into `org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively()` (on `master`).

**Comment by sbrannen** [comment] 2018-09-22 11:34
Or perhaps proper handling of "aborting exceptions" in `org.junit.platform.engine.support.hierarchical.NodeTestTask<C>` would be the better place for such a fix.

**Comment by sbrannen** [comment] 2018-09-22 11:36
We'll likely need to _open up_ `org.junit.platform.engine.support.hierarchical.ThrowableCollector.hasAbortedExecution(Throwable)` so that it can be queried from within `reportCompletion()`.

**Comment by sbrannen** [comment] 2018-09-22 15:03
**Update**:

This sounds like a known [bug in Eclipse IDE](https://bugs.eclipse.org/bugs/show_bug.cgi?id=536005) which is marked as resolved for Eclipse 4.9 M2.

Since we have tests in place that verify support for failed assumptions in _before all_ callback methods, I am therefore inclined to close this issue as "works as designed", but I am awaiting a confirmation from @jkarshin that the behavior was noticed in a version of Eclipse IDE prior to version 4.9 M2.

**Comment by sbrannen** [comment] 2018-09-22 15:06
@jkarshin, since you stated "The following JUnit4 test (run against the JUnit4 test runner)", I assume you are referring to the _Eclipse JUnit 4 Test Runner_, but I'd still appreciate a confirmation from you. 😉

**Comment by jkarshin** [comment] 2018-09-22 17:16
@sbrannen Thanks for the quick reply! Yes, I was running these tests through Eclipse 4.8.0.

I'll update my Eclipse and try the test again on Monday.

**Comment by sbrannen** [comment] 2018-09-23 11:59
You're welcome, and thanks for the feedback.

By the way, I just verified the expected behavior in the latest version of Eclipse:

> Eclipse IDE for Java Developers
> Version: 2018-09 (4.9.0)
> Build id: 20180917-1800
> OS: Mac OS X, v.10.13.6, x86_64 / cocoa
> Java version: 11

The bug has in fact been fixed in Eclipse, and I am therefore closing this issue.

**Closed** 2018-09-23 13:01 UTC
Labels: component: Jupiter, component: Platform, component: Vintage, type: bug

**Comment by Diego11914** [comment] 2020-11-26 20:38
I am still seen this issue on intelliJ
![image](https://user-images.githubusercontent.com/49316187/100390130-fababd80-2ff4-11eb-93da-bba954d32816.png)
