### ISSUE TITLE
DiscoverySelectors#selectPackage does not select packages from JAR

### ISSUE THREAD

**Issue by artem-fedorov** [junit-team/junit5#1493] opened 2018-07-10 13:59 UTC
Hi,

I use JUnit 5.2.0 and I want to select classes from package that locate in jar file.
```
        LauncherDiscoveryRequest request = LauncherDiscoveryRequestBuilder.request().selectors(selectPackage("my.custom.package")).build();
        Launcher launcher = LauncherFactory.create();
        launcher.execute(request);
```

If my package exists as file: URL=`file:/path_to_project/target/my/custom/package` it works fine, but if this package locate in jar: URL=`jar:file:/path_to_jar/tests.jar!/my/custom/package/` org.junit.platform.commons.util.ClasspathScanner does not find it.

Solution:

[ClasspathScanner](https://github.com/junit-team/junit5/blob/master/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ClasspathScanner.java#L211) should append `/` symbol  at the end:

```
now:
packagePath("my.custom.package") -> "my/custom/package"
with fix:
packagePath("my.custom.package") -> "my/custom/package/"
```
Because `getClassLoader().getResources(String)` on [line 217](https://github.com/junit-team/junit5/blob/master/junit-platform-commons/src/main/java/org/junit/platform/commons/util/ClasspathScanner.java#L217) expect such result from `packagePath` method.

**Comment by artem-fedorov** [comment] 2018-07-10 13:59
@undera

**Comment by marcphilipp** [comment] 2018-07-10 20:47
Thanks for the bug report! Since we have tests in place that verify the implementation works correctly, we need a few more details in order to reproduce the issue. Could you please provide a minimal sample project that reproduces the issue?

**Comment by artem-fedorov** [comment] 2018-07-11 09:43
@marcphilipp look at this repo, please
https://github.com/artem-fedorov/junit5-tests/blob/master/src/main/java/TestRunner.java

**Comment by sbrannen** [comment] 2018-07-11 11:45
Thanks for the repo, @artem-fedorov.

We'll look into it.

**Comment by sbrannen** [comment] 2018-07-11 11:45
Tentatively slated for 5.3 RC1 for further investigation.

**Comment by marcphilipp** [comment] 2018-07-16 10:21
Possibly related: #1430.

**Comment by marcphilipp** [comment] 2018-07-25 19:36
I checked out the sample project but it seems to work for me. When I run `TestRunner` it succeeds with the following output:

```
file:/Users/marc/Desktop/junit5-tests-master/target/classes/junit-test-1.1.jar
jar:file:/Users/marc/Desktop/junit5-tests-master/target/classes/junit-test-1.1.jar!/
method 1
method 2
test 1
test 2
```

@artem-fedorov What am I missing? 🤔

**Comment by artem-fedorov** [comment] 2018-07-25 20:43
@marcphilipp 
interesting, I tested on 3 machines and I have the following output:
* Ubuntu 16.04.2 LTS (Xenial Xerus), Oracle Java 1.8.0_131, Idea 181.5087.20
```
file:/home/artem/home/junit5-tests/target/classes/junit-test-1.1.jar
jar:file:/home/artem/home/junit5-tests/target/classes/junit-test-1.1.jar!/
Exception in thread "main" java.lang.AssertionError: expected:<4> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at TestRunner.main(TestRunner.java:52)
```
* Windows 10, Oracle Java 1.8.0_161, Idea 181.4668.68
```
file:/C:/Users/Artem/Downloads/junit5-tests-master/junit5-tests-master/target/classes/junit-test-1.1.jar
jar:file:/C:/Users/Artem/Downloads/junit5-tests-master/junit5-tests-master/target/classes/junit-test-1.1.jar!/
method 1
method 2
test 1
test 2
```
* Ubuntu 16.04.2 LTS (Xenial Xerus), Oracle Java 1.8.0_181, Idea 182.3684.101
```
file:/home/jenkins/Downloads/junit5-tests-master/target/classes/junit-test-1.1.jar
jar:file:/home/jenkins/Downloads/junit5-tests-master/target/classes/junit-test-1.1.jar!/
method 1
method 2
test 1
test 2
```
Is it possible depends my Java version?

**Comment by marcphilipp** [comment] 2018-07-26 06:19
> Is it possible depends my Java version?

Looks like it. Could you try JDKs with 1.8.0_131 < version < 1.8.0_161 so we can find out when this was changed/fixed?

**Comment by artem-fedorov** [comment] 2018-07-26 16:51
I checked 
1.8.0_141 - does not work
1.8.0_144 - fixed

**Comment by marcphilipp** [comment] 2018-07-28 14:46
Thanks for the analysis!

Sounds like it's this issue:

> **java.util.zip.ZipFile.getEntry() now always returns the ZipEntry instance with a / ended entry name for directory entry**  
> The java.util.zip.ZipEntry API doc specifies “A directory entry is defined to be one whose name ends with a /“. However, in previous JDK releases, java.util.zip.ZipFile.getEntry(String entryName) may return a ZipEntry instance with an entry name that does not end with / for an existing zip directory entry when  
>   
> the passed in argument entryName does not end with a **/**, and  
> there is a matching zip directory entry with name entryName + / in the zip file.  
> With this release, the name of the ZipEntry instance returned from java.util.zip.ZipFile.getEntry() always ends with / for any zip directory entry.  
>   
> To revert to the previous behavior, set the system property jdk.util.zip.ensureTrailingSlash to “false”.  
>   
> This change was made in order to fix a regression introduced in JDK 8u141 when verifying signed JARs that has caused some WebStart applications to fail to load.  


Source: http://www.oracle.com/technetwork/java/javase/8u144-relnotes-3838694.html

**Comment by marcphilipp** [comment] 2018-07-28 17:53
Since it works with every JDK I tried >= 1.8.0_144 (9, 10, 11-ea), I'm closing this issue. Please use a recent JDK.

**Closed by marcphilipp** 2018-07-28 17:53 UTC
Labels: component: Platform, type: bug

**Comment by gagansuri** [comment] 2023-06-15 04:44
I am facing the same issue. select package does not work from a jar file when running inside a docker container

**Comment by marcphilipp** [comment] 2023-06-16 11:18
@gagansuri Which exact Java version are you using inside your container?
